### ISSUE TITLE
OKTA Widget asks for a password if user doesn't exist with passwordlessAuth feature

### ISSUE THREAD

**Issue by azhivaeva-flo** [okta/okta-signin-widget#1020]
## I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I use okta-signin-widget on Angular with passwordlessAuth feature. It works well if the user exists.
![image](https://user-images.githubusercontent.com/26054907/73004886-1f646880-3e19-11ea-9f1f-3a44a30ae752.png)

### Expected behavior

If the user doesn't exist, the widget should display an error.

### What went wrong?

If the user doesn't exist, the widget asks for a password.
![image](https://user-images.githubusercontent.com/26054907/73004975-3f942780-3e19-11ea-842a-35bf8f731356.png)

### Steps to reproduce

Set up your OKTA account to use MFA and use a nonexistent email.

### Your environment

  - Okta Sign-In Widget Version: 3.4.2
  - Browser: Chrome
  - OS: Windows
  - Language: JavaScript

**Comment by swiftone** [comment]
Hi @azhivaeva-flo - Thanks for the report.  Based on your description, I believe this is working as intended - we don't reveal that the user doesn't exist as a technique of not revealing which accounts are valid targets for attack.

If you have questions as to options and further details, please reach out to our support team (developers@okta.com) and they can discuss specifics of your organization and use of Okta.  

If I've failed to understand your issue, please let me know.
