### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by alexandermaisey** [okta/okta-signin-widget#1058]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Error: only one instance of babel-polyfill is allowed when using okta-signin-widget 3.7.3 on npm run start

### Expected behavior

Page should render without error.  My application is not explicitly using any other babel-polyfill

### What went wrong?

×
Error: only one instance of babel-polyfill is allowed
▶ 3 stack frames were collapsed.
(anonymous function)
C:/Users/Development/Documents/GitHub/project/webpack:/okta-sign-in.min.js:45604
  45601 | /* 269 */
  45602 | /***/ (function(module, exports, __webpack_require__) {
  45603 | 
> 45604 | __webpack_require__(270);
  45605 | module.exports = __webpack_require__(472);
  45606 | 
  45607 | 
View compiled
▶ 3 stack frames were collapsed.
(anonymous function)
C:/Users/Development/Documents/GitHub/project/webpack:/webpack/universalModuleDefinition:2
  1 | (function webpackUniversalModuleDefinition(root, factory) {
> 2 | 	if(typeof exports === 'object' && typeof module === 'object')
  3 | 		module.exports = factory();
  4 | 	else if(typeof define === 'function' && define.amd)
  5 | 		define([], factory);
View compiled
(anonymous function)
C:/Users/Development/Documents/GitHub/project/webpack:/webpack/universalModuleDefinition:9
   6 | 	else if(typeof exports === 'object')
   7 | 		exports["OktaSignIn"] = factory();
   8 | 	else
>  9 | 		root["OktaSignIn"] = factory();
  10 | })(typeof self !== 'undefined' ? self : this, function() {
  11 | return 
  12 | 
View compiled
./node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.min.js
https://localhost:3003/static/js/2.chunk.js:43484:30
__webpack_require__
C:/Users/Development/Documents/GitHub/project/webpack/bootstrap:790
  787 | };
  788 | 
  789 | // Execute the module function
> 790 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  791 | 
  792 | // Flag the module as loaded
  793 | module.l = true;
View compiled
fn
C:/Users/Development/Documents/GitHub/project/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/modules/LoginPage.js
https://localhost:3003/static/js/10.chunk.js:20:110
__webpack_require__
C:/Users/Development/Documents/GitHub/project/webpack/bootstrap:790
  787 | };
  788 | 
  789 | // Execute the module function
> 790 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  791 | 
  792 | // Flag the module as loaded
  793 | module.l = true;
View compiled
fn
C:/Users/Development/Documents/GitHub/project/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

### Steps to reproduce
npm run start

### Your environment

  - Okta Sign-In Widget Version: 3.7.3
  - Browser: Any
  - OS: Any
  - Language: Any

**Comment by alexandermaisey** [comment]
Have determined that a dependency of my project requires babel-polyfill 7.8.3 but okta-signin-widget requires 6.23.0

Removing my dependency causes the the page to run normally but this could be problematic.

**Comment by swiftone** [comment]
@alexandermaisey - We have a fix for that, but the docs are trailing behind.  Can you see the updated docs here ( https://github.com/okta/okta-signin-widget/pull/1059 ) and see if this addresses your issue (using the non-polyfill bundle)

**Comment by aarongranick-okta** [comment]
Documentation has been updated: https://github.com/okta/okta-signin-widget/blob/master/README.md#using-the-okta-cdn

We provide a no-polyfill option from CDN.
