### ISSUE TITLE
Customized Help Link Text not showing up in Hosted SignIn Widget

### ISSUE THREAD

**Issue by chudel** [okta/okta-signin-widget#1081]
### I'm submitting a
  - [x ] bug report

### Background info
Help Link Text set in the Admin Console is not being honored in the hosted signin widget.

### Expected behavior
It's expected that the Help Link Text set by the admin be reflected in the hosted signin widget.

### What went wrong?

Please provide log or error messages if applicable.

### Steps to reproduce

1. Go to the console and enter a help text, such as "**More Information ...**"
![image](https://user-images.githubusercontent.com/5213899/76085724-9b0d1580-5f80-11ea-9bb6-6c3872e29d6a.png)

2. Preview or load the hosted signin widget. Observe that it continues to display "**Need help signing in?**"
![image](https://user-images.githubusercontent.com/5213899/76085755-abbd8b80-5f80-11ea-91ce-a1cda33ce9c8.png)

3. Examining config.helplinks does not show the admin-supplied value either.
![image](https://user-images.githubusercontent.com/5213899/76085897-f4754480-5f80-11ea-863c-ec8334b24d2d.png)

### Your environment

  - Okta Sign-In Widget Version: Hosted 3/Latest
  - Browser: Chrome / Firefox / IE
  - OS: Windows
  - Language: English

**Comment by swiftone** [comment]
Internal ref: OKTA-282548

**Comment by KostiantynDrozd-okta** [comment]
@chudel Thanks for your report,
Please visit https://developer.okta.com/docs/guides/style-the-widget/style-self-hosted/#modify-strings for more details.
I hope our answers helped.  I'm going to close this, feel free to re-open if needed (or ask new questions in new issues).  Also, check out the developer forum, it's great!
