### ISSUE TITLE
Default responseMode should be changed to query for pkce

### ISSUE THREAD

**Issue by restfulhead** [okta/okta-signin-widget#1094]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info
With the release of okta-auth-js 3.0, the default responseMode has changed:

> Previously, the default responseMode for PKCE was "fragment". It is now "query". Unless explicitly specified using the responseMode option, the response_mode parameter is no longer passed by token.getWithRedirect to the /authorize endpoint. The response_mode will be set by the backend according to the OpenID specification. Implicit flow will use "fragment" and PKCE will use "query". If previous behavior is desired, PKCE can set the responseMode option to "fragment".

This should also be changed in the widget, because otherwise if you don't specify responseMode it all, it will break. That's because the widget currently sends `response_mode=fragment` if no responseMode is configured, even if `pkce` is true.

### Expected behavior
Widget response mode should be set to what okta-auth-js does (which is based on OICD standards)

### What went wrong?
Widget response mode is set to 'fragment' even if `pkce` is true.

### Your environment
  - Okta Sign-In Widget Version: 3.8.1
  - @okta/okta-angular: 2.0.0
  - @okta/okta-auth-js: 3.0.0  
  - Browser: Chrome

**Comment by swiftone** [comment]
@restfulhead - We have an update of the Sign-in widget in the works that will address this difference.  As a workaround in the meantime, as you've discovered, you need to set the responseMode to `fragment` in okta-angular, so it will consume the callback that is generated by the widget.

**Comment by aarongranick-okta** [comment]
@restfulhead You could also set the responseMode to "query" in Signin Widget `authParams` config.

```
    signIn = new OktaSignIn({
      baseUrl: "<your base url>",
      clientId: "<your client id">,
      redirectUri: "<your redirect uri>"
      authParams: {
        pkce: true,
        responseMode: 'query',
    }})
```

**Comment by restfulhead** [comment]
Thanks, yes, I was able to set the `responseMode` param. However, it took me quite some time to figure out that I have to do this. I'm happy to hear that there's an update coming, so that other people don't run into the same issue...

**Comment by xmlguy74** [comment]
Setting the responseMode to query is not working for me. I am always seeing fragment in use. This is my config:

```
var signIn = new OktaSignIn({
      baseUrl: "https://<okta-domain>",
      el: "#widget-container",
      authParams: {
        display: 'page',
        pkce: true,
        responseMode: 'query'
      }
    });
```

**Comment by xmlguy74** [comment]
Forgot to mention what versions I am using:

```
    "@okta/okta-signin-widget": "^3.9.2",
    "@okta/okta-vue": "^2.0.0",
```

**Comment by swiftone** [comment]
Sign-in widget 4.x should now intelligently handle both PKCE and Implicit Flow connections without having to set responseMode.  

Please let us know if that does not address the problems you have encountered.

**Comment by swiftone** [comment]
Closing this issue as resolved in widget 4.x.
