### ISSUE TITLE
Failed to load sourcemap okta-sign-in.css.map

### ISSUE THREAD

**Issue by jamie-kount** [okta/okta-signin-widget#1124]
#761 # I'm submitting a
  - [ X] bug report
  - [ ] feature request

### Background info

We recently updated our okta sign in widget to use version 3.8.2 and are now getting a console warning (in Chrome but it's an error in Firefox/Safari) that it failed to load sourcemap  https://global.oktacdn.com/okta-signin-widget/3.8.2/css/okta-sign-in.css.map

When I go to that URL, I get the following error:
`
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>okta-signin-widget/3.8.2/css/okta-sign-in.css.map</Key>
<RequestId>66B8C719E23F683F</RequestId>
<HostId>
frH9EspC9vccRWilCwEC3JuvoUY42rGraXDjtcMG3jkvXSzFBKrF7YRdgXrOhZzk1aOODJKrROg=
</HostId>
</Error>
`

In our previous version (2.16.0) we were seeing similar warnings/errors:
https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.16.0/css/okta-theme.css.map
https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.16.0/css/okta-sign-in.css.map

### Expected behavior

Sourcemaps should load without causing any console errors or warnings.

### Your environment

  - Okta Sign-In Widget Version: 3.8.2
  - Browser: Chrome, Firefox and Safari
  - OS: 
  - Language:

**Comment by swiftone** [comment]
@jamie-kount - Thanks for the bug report!

Internal ref: OKTA-289857

**Comment by aarongranick-okta** [comment]
@jamie-kount It seems this issue was fixed by [this PR](https://github.com/okta/okta-signin-widget/pull/1208) back in 2020. If you are experiencing a problem with the latest version, please create a new issue. Thanks!
