### ISSUE TITLE
Incomplete parsing of factors object within the transaction

### ISSUE THREAD

**Issue by robotwiss** [okta/okta-signin-widget#1147]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

During the MFA prompt stage in Okta sign in widget, on click of the "Send me the Code" button, there is a failure on Factor.js:294 Uncaught TypeError: Cannot read property 'verify' of undefined which is caused by the incomplete parsing in factors causing the transaction to represent it as a json string instead of the expected arraylist.

![image (30)](https://user-images.githubusercontent.com/35041340/80012612-2db33680-8493-11ea-858a-7f94dddc21f0.png)

NOTE: Factors does seem to be parsed correctly higher up in the data > _embedded object, while still showing improperly parsed json string further down

![image (32)](https://user-images.githubusercontent.com/35041340/80013140-0872f800-8494-11ea-86f2-68b99dfa0581.png)

### Expected behavior

What should have happened? 

The factors should be parsed and represented as an array object and not cause a failure during the verify method.

![image (31)](https://user-images.githubusercontent.com/35041340/80012766-6bb05a80-8493-11ea-8a17-85b503aeaf62.png)

### What went wrong?

Factor.js:294 Uncaught TypeError: Cannot read property 'verify' of undefined
    at L.r.<anonymous> (Factor.js:294)
    at L.r.manageTransaction (BaseLoginModel.js:53)
    at L.r.save (Factor.js:271)
    at L.r.submit (SendEmailAndVerifyCodeForm.js:54)
    at D (underscore.js:762)
    at HTMLFormElement.<anonymous> (underscore.js:775)
    at HTMLFormElement.<anonymous> (underscore.js:122)
    at HTMLFormElement.dispatch (jquery.js:5228)
    at HTMLFormElement.g.handle (jquery.js:4880)

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

### Your environment

  - Okta Sign-In Widget Version: tried both 3.8.1 and 3.9.1
  - Browser: Chrome Version 81.0.4044.122 (Official Build) (64-bit)
  - OS: Mac OS Mojave Version 10.14.6
  - Language: Java/JSF/xhtml

**Comment by swiftone** [comment]
Internal ref: OKTA-293150

**Comment by denysoblohin-okta** [comment]
@robotwiss Do you have such issue with new versions of widget? 
What factors are in `factors` array object (what `factorType`s do they have)?

**Comment by denysoblohin-okta** [comment]
Closing this issue as no response was provided. Seems like this issue has been already fixed.
Feel free to create a new issue or reopen this one with more details.
