### ISSUE TITLE
Cancel or Goback option in sign-in-widget without passwordlessAuth options

### ISSUE THREAD

**Issue by patluri43** [okta/okta-signin-widget#1180]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info
Cancel/Signout/Back option if user entered incorrect username with username and password on the same screen.
Describe your issue or request here (if necessary).
Cancel/Signout/Back option if user entered incorrect username with username and password on the same screen.

### Expected behavior
If user enters incorrect username, after the IDP discovery, sign-in-widget falls back to local authentication. There is not Signout/cancel/back option to change the username and rerun the IDP discovery

What should have happened? 
If user enters incorrect username, after the IDP discovery, sign-in-widget falls back to local authentication. There is not Signout/cancel/back option to change the username and rerun the IDP discovery

### What went wrong?
User is locked and has to refresh their page to initiate the IDP discovery call again.

Please provide log or error messages if applicable.
<img width="402" alt="Screen Shot 2020-05-11 at 12 16 58 PM" src="https://user-images.githubusercontent.com/957780/81602412-6acb6400-9381-11ea-99fa-71834a60a50d.png">

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

### Your environment

  - Okta Sign-In Widget Version:
  - Browser:
  - OS:
  - Language:

**Comment by aarongranick-okta** [comment]
Created issue: OKTA-298383

**Comment by denysoblohin-okta** [comment]
Issue has been fixed with https://github.com/okta/okta-signin-widget/pull/2839 (version 6.8.1)
