### ISSUE TITLE
i18n language property file blocked by CORS

### ISSUE THREAD

**Issue by jayjayzheng** [okta/okta-signin-widget#1204]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

i18n for "zh-CN" property file is blocked by CORS on the latest version 4.1.1. 

CORS setting is enabled on the targeted host. prior updating to widget 4.1.1, the lang setting for "zh-CN" is working fine. after update, the language is not updated on the page but instead the following error is printed out in the console: 

Access to XMLHttpRequest at 'https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/4.1.1/labels/json/country_zh_CN.json' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Steps to reproduce

use okta signin widget js on React and set the widget config lang to "zh-CN". upon rendering the widget, the lang is showing as English and the CORS blocked error shown in the browser console.

### Your environment

  - Okta Sign-In Widget Version: 4.1.1
  - Browser: latest of chrome
  - OS: MacOS latest
  - Language:

**Comment by aarongranick-okta** [comment]
@jayjayzheng There is currently a delay from when we publish a signin widget version to when these assets are available in this CDN location. This may be the same issue as described here: https://github.com/okta/okta-signin-widget/issues/1038 

We are currently working on fixing this.

I see that the URL: https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/4.1.1/labels/json/country_zh_CN.json does load in my browser, so the asset has been deployed to the CDN. Can you test again to see if you are still experiencing an error? If the error is still occurring, can you see if this workaround will fix it? https://github.com/okta/okta-signin-widget/issues/1038#issuecomment-614935682
