### ISSUE TITLE
Support Github as a built-in IDP type

### ISSUE THREAD

**Issue by myspivey** [okta/okta-signin-widget#1300]
### I'm submitting a
  - [ ] bug report
  - [ X ] feature request

### Background info

It would be great to have GitHub as one of the supported provider types out of box. This would simplify styling and integration. I assume because Okta proper does not have this out of box yet this is the reason for it missing however it seems as though the styling could at least be there for when Okta does.

### Expected behavior

Should allow for type `GITHUB` to be supported in `idps` array

**Comment by aarongranick-okta** [comment]
@myspivey I believe this feature was brought into the widget by this commit: https://github.com/okta/okta-signin-widget/commit/8d9bbd5ff0e257e1391b3047750e02ee9b180c7c

The latest version of the widget should have full support for Github as an IDP
