### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lifenautjoe** [okta/okta-signin-widget#1330]
### I'm submitting a
  - [ ] bug report
  - [X] feature request

### Background info

As Typescript grows exponentially, its a great thing for a package such as Okta to support it

### Expected behavior

Types should be included in the package

### What went wrong?

Types do not exist

### Steps to reproduce

Install `okta-signin-widget`, try to import it in your Typescript app, get a failure build as types are not included.

### Your environment

  - Okta Sign-In Widget Version: All versions
  - Browser: N/A
  - OS: N/A
  - Language: Typescript

**Comment by aarongranick-okta** [comment]
@lifenautjoe I'm happy to say types were added in version 6.3.0. I recommend upgrading to the latest version to get the latest type definitions and all other fixes.
