### ISSUE TITLE
Password requirements translation in Spanish have extra periods

### ISSUE THREAD

**Issue by vdineva** [okta/okta-signin-widget#1366]
### I'm submitting a
  - [x] bug report

### Background info

Describe your issue or request here (if necessary).
When a user tries to reset their password and it does not meet the password requirements - the translation is Spanish has some extra periods:

`La contraseña no cumple los requisitos especificados. Requisitos de contraseña: al menos 8 caracteres, una letra minúscula, una letra mayúscula, un número, un símbolo, ninguna parte de su nombre de usuario, no incluye su nombre., no incluye su apellido.. No puede repetir ninguna de sus últimas 10 contraseñas.`

https://github.com/okta/okta-signin-widget/blob/b1b604d3760d7d5385304f1240e86f62f079789c/packages/%40okta/i18n/src/properties/login_es.properties#L553
https://github.com/okta/okta-signin-widget/blob/e366768ad28bdbb35f65c6d3048b13e6dc74e62e/packages/%40okta/i18n/src/properties/login_es.properties#L554 

### Expected behavior

The above text should be:

`La contraseña no cumple los requisitos especificados. Requisitos de contraseña: al menos 8 caracteres, una letra minúscula, una letra mayúscula, un número, un símbolo, ninguna parte de su nombre de usuario, no incluye su nombre, no incluye su apellido. No puede repetir ninguna de sus últimas 10 contraseñas.`

### Your environment

  - Okta Sign-In Widget Version: latest
  - Browser: any
  - OS: any
  - Language: Spanish

**Comment by swiftone** [comment]
@vdineva - Thanks for the detailed report!  We'll have a fix incoming with our next translation update.

Internal ref: OKTA-320795

**Comment by swiftone** [comment]
Closing this as the fix was released by the end of August.  @vdineva - if you are still seeing this issue, please reopen with details, and thanks again for the report.
