### ISSUE TITLE
Cookie sameSite attribute is overridden when supplied Secure: false & sameSite: none

### ISSUE THREAD

**Issue by umerkk** [okta/okta-signin-widget#1438]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

Okta-Signin-widget for Angular with custom TokenManager settings is not setting the cookie properly. I am defining 
`
    tokenManager: {
      storage: 'cookie',
      secure: false,
      sameSite: 'none',
      storageKey: 'myCookiename'
    },
`

although on a non-localhost domain, the cookie is set as "SameSite: lax".

### Expected behavior

Cookie should be set as "samesite: none"

### Steps to reproduce

Instantiate the okta-signin-widget for Angular with the following config and try to login from a non-localhost domain.
`
  oktaConfig: {
    clientId: ``,
    issuer: ``,
    redirectUri: '',
    pkce: true,
    scopes: ['openid', 'profile', 'email'],
    testing: {
      disableHttpsCheck: false
    },
    tokenManager: {
      storage: 'cookie',
      secure: false,
      sameSite: 'none',
      storageKey: 'myCookieName'
    },
    features: {
      registration: true,
      rememberMe: false,
      router: true
    }
  }
`

### Your environment

  - Okta Sign-In Widget Version:
    "@okta/okta-angular": "^2.0.0",
    "@okta/okta-auth-js": "^4.0.0",
    "@okta/okta-signin-widget": "^4.1.2",
  - Browser: Chrome
  - OS: MacOS Catalina
  - Language: Angular 8, JS

**Comment by aarongranick-okta** [comment]
@umerkk The `cookie` settings have their own config setting (outside the `tokenManager` setting). Try:

```
var config = {
  cookies: {
    secure: false
    sameSite: 'none'
  },
  tokenManager: {
    storage: 'cookie'
    storageKey: 'myCookiename'
  }
}
```

Not that this combination of settings will probably not work on latest versions of Chrome, which will block cookies with sameSite "none" and secure false. We recommend leaving the cookie settings at their default values. The SDK will automatically select values which will work on either HTTP or HTTPS.  You may set `cookies: { secure: false }` if you do not want secure cookies even on an HTTPS connection.
