### ISSUE TITLE
Release Notes for 5.0

### ISSUE THREAD

**Issue by amcdnl** [okta/okta-signin-widget#1482]
Looks like 5.0.0 went out and has some breaking changes but there is no release notes provided: https://github.com/okta/okta-signin-widget/releases/tag/okta-signin-widget-5.0.0

**Comment by shuowu** [comment]
@amcdnl Thanks for catching it! We'll add the release notes ASAP.

**Comment by amcdnl** [comment]
Side note: I noticed that I get popup oauth now despite it having page configured.

**Comment by shuowu** [comment]
This link may help:
https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md#display-option-no-longer-determines-redirect-behavior

**Comment by haishengwu-okta** [comment]
release notes have been published and link to this migration guide.
