### ISSUE TITLE
Login doesnot redirect

### ISSUE THREAD

**Issue by anwesh-b** [okta/okta-signin-widget#1484]
### I'm submitting a
  -  bug report

### Background info
I am using sign-in-widget v5.0.0 in Angular 10.1.2. <br>
When login completes, it doesnot redirect to OktaCallbackComponent. I have received the bearer token, which I can see in the network tab. I tried using the Bearer token and it works fine, but the UI is stuck in login page. It does not store the token and
doesnot redirect anywhere.
 I downgraded the version to 4 and it works fine.

### Expected behavior

It should redirect to the '/' route. 

### What went wrong?

It is stuck in login page, without any redirects. But I have received the login token and when I used the token to access my backend services, it works fine. The UI is stuck here.
![Screenshot (108)_LI](https://user-images.githubusercontent.com/45763486/97959778-2cff4380-1dd8-11eb-8fcd-81c085bfdc20.jpg)

### Steps to reproduce

Just login and the bug is reproduced everytime.

### Your environment

  - Okta Sign-In Widget Version: 5.0.0
  - Browser: Microsoft Edge Version 86.0.622.58 
  - OS: Windows 10
  - Language: Angular 10.1.2

**Comment by shuowu** [comment]
@anwesh-b From the [Migration guide](https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md#showsignintogettokens-no-longer-redirects), the `showSignInToGetTokens ` method is no longer redirect. The `OktaCallbackComponent ` is designed to process/get tokens from the redirect URL, now it's handled implicitly by the signIn widget and returns tokens in the success callback.
With signIn widget version 5.0, you can move the store tokens and in-app redirect logic to the success callback, and remove OktaCallbackComponent from the routes.

**Comment by kgorol** [comment]
I have exactly the same issue. Everything is working on localhost, but as soon as I build the production package and put it on my server it does not go past login screen with button disabled after click. My config:

**app.config:**
```
export default {
  oidc: {
    clientId: environment.oktaClientId,
    issuer: environment.oktaIssuer,
    redirectUri: environment.oktaRedirect,
    scopes: ['openid', 'profile', 'email'],
    pkce: true,
    testing: {
      disableHttpsCheck: false
    }
  }
};
```
**environment config:**
```
export const environment = {
  production: true,
  apiAddress: 'http://someaddresstoapi',
  oktaRedirect: 'http://mywebsite.com/implicit/callback',
  oktaIssuer: 'https://dev-XXXXXX.oktapreview.com/oauth2/default',
  oktaClientId: XXXXX',
  mapsApiKey: 'XXXXX'
};
```

**Login.component.ts:**
```
export class LoginComponent implements OnInit {

  public loginForm: FormGroup;
  signIn: any;

  constructor(public oktaAuth: OktaAuthService) {
    this.signIn = new OktaSignIn({
      baseUrl: appConfig.oidc.issuer.split('/oauth2')[0],
      clientId: appConfig.oidc.clientId,
      logo: '../../../assets/images/logo_login.png',
      authParams: {
        issuer: appConfig.oidc.issuer,
      },
      language: 'pl'
    });
  }

  ngOnInit() {
    this.signIn.showSignInToGetTokens({
      el: '#sign-in-widget',
      scopes: appConfig.oidc.scopes
    }).then(tokens => {
      // When navigating to a protected route, the route path will be saved as the `originalUri`
      // If no `originalUri` has been saved, then redirect back to the app root
      const originalUri = this.oktaAuth.getOriginalUri();
      if (originalUri === DEFAULT_ORIGINAL_URI) {
        this.oktaAuth.setOriginalUri('/');
      }

      // Remove the widget
      this.signIn.remove();

      // In this flow the redirect to Okta occurs in a hidden iframe
      this.oktaAuth.handleLoginRedirect(tokens);
    }).catch(err => {
      // Typically due to misconfiguration
      throw err;
    });
  }
}
```
**app.routing:**
```
const routes: Routes = [
  {
    path: '',
    component: ContentComponent,
    canActivateChild: [OktaAuthGuard],
    children: [
        someProtectedChildrenRoutes
    ]
  },
  {
    path: 'login',
    component: LoginComponent
  },
  {
    path: '**',
    redirectTo: ''
  }
];
```

As I said everything is working on my localhost, but on production environment it seems to not even get into `then` method of `showSignInToGetTokens`. When I try to remove `redirectUri` from `OktaSignIn` it gives me this error in console:
`
ERROR r {name: "CONFIG_ERROR", message: ""redirectUri" is required"}`

And these are my dependencies and their versions:

```
"dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^9.1.12",
    "@angular/common": "^9.1.12",
    "@angular/compiler": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.1.12",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@okta/okta-angular": "^3.0.1",
    "@okta/okta-signin-widget": "^5.1.1",
    "angular-calendar": "^0.28.22",
    "date-fns": "^2.16.1",
    "jwt-decode": "^2.2.0",
    "rxjs": "~6.5.5",
    "tslib": "^1.14.1",
    "zone.js": "~0.10.2"
  },
```

**Comment by EwoutB99** [comment]
I have the same issue. However sometimes it works sometimes it doesn't.

> @anwesh-b From the [Migration guide](https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md#showsignintogettokens-no-longer-redirects), the `showSignInToGetTokens ` method is no longer redirect. The `OktaCallbackComponent ` is designed to process/get tokens from the redirect URL, now it's handled implicitly by the signIn widget and returns tokens in the success callback.
> With signIn widget version 5.0, you can move the store tokens and in-app redirect logic to the success callback, and remove OktaCallbackComponent from the routes.

Hi, I'm having the same issue as mentioned here. Can you elaborate on this fix? It's not really clear where and what I should move (the store tokens and in app redirect logic).

**Comment by swiftone** [comment]
@kgorol - 

The advice about the redirect is not to remove the `redirectUri` (that is still required) but that the OktaCallbackComponent will only be used during a full redirect away-from-and-back-to your application, which will no longer occur if you are using `showSignInToGetTokens(...)`.

If your code isn't getting to the `.then()`, you are facing a different problem than this GH issue was covering.  A few questions:
- What does the browser DevTools reveal about the failing(?) call?
- Is the clientId you are using associated with a "SPA" type or "Web" type in okta's admin dashboard?

**Comment by jchabotamica** [comment]
I believe I had to move a couple things into the authParams object.
In authParams, I have `authParams: {
        pkce: true,
        responseType: 'code',
        issuer: {issuer here - make sure you get this right!}
      }`


My problem I'm having once I got this to work is that it doesn't end up bringing me to the protected route I originally attempted to bring to.  It seems to bring me to window.location.origin instead.  To do the redirect, I'm using `handleLoginRedirect(tokens)` - but again this seems to just always bring me to window.location.origin instead of the original protected route I tried to get to.

**Comment by kgorol** [comment]
Sorry for the late reply.
> 
>     * What does the browser DevTools reveal about the failing(?) call?
The sad part is DevTools reveal nothing. Console is clear and request under `authn` gives me a nice response:
```
{
  "expiresAt": "2021-03-22T06:58:13.000Z",
  "status": "SUCCESS",
  "sessionToken": "XX",
  "_embedded": {
    "user": {
      "id": "XX",
      "passwordChanged": "2019-07-20T16:14:25.000Z",
      "profile": {
        "login": "XX",
        "firstName": "XX",
        "lastName": "XX",
        "locale": "en",
        "timeZone": "America/Los_Angeles"
      }
    }
  },
  "_links": {
    "cancel": {
      "href": "https://dev-XXX.oktapreview.com/api/v1/authn/cancel",
      "hints": {
        "allow": [
          "POST"
        ]
      }
    }
  }
}
```
Everything is working on `localhost` environment, but when I build prod package and push it on my server, login seems not to be redirected...
> 
>     * Is the clientId you are using associated with a "SPA" type or "Web" type in okta's admin dashboard?

This is my Okta configuration in admin dashboard:
![image](https://user-images.githubusercontent.com/34159482/111952748-e0e24080-8ae5-11eb-9400-39eee4cc2b6b.png)

**Comment by aarongranick-okta** [comment]
It is currently recommended for SPA apps to call `showSignIn`
https://github.com/okta/okta-signin-widget#showsignin

This method returns a promise, that may return tokens without redirecting to your callback URI. However, depending on how your policy is configured, the widget may redirect to another IDP before returning to your application on the callback. When using `showSignIn`, your app should be prepared to receive tokens from the promise or on the callback.

If your app only wants to receive tokens on the callback, it is recommended to use `showSignInAndRedirect`

If you have any further troubles with SignIn Widget, please open a new issue.
