### ISSUE TITLE
Issue Completing Widget Flow With MFA (Okta Verify)

### ISSUE THREAD

**Issue by abeagley** [okta/okta-signin-widget#1487]
### I'm submitting a
  - [X] bug report
  - [] feature request

### Background info

Utilizing 4.x or 5.x I'm running into a couple issues getting past the MFA push challenge for my organization in order to process the tokens.

1) When submitting a push request, and accepting the "This was me" challenge - the widget does nothing even though the network tab shows the 'SUCCESS' status come through from the push (See what went wrong). It simply just pauses there and I don't get a success or error callback for my `showSignInToGetTokens` (5.x) or a redirect for 4.x.

2) If I choose to enter a code it flat out just errors out when I submit one. See the 'What went wrong?' section 5.x and 4.x

### Expected behavior

The promise from `showSignInToGetTokens` should have been resolved with the tokens or an error message. I should also be able to type in the code manually for MFA without getting an error.

### What went wrong?

Success Message from the `verify` endpoint:

```
{
  expiresAt: "XXX"
  sessionToken: "XXX"
  status: "SUCCESS"
  _embedded: {user: {id: "XXX",…}}
  _links: {cancel: {href: "XXX/api/v1/authn/cancel", hints: {allow: ["POST"]}}}
}
```

Error message when typing in the code manually:

```
okta-sign-in.entry.js?7589:51 Uncaught TypeError: n.verify is not a function
    at L.r.eval (okta-sign-in.entry.js?7589:51)
    at L.r.manageTransaction (okta-sign-in.entry.js?7589:47)
    at L.r.save (okta-sign-in.entry.js?7589:51)
    at L.r.eval (okta-sign-in.entry.js?7589:127)
    at L.r.manageTransaction (okta-sign-in.entry.js?7589:47)
    at L.r.click (okta-sign-in.entry.js?7589:127)
    at L.r.n.<computed> (okta-sign-in.entry.js?7589:14)
    at j (okta-sign-in.entry.js?7589:88)
    at HTMLAnchorElement.eval (okta-sign-in.entry.js?7589:88)
    at HTMLAnchorElement.eval (okta-sign-in.entry.js?7589:88)
```

### Steps to reproduce

I simply configured the SignInWidget as shown in the 5.x README:

```
this.widget = new OktaSignIn({
  clientId: 'XXX',
  baseUrl: 'https://XXX.okta.com',
  el: '#okta-sso-login',
  redirectUri: `${window.location.origin}/auth/okta/login`
})

this.widget.showSignInToGetTokens({
  scopes: ['openid', 'email', 'profile']
}).then(this.processTokens).catch(this.processError)
```

### Your environment

  - Okta Sign-In Widget Version: 5.0 and 4.5.2 attempted
  - Browser: Chrome
  - OS: Manjaro Linux

**Comment by shuowu** [comment]
@abeagley Thanks for reporting the issue! Can you please try `4.4.4` or `3.9.2` to see if the issue still exists? Those are two stable versions.

**Comment by abeagley** [comment]
@shuowu just tried `4.4.4` same issue as `4.5.2`. 'SUCCESS' response from `verify` endpoint but no redirect. I also can't enter in the code manually and still get the `n.verify is not a function error`.

I'll try `3.9.2`, but I will admit having to go back versions this far to get anything working is a bit disheartening for our organization.

**Comment by shuowu** [comment]
@abeagley Thanks for trying v4.4.4. Looks like it may come from backend response issue.

Internal Ref: OKTA-344154

**Comment by denysoblohin-okta** [comment]
@abeagley 
Are you sure success callback (`this.processTokens`) is defined?

In case of undefined callback widget will not close automatically and you will get error `Uncaught TypeError: n.verify is not a function` on click on `Verify` button with correct entered code.

If it's not the case, can you please specify the minimum version of `okta-signin-widget` which works for you? Or provide a more complete sample code to reproduce.

**Comment by abeagley** [comment]
@denysoblohin-okta 

Yes it's for sure defined, the widget never gets the point of calling it though. In any version since it can't get past the MFA verify call.

**Comment by denysoblohin-okta** [comment]
@abeagley 
Can you provide some details of response from the `api/v1/authn` endpoint? 
(Interested in `factorType` and `provider` in `_embedded.factors`)
Example: 
```
{
  status: "MFA_REQUIRED",
  _embedded: {
    factors: [
      { factorType: "push", provider: "OKTA", .. },
      { factorType: "token:software:totp", provider: "OKTA", .. },
    ]
  }
}
```

**Comment by denysoblohin-okta** [comment]
@abeagley 
If you choose to enter a code (without trying the push method first), you still get error `n.verify is not a function`?

Also, do you see this error in console?
```
error.errorCode: login_required, error.description: The client specified not to prompt, but the client app requires re-authentication or MFA.
```

**Comment by denysoblohin-okta** [comment]
We are going to close this issue because we haven't heard back, but please re-open this issue if you want to continue working on it with us
