### ISSUE TITLE
Localization does not work

### ISSUE THREAD

**Issue by RJBernardo** [okta/okta-signin-widget#1492]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

React app using octa-signin-widget.

### Expected behavior

If one of supported languages (described here: https://github.com/okta/okta-signin-widget#language-and-text) is used, widget should load localized texts.
I'm using 'pt-BR'

### What went wrong?

Failed to load resource: the server responded with a status of 404 (https://global.oktacdn.com/okta-signin-widget/4.3.2-g4bb3b7e/labels/json/login_pt_BR.json)
https://global.oktacdn.com/okta-signin-widget/4.3.2-g4bb3b7e/labels/json/country_pt_BR.json

### Steps to reproduce

set language property to 'pt-BR'

### Your environment

Okta Sign-In Widget Version: 4.3.2
Browser: Opera GX core: 71.0.3770.310
OS: Windows 10 Enterprise
Language: OS language - pt-BR

**Comment by shuowu** [comment]
@RJBernardo Thanks for reporting the issue! 
Looks like the translation link is broken in v4.3.2. Can you try v4.4.4 or the newly released major version 5.0 (both verified)?

**Comment by RJBernardo** [comment]
> @RJBernardo Thanks for reporting the issue!
> Looks like the translation link is broken in v4.3.2. Can you try v4.4.4 or the newly released major version 5.0 (both verified)?

works for me! thanks
