### ISSUE TITLE
Include source code with source maps

### ISSUE THREAD

**Issue by andyrichardson** [okta/okta-signin-widget#1520]
## About

Hey there! It would be super helpful for debugging purposes if you could include source code when publishing libraries 🙏 

Right now, the source maps aren't doing a whole lot because they point to source files that don't exist.

**Comment by robertjd** [comment]
Hi @andyrichardson , thanks for the question.  I was just looking at our NPM packages, and I do see the .map files in `dist/js`.  Maybe there is something more we need to do to make it place nicely with the debugger?  I'll ask the team to look further (internal ticket OKTA-347899).

**Comment by andyrichardson** [comment]
@robertjd this would be the required change - https://github.com/okta/okta-signin-widget/pull/1536

**Comment by andyrichardson** [comment]
Closing as it could be an issue on my end
