### ISSUE TITLE
Tooltip issue in Webkit

### ISSUE THREAD

**Issue by philsbury** [okta/okta-signin-widget#156]
Hi,

In Webkit browsers (tested in Safari and Chrome), if I scroll down the page and hover on a tooltip they are misplaced, looks like an incorrect offset. Works as expected in Firefox, however.

**Comment by rchild-okta** [comment]
Thanks for letting us know - I'm able to reproduce and we'll try to get a fix in for this by the next release.

**Comment by philsbury** [comment]
@rchild-okta great, thank you

**Comment by philsbury** [comment]
Hi @rchild-okta this issue still persisted in version 1.10.0. The issue is with vertical scrolling, not horizontal as in [#158](https://github.com/okta/okta-signin-widget/issues/158)
