### ISSUE TITLE
Social Auth redirect not working with Angular Okta Sign-in Widget

### ISSUE THREAD

**Issue by DerekJDev** [okta/okta-signin-widget#1568]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info
I'm trying to login to my angular app using configured idps, but after successfully authenticating it goes to the Okta dashboard, not my angular application. I have tried following this KB doc: https://support.okta.com/help/s/article/Social-Auth-redirect-not-working-with-okta-signin-widget?language=en_US

But when it redirects back to my application it's not passing the information needed to authenticate so it just goes back to the login page in my app.

### Expected behavior

It should redirect to the idp then redirect back to my app with the information needed to authenticate

### What went wrong?

It redirected back to my app without information needed to authenticate

### Steps to reproduce
widget: OktaSignIn = new OktaSignIn({
    baseUrl: environment.issuerBase,
    redirectUri: environment.redirectUri,
    customButtons: [
      {
        title: 'Sign in with Facebook',
        className: 'social-auth-button social-auth-facebook-button link-button',
        click: function () {
          window.location.href = `${environment.issuerBase}sso/idps/0oa23p941y00000zF5d6?fromURI=${encodeURI(environment.redirectUri)}`;
        }
      },
      {
        title: 'Sign in with Google',
        className: 'social-auth-button social-auth-google-button link-button',
        click: function () {
          window.location.href = `${environment.issuerBase}sso/idps/0oa23pbisTuZ000005d6?fromURI=${encodeURI(environment.redirectUri)}`;
        }
      }],
    authParams: {
      pkce: true
    },
    registration: {
      postSubmit: function (response, onSuccess, onFailure) {
        // handle postsubmit callback
        onSuccess(response);
        console.log(response, onSuccess, onFailure);
      }
    },
    language: navigator.language.substring(0, 2),
    features: {
      registration: true,
      autoPush: true,
      multiOptionalFactorEnroll: true,
      showPasswordToggleOnSignInPage: true
    }
  });

 this.widget.renderEl({
        el: '#okta-signin-container'
      },
        (res) => {
          if (res.status === 'SUCCESS') {
            this.oktaAuth.signInWithRedirect({ redirectUri: 'http://localhost:4200/login/callback', sessionToken: res.session.token });
          }
        },
        (err) => {
          throw err;
        }
      );

### Your environment

  - Okta Sign-In Widget Version: 5.1.1
  - Browser: Edge
  - OS: Windows
  - Language: English

**Comment by denysoblohin-okta** [comment]
Thanks for reporting this issue.
Internal ref: OKTA-352694

**Comment by denysoblohin-okta** [comment]
@DerekJDev Your example and KB guide use non-OIDC flow. Have you tried OIDC flow? It should work fine with social auth.
```
var signIn = new OktaSignIn(
  {
    baseUrl: 'https://{yourOktaDomain}',
    clientId: '{{clientId of your OIDC app}}'
    redirectUri: '{{redirectUri configured in OIDC app}}',
    idps: [
      { type: 'Facebook', id: 'xxxx' }
    ],
  }
);

signIn.showSignInAndRedirect({
  el: el: '#okta-signin-container'
}).then(function(tokens) {
  // Store tokens
});
```

There is working [sample](https://github.com/okta/okta-auth-js/blob/master/samples/generated/webpack-spa)
Just add your idps [here](https://github.com/okta/okta-auth-js/blob/master/samples/generated/webpack-spa/src/index.js#L205)
```
      idps: [
        { type: 'Facebook', id: 'xxxx' }
      ],
```

Set  `Authentication Flow = Okta Signin Widget`, your `Issuer` and `Client ID`

**Comment by DerekJDev** [comment]
It looks like that worked. What I ended up needing to change was adding the clientId into my config and then instead of using the renderEl() function, I used the showSignInAndRedirect() function. I would include this in the documentation for setting up the sign-in widget using different IDPs because I didn't catch that I needed to use the other function. Thanks for the feedback.
