### ISSUE TITLE
Mismatched styling in Self-Hosted widget vs Okta-Hosted - password reset form

### ISSUE THREAD

**Issue by Tennyx** [okta/okta-signin-widget#1605]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

In the self-hosted widget, in the password reset form, the styling/HTML does not match that of the Okta-hosted widget.

### Expected behavior

The form should display as an unordered list like so:

```
<div data-se="password-requirements-html">
  <div class="password-requirements--header">Password requirements:</div>
    <ul class="password-requirements--list">
      <li class="password-requirements--list-item">At least 8 characters</li>
      <li class="password-requirements--list-item">A lowercase letter</li>
      <li class="password-requirements--list-item">An uppercase letter</li>
      <li class="password-requirements--list-item">A number</li>
      <li class="password-requirements--list-item">No parts of your username</li>
      <li class="password-requirements--list-item">Your password cannot be any of your last 4 passwords</li>
    </ul>
</div>
```

### What went wrong?

Instead, it displays the rules inside a single `<p>` tag:

```
<p class="okta-form-subtitle o-form-explain" data-se="o-form-explain">Password requirements: at least 8 characters, a lowercase letter, an uppercase letter, a number, no parts of your username. Your password cannot be any of your last 4 passwords.</p>
```

### Steps to reproduce

If you make an api call to **/api/v1/authn/recovery/password**, with the body as follows:

```
{
  "username": <Okta email>
  "factorType": "EMAIL",
  "relayState": "/myapp/some/deep/link/i/want/to/return/to"
}
```

You will trigger a forgot password email. Find the Reset Password link in that email and grab the reset token that comes after **/signin/reset-password/**. In your self-hosted widget config, add parameter `recoveryToken: <reset token>`. Compare this to a password reset flow done via the Okta-hosted widget to see the difference.

### Your environment

  - Okta Sign-In Widget Version: 5
  - Browser: Firefox 84.0.2
  - OS: Mac 10.15.7
  - Language: English

**Comment by oleksandrpravosudko-okta** [comment]
@Tennyx thanks for submission.
It looks like password rules layout is controlled by [`showPasswordRequirementsAsHtmlList`](https://github.com/okta/okta-signin-widget/blob/3069f9fb63be71687011d33ab7e2f0e66edec7bd/src/models/Settings.js#L83) option - would you mind checking if it works for you?

**Comment by Tennyx** [comment]
@oleksandrpravosudko-okta Oh wow - ya that worked. Thanks so much and I apologize for wasting your time!
