### ISSUE TITLE
Link to gallery examples is broken

### ISSUE THREAD

**Issue by sriks316** [okta/okta-signin-widget#1621]
https://github.com/okta/okta-signin-widget#okta-hosted-signin-page-customizable

The gallery link is giving me a 404

![image](https://user-images.githubusercontent.com/3370288/105867615-47a21c80-5fc3-11eb-90e5-478d53585ee8.png)

**Comment by shuowu** [comment]
@sriks316 Thanks for the report! 

Internal Ref: OKTA-364541

**Comment by jmelberg-okta** [comment]
Thanks again @sriks316 for opening this issue!

After checking with our documentation team, the gallery page has been deprecated and removed. We've updated this project's README (#1761) to remove this stale link.
