### ISSUE TITLE
IE11 MFA verify button problem

### ISSUE THREAD

**Issue by erhangundogan** [okta/okta-signin-widget#1668]
### I'm submitting a
**Bug report** for MFA verification process with Okta Sign-in widget (v4.5.2) on IE11 (v11.0.9600.18860)

### Background info

Our customers are having problem with MFA verification. First we have added TextEncoder support with polyfill library (https://cdn.jsdelivr.net/npm/text-encoding@0.7.0/lib/encoding.min.js). That resolved some issues on Edge and some of the IE11 versions. But we are still having problem on IE11. TextEncoder and SubtleCrypto are defined but still cannot proceed MFA verification. Error in the console is: **"Object doesn't support property or method 'activate'"**.

### Expected behavior

Pass MFA without any problem

### What went wrong?

Having console errors as shown below.

![Screenshot 2021-02-16 at 17 16 38](https://user-images.githubusercontent.com/818450/108096442-44a9c180-7081-11eb-9ceb-3a6032bb39a1.png)

### Your environment

  - Okta Sign-In Widget Version: v4.5.2
  - Browser: IE11 v11.0.9600.18860, v11.329.19041
  - OS: Windows 7 Enterprise (VM), Windows 10 PRO
  - Language: EN-US

**Comment by aarongranick-okta** [comment]
@erhangundogan We provide a polyfill for IE11 that may help in this case: https://github.com/okta/okta-auth-js#browser-compatibility--polyfill

It is recommended to include the polyfill in a script tag before any other scripts load.

**Comment by haishengwu-okta** [comment]
@aarongranick-okta don't we bundle the polyfill by default into widget?

**Comment by aarongranick-okta** [comment]
@haishengwu-okta We do for CDN version, but it is not included if you are using the NPM version. However in this case I think something else is going on..

@erhangundogan Are you still seeing this issue? Does it only affect IE 11?

**Comment by erhangundogan** [comment]
@aarongranick-okta adding polyfill library resolved the problem. We can close the issue. Thank you.
