### ISSUE TITLE
Destroy or update settings

### ISSUE THREAD

**Issue by SergeyShablenko** [okta/okta-signin-widget#169]
How to destroy widget or update its settings?

**Comment by joelfranusic-okta** [comment]
Can you provide more context on what you're trying to do?

**Comment by SergeyShablenko** [comment]
I want to make widget with tabs, where each tab has different widget for signing-in through different services, but when i try to hide or destroy or create new instance of your widget it throws an error `Backbone.history has already been started`

**Comment by rchild-okta** [comment]
Same issue as https://github.com/okta/okta-signin-widget/issues/168, will track it there.
