### ISSUE TITLE
Widget should allow passing in an instance of OktaAuth

### ISSUE THREAD

**Issue by distinctdan** [okta/okta-signin-widget#1713]
### I'm submitting a
  - [] bug report
  - [X] feature request

### Background info

I'm using the sign in widget with React.

### Expected behavior

The widget currently requires all OktaAuth configuration params to be passed in. However, for react, this results in having to duplicate all of your parameters, because the react setup involves creating a global OktaAuth instance to use for routing in addition to the widget. Also, this isn't documented in the react docs. From the way the docs read, it would be reasonable to assume that the signin widget is pulling the oktaAuth instance from react's context, so it would use all of the configuration properties. For example, in the react docs, an issuer property is set on the global OktaAuth instance, but it's not passed to the widget, which results in the widget not working. I've filed a separate issue in okta-react [here](https://github.com/okta/okta-react/issues/93)).

So, to fix this for react, the widget would need to support being passed an instance of OktaAuth, instead of creating its own. This would allow it to correctly integrate, so that it's using the global instance instead of its own separate one.

### Your environment

  - Okta Sign-In Widget Version: 5.4.0
  - Browser: Chrome
  - OS: macOS
  - Language: Typescript

**Comment by swiftone** [comment]
Recently completed!  See the new `authClient` option as of 5.3.x ( https://github.com/okta/okta-signin-widget/pull/1617 )

https://github.com/okta/okta-signin-widget#authclient

**Comment by distinctdan** [comment]
Great! That's exactly what I'm looking for, thanks.
