### ISSUE TITLE
Deprecation warning when logging in with sign in widget

### ISSUE THREAD

**Issue by christopherhuii** [okta/okta-signin-widget#1722]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info
I recently upgraded `@okta/okta-signin-widget` to `v5.4.0` and am using it alongside `@okta/okta-react v4.1.0`. After entering my username and password, but BEFORE entering MFA, I get a console warning:

```
[okta-auth-sdk] DEPRECATION: This method has been deprecated, please use signInWithCredentials() instead.
```

I did some research and found this deprecation notice [here](https://github.com/okta/okta-auth-js#signinoptions), but I don't see this method anywhere in my code. Since `okta-signin-widget` is handling that process, it leads me to believe it's coming from there? Please correct me if I'm wrong. In any case, here's the snippet of code I'm using for my sign in widget:

```
const OktaSignInWidget = ({ onSuccess, onError }) => {
  const widgetRef = useRef(null);

  useEffect(() => {
    let signIn: any;
    if (widgetRef.current) {
      signIn = new OktaSignIn({
        el: widgetRef.current,
        baseUrl: process.env.REACT_APP_OKTA_DOMAIN,
        clientId: process.env.REACT_APP_OKTA_CLIENT_ID,
        authParams: {
          pkce: true,
          issuer: process.env.REACT_APP_OKTA_ISSUER,
          responseMode: 'query'
        }
      });

      signIn
        .showSignInToGetTokens({
          authorizationServerId: process.env.REACT_APP_OKTA_SERVER_ID,
          clientId: process.env.REACT_APP_OKTA_CLIENT_ID,
          redirectUri: process.env.REACT_APP_OKTA_REDIRECT_URI,
          scopes: ['openid', 'profile', 'email']
        })
        .then(onSuccess)
        .catch(onError);
    }

    return () => signIn.remove();

  }, []);

  return <div ref={widgetRef} />;
};
```

### Expected behavior
I don't expect to see any errors/warnings in the developer console.

After upgrading `okta-signin-widget`, my application functionally works exactly how I expect it to. I just want to make sure I am not to using any deprecated methods that will break in future updates.

Please let me know if there's anymore information I can provide. Thanks!

### Your environment

  - Okta Sign-In Widget Version: 5.4.0
  - Okta React Version: 4.1.0
  - Okta Auth JS Version: 4.5.1
  - Browser: Chrome
  - OS: MacOS
  - Language: Javascript/React

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue!
Looks like source of this this deprecation warning is this:
https://github.com/okta/okta-signin-widget/blob/okta-signin-widget-5.4/src/models/PrimaryAuth.js#L119
In `okta-auth-js` `signIn` is a deprecated alias to `signInWithCredentials` and will be removed in `5.0`

**Comment by christopherhuii** [comment]
Thanks for the quick response!

**Comment by denysoblohin-okta** [comment]
@christopherhuii SIW 5.4.3 does not produce such deprecations.
Closing this issue. 
If you still have deprecation warnings, feel free to reopen the issue or open a new one
