### ISSUE TITLE
Unable to update the username in Widget conf

### ISSUE THREAD

**Issue by sovushka-utrom** [okta/okta-signin-widget#1727]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

If a username is set up the in the initial conf, it is displayed correctly in the login field:
```
  loginWidget = new OktaSignIn({
   ...
    username: 'myFirstEmail@somedomain.com'
  });
```

But if it is replaced programmatically with another one, the first one is still displayed :
```      
   this.loginWidget.username = 'mySecondEmail@somedomain.com';
   console.log('this.loginWidget.username', this.loginWidget.username); // => logs correctly 'mySecondEmail@somedomain.com'
   this.loginWidget.renderEl({
        el: '#okta-signin-container'}, // => login field still displays 'myFirstEmail@somedomain.com'
        (result) => {}
      );
```
NB: Widget is rendered only once.

### Expected behavior

The username should be replaced.

### What went wrong?

Looks like the replacement is just ignored. 

### Steps to reproduce

1. Create initial conf with some email in username.
2. On button click, call a function that sets another email & renders the widget.
3. Check what is displayed

### Your environment

    "@okta/okta-angular": "^2.0.0",
    "@okta/okta-auth-js": "^3.0.0",
    "@okta/okta-signin-widget": "3.8.1",
  - Browser: Firefox, Chrome
  - OS: Windows
 - Language: N/A

**Comment by shuowu** [comment]
@sovushka-utrom Based on current implementation, the passed-in config is initialized and protected by closure as private variables when the widget instance is created.

In your code, `this.loginWidget.username = 'mySecondEmail@somedomain.com'` only add a new property to the widget instance, but the internal code cannot read it as the configuration.

The workaround can be only initial the widget instance when all configurations are ready, then call the `renderX` method afterward.

**Comment by sovushka-utrom** [comment]
@shuowu , thank you for this workaround. 
It's all fine now when the widget is instantiated with the final config right before rendering :
```
this.loginWidgetConfig.username = 'mySecondEmail@somedomain.com';
this.loginWidget = new OktaSignIn(this.loginWidgetConfig);
this.loginWidget.renderEl({
        el: '#okta-signin-container'}, // => login field still displays 'myFirstEmail@somedomain.com'
        (result) => {}
);
```
