### ISSUE TITLE
showSignInToGetTokens Promise without any Response

### ISSUE THREAD

**Issue by lawchihon** [okta/okta-signin-widget#1765]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

I'm trying to use the widget under NextJs or ReactJs. But it didn't return any callback or reject from the promise

### Expected behavior

Receiving onSuccess or onError after clicking sign in button

### What went wrong?

There is no log at all, the loading icon just keep spinning

### Steps to reproduce

Build the app following https://developer.okta.com/code/react/okta_react_sign-in_widget/
Or https://github.com/lawchihon/nextjs-okta-signin-widget
Tried with `showSignInToGetTokens`, `showSignInAndRedirect`, and `renderEl`, but neither of them work

### Your environment

  - Okta Sign-In Widget Version: 5.4.3
  - Browser: Chrome
  - OS: Mac
  - Language:

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the report @lawchihon.

Could you please check if there are errors popping in [`afterError`](https://github.com/okta/okta-signin-widget#aftererror) event handler?

**Comment by lawchihon** [comment]
Thank you for replying @oleksandrpravosudko-okta.
It is popping `{controller: "primary-auth"}` in afterError event handler.

**Comment by oleksandrpravosudko-okta** [comment]
I would expect the error object to contain `error.name, error.message, error.statusCode` properties - are they available in your case?

There seem to be no errors with the linked [NextJS](https://github.com/lawchihon/nextjs-okta-signin-widget) example - I can see tokens being retrieved (`onSuccess` is called).

**Comment by lawchihon** [comment]
@olegandreyev-okta Thanks!
So it is all becoz Im serving it under http as NextJS default and forgot we have pkce default to true.
But I wonder why it didn't reject the promise.

**Comment by MikeMondragon-okta** [comment]
#2296 is also seeing this ... started a Jira to track.

Okta Internal Reference: [OKTA-445189](https://oktainc.atlassian.net/browse/OKTA-445189)

**Comment by monde** [comment]
#2296 is also seeing this ... started a Jira to track.

Okta Internal Reference: [OKTA-445189](https://oktainc.atlassian.net/browse/OKTA-445189)

**Comment by JacobTLeBlanc** [comment]
I am also having this exact issue, any updates on this by any chance?

**Comment by aarongranick-okta** [comment]
@lawchihon @JacobTLeBlanc I believe this issue has been fixed and is no longer a problem when using the latest version of okta-signin-widget. If you are still experiencing this issue, please open a new Github issue.
