### ISSUE TITLE
Fire error callback regardless of error type

### ISSUE THREAD

**Issue by asharma93** [okta/okta-signin-widget#181]
The docs state "The widget will handle most types of errors - for example, if the user enters an invalid password or there are issues authenticating.". This is great, however, but for cases where we would like to track errors during failed authentication flows for example, we are unable act on such events since the widget handles them and the failure callback isn't triggered.

To give the developer more control, I believe any error regardless of type should be reported to the consumer by expanding the widget to propagate these errors to the failure callback without affecting how the widget currently handles them. 

I would be more than happy to submit a PR for this change but would like to gain some feedback on the matter first.

**Comment by rchild-okta** [comment]
Hi @asharma93, thanks for the feedback!

Definitely agree - we need to expose more of our events to the developer. Main question from me is where to put it:

- Failure callback - this currently acts as a full stop, i.e. we've hit a state the widget cannot recover from, and it's up to the developer to expose some type of error message.
- Events, i.e. when you subscribe to [on](https://github.com/okta/okta-signin-widget#onevent-callback-context). This feels more appropriate to me - expose everything here as an async event. 

I prefer the second, using events. Second question is how you need to use it - for example, is it fine to treat these errors as an async event (you can log and respond without changing the existing flow), or do you need a hook which needs to happen synchronously before the widget shows the error message?

**Comment by asharma93** [comment]
I agree, the latter provides more flexibility and is less restrictive for the developer as they can write the logic to handle the events they are interested in. 

For me, I simply need to log and respond to these events without changing the existing flow - for example, catching failed login attempts as they happen and publishing a custom event through my application.

If we use '.on', we could create an event for this and do something like:

```
/* 
 * Subscribe to all authentication failures
 * @param {object} data - contains type and error message
 */
signIn.on('auth_fail', function (data) {

 if (data.type === "INVALID_CREDENTIALS") {
    // do something
    myAuthHandler(data.error);
    return;
 }

 if (data.type === "TOO_MANY_ATTEMPTS") {
    // do something
    return;
  }

 if (data.type === "NETWORK_ERROR") {
    // do something
    return;
  }
});
```

If we do decide to go down this path, I would suggest keeping the existing error handler for when the widget enters an unrecoverable state (what it's currently doing) rather than channeling this through the events.

**Comment by rchild-okta** [comment]
Sounds good to me - let's go with triggering it through the events, and keeping unrecoverable errors the way it is currently with the failure callback.

[This](https://github.com/okta/okta-signin-widget/blob/master/src/util/BaseLoginController.js#L51-L53) might be a good place to start looking - it catches all model errors on all the forms. All events on controllers are triggered up through the [BaseLoginRouter](https://github.com/okta/okta-signin-widget/blob/master/src/util/BaseLoginRouter.js#L203), which is then [bubbled up](https://github.com/okta/okta-signin-widget/blob/master/src/widget/OktaSignIn.js#L157) through the main OktaSignIn instance.

I did notice that you had put "auth_fail" as the error name - we have many different states outside of primary authentication (i.e. when you enroll in various MFA options, challenge, go through the recovery flow, etc). I do think it'd be nice to expose which page the error came from if we hook it up at this low level. You can get access to which controller it is by accessing the controller.className, i.e. what we do for the 'pageRendered' event [here](https://github.com/okta/okta-signin-widget/blob/master/src/util/BaseLoginController.js#L101).

**Comment by asharma93** [comment]
Thanks @rchild-okta! I've plenty to get started.

**Comment by jmelberg-okta** [comment]
I've created a new issue (#549) to track all ongoing work related to providing the ability capture these type of events, so I'm going to close this issue for now.

Please leave a 👍 on that issue.
