### ISSUE TITLE
authParams.nonce not setting `nonce` returned in `id_token`

### ISSUE THREAD

**Issue by kblizeck** [okta/okta-signin-widget#1867]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

I am using the `okta-signin-widget` with Javascript, using the `authorization_code` flow so I get a `code` returned to the browser, which I swap for `id_token` from the `/token` endpoint. 

### Expected behavior

I am setting the `nonce` value to a random string in the Javascript call -
```
import OktaSignIn from '@okta/okta-signin-widget';

const oktaSignIn = new OktaSignIn({
	baseUrl: 'https://customokta.okta.com',
	el: '#okta-login-container',
	clientId: clientId,
	// must be in the list of redirect URIs enabled for the OIDC app
	redirectUri: `https://${window.location.host}/login`,
	authParams: {
		issuer: 'https://customokta.okta.com/oauth2/default',
		pkce: false,
		responseType: ['code'],
		nonce: 'addrandomvaluehere',
	},
});

oktaSignIn.showSignInAndRedirect();
```

### What went wrong?

The `nonce` value being returned within the `id_token`, from the `/token` endpoint `code` swap does not match the `nonce` value I'm sending in via the `authParams`.

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

### Your environment

  - Okta Sign-In Widget Version: 5.5.3
  - Browser: Chrome
  - OS: 
  - Language:

**Comment by bretterer** [comment]
@kblizeck thank you for your bug report. One of our SIW Experts will look into this and help you out.

**Comment by kblizeck** [comment]
Hi @bretterer - any idea on a timeline for assistance with this? Thanks!

**Comment by kblizeck** [comment]
@bretterer Just tried this again... and it's working as expected. Unsure if it was user error (most likely) or `magic`... Closing as it's a non-issue!
