### ISSUE TITLE
showSignInToGetTokens and handleLoginRedirect when system time 1 hour ahead

### ISSUE THREAD

**Issue by jchabotamica** [okta/okta-signin-widget#1899]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

When using showSignInToGetTokens then handleLoginRedirect, we were doing some testing around error handling for incorrect user system times.
Typically the okta libraries would throw an error which we could interrogate to display appropriate messaging to the user.
However, if the system time is exactly one hour ahead, it is treated as a "success" but it then goes into an infinite loop of trying to refresh the token it seems:
![image](https://user-images.githubusercontent.com/52013619/117013609-05713100-acbe-11eb-820b-d74515718734.png)

When looking at the "expiresAt" on the idToken, it seemed that it was set to expire immediately.

One thing to note is we have our maxClockSkew set to 900.

### Expected behavior

Either treat it as a true success and let the customer login or throw the same OAUTH_ERROR indicating that the jwt token was generated in the future.

**Comment by aarongranick-okta** [comment]
@jchabotamica Thank you for the issue report. To help us better reproduce the error it will help us to know:
- what version of the widget are you using?
- how are you calling `handleLoginRedirect`? (are you using the `authClient` on the widget, or are you instantiating your own copy of `okta-auth-js`? If so, what version?
- was it an infinite loop, or did it try exactly 10 times? (we have some built-in flood prevention which should stop the loop after 10 cycles).

**Comment by jchabotamica** [comment]
This no longer seems to be occurring
