### ISSUE TITLE
Sign-in widget not compatible with Nuxt.js

### ISSUE THREAD

**Issue by chrisnetonline** [okta/okta-signin-widget#1946]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

We are wanting to utilize the Okta sign-in widget in our Nuxt.js single page app.

```
<template>
  <section>Testing</section>
</template>

<script>
import OktaSignIn from "@okta/okta-signin-widget";

export default {
  mounted() {
    console.log(OktaSignIn);
  },
};
</script>
```

### Expected behavior

No Javascript errors should be received.

### What went wrong?

![image](https://user-images.githubusercontent.com/265868/118023018-07c13400-b32b-11eb-9a3d-81871be984af.png)

### Steps to reproduce

I am using a base install of Nuxt.js and simply importing the _@okta/okta-signin-widget_ package:
https://codesandbox.io/s/dreamy-sun-xlhoj

### Your environment

  - Okta Sign-In Widget Version: 5.6.2
  - Browser: Chrome
  - OS: MacOS
  - Language: EN

**Comment by bryanapellanes-okta** [comment]
@chrisnetonline,
Thanks for reaching out!  I'll bring this to the attention of our Javascript developers and someone will comment here with more.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-395193

**Comment by shuowu** [comment]
@chrisnetonline okta-signin-widget is a client-side widget, currently, it cannot support server-side framework very well. A workaround for your use case is to use widget via okta CDN. See the details [here](https://github.com/okta/okta-signin-widget#using-the-okta-cdn).
