### ISSUE TITLE
Hide, show, remove for backbone apps

### ISSUE THREAD

**Issue by rchild-okta** [okta/okta-signin-widget#202]
We will add show, hide, remove with this PR: https://github.com/okta/okta-signin-widget/pull/201.

However, this doesn't work in the case of a Backbone SPA - we are depending on the global Backbone.history.start/stop methods. The widget should recognize when it's in a backbone app, and not start/stop if Backbone history is already in use.

Original comment from kimu: https://github.com/okta/okta-signin-widget/issues/168#issuecomment-288426267

**Comment by jmelberg-okta** [comment]
We've been able to validate `show`, `hide`, and `remove` work for the main three frontend frameworks: **Angular**, **React**, and **Vue**.

This should be fixed with Backbone apps as well. If not - please reopen this issue.
