### ISSUE TITLE
Unidentified text displayed on error that is not listed in login.properties file

### ISSUE THREAD

**Issue by casp4** [okta/okta-signin-widget#2030]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Am trying to override the error message for one particular error message but since our Okta instances are not self-hosted, I have to reproduce errors manually to see the error pages.

In this case, I want to change the error text for invalid URL but when I look at the expected text output I should see BEFORE customising, I am seeing text that does not appear at all in the list of possible error codes (https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/src/properties/login.properties).

Can we either get that list updated with the most up-to-date error messages or have this particular error added? 

> Sidenote: This is a slight matter of urgency as the real error I need to customise is the `Bad request` error which is notoriously difficult to emulate, especially since we see it when login has timed out and our client wants the error message to just be a little more friendly. In the mean time I can update the error page customisation on the Okta Admin console to replace `Bad request` with `Something went wrong while authenticating. Please try again.`

### Expected behavior

Expected to see one of the error messages (`errors.E0000008`) as listed in https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/src/properties/login.properties so that I can pinpoint which exact `errorLink` is being produced.

### What went wrong?

Should see `The requested path was not found` but am seeing `We couldn't find the page you were looking for.` when using `{{{errorDescription}}}` in error page customisation html for Okta hosted environment.

### Steps to reproduce

1. Open preview page for login/error page customised via Okta Admin console
2.  Add `w` at the end of the url to make it invalid e.g. `/previeww`
3. See error message `We couldn't find the page you were looking for.` come back for `{{{errorDescription}}}` instead of anything listed in https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/src/properties/login.properties 

### Your environment

  - Okta Sign-In Widget Version: not self-hosted
  - Browser: Chrome 90
  - OS: Microsoft
  - Language:

**Comment by bryanapellanes-okta** [comment]
@casp4,
Thanks for reaching out! I'll bring this to the attention of our Javascript developers and someone will respond here.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-402540

**Comment by jmelberg-okta** [comment]
Hi @casp4  - thanks for opening this issue.

Messages matching `errors.*` in the `login.properties` file are primarily mapped to Okta's API errors. The text "`We couldn't find the page you were looking for.`" is a static message that appears to come from the generic `400` error page, so it is outside of the messaging control of the Widget. You should be able to customize this text by creating a [custom error page](https://help.okta.com/en/prod/Content/Topics/Settings/custom-error-pages.htm).

In regards to your sidenote - the "Bad request" error is unfortunately bucketed into several i18n keys. Can you confirm an error code matching `E0000020` is returned when the the login has timed out? I'd actually expect the error code to be either `E0000005` or `E0000011` (can be modified [here](https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/src/properties/login.properties#L65) or [here](https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/src/properties/login.properties#L71)).

**Comment by casp4** [comment]
Hi @jmelberg-okta, thank you for getting back to me. We are already creating a custom error page but not self-hosting. This means that on page load, there is no config object nor is there any indication of which error code it actually is. 

I can see that the "Bad Request" is bucketed into several i18n keys and I would love to override them for both english and chinese. 

As an aside, what I'd _really_ like to do is set the config overrides on the login customisation page (https://developer.okta.com/docs/guides/style-the-widget/style-okta-hosted/) that's hosted, via the config object accessible on there but it unfortunately doesn't contain most of what's listed in the `login.properties` file.

Right now, the only option I can see to override the error messages shown is to do a literal text compare and replace. This makes me sad.

```javascript
let content = div.innerHTML.trim();
if (content == 'default error') {
  // set innerHTML to desired text
}
```

And this doesn't actually cover the language situation where atleast on the login page I can check language via `config.language`.

Can you advise what you mean by `You should be able to customize this text by creating a custom error page.` that would look less hacky than the above snippet, please?

**Comment by casp4** [comment]
After some consideration I wonder if we shouldn't be setting the text override on a config object via terraform, since that's what we use to set other settings for Okta at the moment.

**Comment by jmelberg-okta** [comment]
Hey @casp4 - It sounds like we're wanting additional customization options for the [Custom Okta-hosted Error Page](https://developer.okta.com/docs/guides/custom-error-pages/edit-the-error-page/), which would allow you to easily add internationalization support for different types of errors. At the moment, I don't think this is supported - nor is having the [Widget's language options](https://github.com/okta/okta-signin-widget/#language-and-text) extend to these custom error pages.

Since this issue appears to be related to **Okta Error Pages**, not the Sign-in Widget - I'm going to close this issue for now. 

I have a message out to our customizations team to see if this is on their roadmap, so I'll follow-up here early next week once I know for sure. Alternatively, you're welcome to post in the [Okta DevForum](https://devforum.okta.com/), which has a closer tie to our support team.

**Comment by jmelberg-okta** [comment]
Hi @casp4 - Following up from last week!

After chatting with our customizations team, it currently is **not possible** to localize our server-side errors. The only user-facing messages that can be overwritten are the ones rendered within the Sign-in Widget. In your test scenario mentioned above, this unfortunately falls outside of the realm of the Widget.

The team is investigating providing a mechanism to do so, so hopefully we can make this possible in the near future!
