### ISSUE TITLE
Custom events are missing in case of Errors in OKTA sign-in widget

### ISSUE THREAD

**Issue by droy-deloitte** [okta/okta-signin-widget#2051]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request 
 
###Describe your issue or request here (if necessary).
The sign-in widget can't handle error scenarios. In case a user is not assigned to an app, then instead of state and code, it passes state, error, and error_description in the redirect URI. How can this be handled in Frontend?

### Expected behavior
What should have happened? 
On the error scenario, some custom event should be fired and from Frontend, we can subscribe to it and a callback would be running in case of some errors.

### Steps to reproduce
A user is not assigned to the OKTA app and the user is trying to login with the same Email Id, then authn, authroize call happens. authorize call redirects to redirect URI 
**redirect-uri?state=xxxxxxxxxx&error=access_denied&error_description=User+is+not+assigned+to+the+client+application.**
This should be handled from Frontend

### Your environment
  - Okta Sign-In Widget Version: 5.7.0
  - Browser: Chrome
  - OS: Windows
  - Language: Frontend: jQuery, Backend: Java

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reaching out @droy-deloitte.

You can subscribe to error events by adding [`afterError`](https://github.com/okta/okta-signin-widget#aftererror) handler.
Also, it looks like SIW is also handling this particular error by displaying an error message above the sign in form. You could check out this behavior in our React [sample app](https://github.com/okta/samples-js-react/tree/master/custom-login).

**Comment by droy-deloitte** [comment]
The above solution is not working for the issue mentioned. 
Our Environment is a multi-page application. 

We need another help also, If the client ID is wrong, can the above solution handle the error?

**Comment by oleksandrpravosudko-okta** [comment]
Ticket to track further investigation:
Internal Ref: OKTA-408673

**Comment by oleksandrpravosudko-okta** [comment]
@droy-deloitte a couple of follow-up questions:
* are you using Okta-hosted flow (signin widget is served from Okta org page) or the page containing signin widget is provided by your own backend? 
* is your OIDC application created as a `Web Application` in Okta dashboard?

**Comment by oleksandrpravosudko-okta** [comment]
@droy-deloitte Closing this issue. Please feel free to re-open with more details if necessary.
