### ISSUE TITLE
React Wrapper Component for this library

### ISSUE THREAD

**Issue by lawrencetvo** [okta/okta-signin-widget#207]
Hello all,

React is becoming a very popular framework for frontend web development and as such, I feel like having a React wrapper component for this library would be extremely useful. I can build one to make it closer to the React methodology but only if I get prior approval from the mods of this library.

**Comment by rchild-okta** [comment]
@lawrencetvo - sounds like a great idea (definitely something we're interested in). How are you planning on building it, and from your perspective is it something that would actually be part of this repo? For example, another option is to write the wrapper and consume the widget from there - it doesn't seem like there should be any changes to the base widget, right?

**Comment by lawrencetvo** [comment]
@rchild-okta I was planning on making a separate repo for the wrapper and then using this library within that wrapper. That way, core functionality and development can happen here and the wrapper will expose the functionality in a more React-like format.

I'll start development on it and then show off the initial repo.

**Comment by rchild-okta** [comment]
Perfect - looking forward to it.

**Comment by lawrencetvo** [comment]
Progress is found here:

**Comment by lawrencetvo** [comment]
Github repo can be found here:
https://github.com/lawrencetvo/react-okta-signin-widget

package (as of this date and time) is not fully functional. Rather, it only contains the basic architecture of how to approach making this more React-like.

**Comment by rchild-okta** [comment]
Looks like a good start 👍 

@magizh-okta, you might also be interested in this ^^

**Comment by lawrencetvo** [comment]
@rchild-okta @magizh-okta I updated the repo's README to reflect my thinking process so far. What's your feedback?

Also, I'm not entirely sure how to integrate the OIDC and the session portion of the widget into the wrapper. What do you think is the best way of doing so?

Thanks!

**Comment by lawrencetvo** [comment]
https://github.com/okta/samples-js-react

It seems there is already a lib for this?

**Comment by rchild-okta** [comment]
@lawrencetvo - that's a sample implementation, i.e. we haven't broken it out into a wrapper library yet. We are planning on spending more time on client SDK's later this month to next month.

**Comment by lawrencetvo** [comment]
@rchild-okta  sounds good, should I continue development?

**Comment by rchild-okta** [comment]
@lawrencetvo It's totally up to you - if you're interested, I think it'd serve as a good starting point for us when we're building out the wrapper.

**Comment by lboyette-okta** [comment]
We currently have a guide outlining a simple integration with React and the widget. If you're interested in building out a deeper integration, you're welcome to! For now, we'll be closing this issue.

https://developer.okta.com/code/react/okta_react_sign-in_widget.html#create-a-widget-wrapper
