### ISSUE TITLE
TypeError: $.cookie is not a function

### ISSUE THREAD

**Issue by GitShaffi** [okta/okta-signin-widget#215]
Getting Uncaught TypeError: $.cookie is not a function at Object.fn.getCookieUsername (okta-sign-in.entry.js) in renderEl function

**Comment by rchild-okta** [comment]
@GitShaffi, can you add some details on how you're configuring the widget, and the flow to get into this state?

**Comment by GitShaffi** [comment]
@rchild-okta 
"@okta/okta-signin-widget": "^1.9.0",
and i am using the LoginPage component from https://github.com/leebrandt/okta-react-widget-sample/tree/1cdbfb4f1bf2ec66ffc44d3a88d6503561173e45

this works fine if i have the okat-widget with a static html and use https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/1.9.0/js/okta-sign-in.min.js from cdn

but the same doesn't work if i have it as react component and have import OktaSignInWidget from '@okta/okta-signin-widget';

**Comment by jmelberg-okta** [comment]
Hi @GitShaffi. To make sure we better understand what could be causing this, can you run the following command to give us the version of the Widget you are using?
```bash
$ cd node_modules
$ npm list @okta/okta-signin-widget
```

One quick note, have you tried pulling from master? Looks like you were referencing an early commit.

**Comment by GitShaffi** [comment]
Hi @jmelberg-okta 

└── @okta/okta-signin-widget@1.11.0

I find the above version in my node_modules. It seems to be the latest master version.

**Comment by ericmcgregor** [comment]
same issue.

**Comment by amitkapps** [comment]
Is there a way to get it to work with later versions?

**Comment by mwld** [comment]
I have a similar issue where 1.9.0 works but more recent versions do not: https://github.com/okta/okta-signin-widget/issues/263

**Comment by kurtfurbush** [comment]
@rchild-okta any response on this? Same issue for me using 1.11.0.

**Comment by rchild-okta** [comment]
@samerfanek-okta @lboyette-okta ^^

**Comment by kurtfurbush** [comment]
As info, I updated to 2.1 and it's working for me.

**Comment by kylefoley** [comment]
Updated to 2.1 as well, not working

**Comment by rw3iss** [comment]
Same issue on 2.1.0.

**Comment by rw3iss** [comment]
Was able to get around this by installing 'js-cookie' npm module, and then editing the @okta/okta-signin-widget/dist/js/okta-sign-in-entry.js file's occurrences of $.cookie (there were only 3) with the new API, which is the same, but should be 'Cookies' instead of '$.cookie', ie:

```
function setCookie (name, value) {
	Cookies(name, value, {
		expires: DAYS_SAVE_REMEMBER,
		path: '/'
	});
}
```

**Comment by rw3iss** [comment]
Note, you can also get around this if you edit the module's package.json and change the main entry to the no-jquery version, ie:
"main": "./dist/js/okta-sign-in-no-jquery.js"
This solved both problems for me ($.cookie error, and also the widget not showing anything).

**Comment by kylefoley** [comment]
Can confirm @rw3iss workaround. I was having a problem where the successCB wouldn't fire, even after it got a success response. Works now

My verison info: 
`"react": "^15.6.1",`
`"@okta/okta-auth-js": "^1.8.0",`
`"@okta/okta-signin-widget": "^2.1.0",`

**Comment by rw3iss** [comment]
@kylefoley Yer welcome. We're not robots, yet. Even then, hopefully they'll show their thanks.

**Comment by kylefoley** [comment]
It's only a matter of time *insert robot beeps here*

**Comment by manueltanzi-okta** [comment]
Hi @GitShaffi , do you still have this issue?

**Comment by CharlieKuharski** [comment]
I have the same issue with VueJs. I tried the suggestions which yielded "Cookies is undefined"

Versions.
---------------
"js-cookie": "^2.1.4",
"@okta/okta-signin-widget": "^2.1.0",
"vue": "^2.2.2",
npm: '4.2.0',
node: 6.10.3

**Comment by kathleentully** [comment]
I've found that installing @okta/okta-signin-widget as: `npm i --legacy-bundling @okta/okta-signin-widget` will fix this as well, but that's not a particularly helpful solution as there's no way to mark in `package.json` that this package needs to be install this way, so it's not very portable.

The difference between legacy and the new bundling pattern is explained here. Essentially, it seems like @okta/okta-signin-widget is looking for its dependencies within its own `node_modules` directory, rather than the generalized `node_modules`.
legacy directory structure:
```
- node_modules
   - okta
     - okta-signin-widget
       - node_modules
         - okta
           - okta-auth-js
```
current default directory structure:
```
- node_modules
   - okta
     - okta-signin-widget
     - okta-auth-js
```
Are the jQuery dependencies being referenced somewhere based on their relative location to the root of this repository?

**Comment by fergalmoran** [comment]
Seeing this too with 2.4.0, workarounds "work" but are clearly unusable in real-world scenarios.

@manueltanzi-okta this issue is 4 months old, really not a good look for people researching okta for production use.

**Comment by santhoshbalakrishnan** [comment]
The latest release of the widget (2.5.0) fixes this issue:

```
npm install @okta/okta-signin-widget@2.5.0 --save
```

You'll need to import the widget directly:
```
import * as OktaSignIn from '@okta/okta-signin-widget'
```

**Comment by crazyman1979** [comment]
Still seeing this with 2.5.0

**Comment by CharlieKuharski** [comment]
It didn't work for me either.  I am using 2.5.0 but I'm using the same work around as the previous version.
Here is what I use for VueJs

1. Load the Sign-In Widget module **directly**.  
 ` const OktaSignIn = require('@okta/okta-signin-widget/dist/js/okta-sign-in.min.js');`

2. The css resources can't be found so put it somewhere the for the app.  In my case I used the 'static' folder
```
// In my 'static' folder 
okta-sign-in.min.css
okta-theme.css
okta-custom.css
```
3. Lastly, reference the css in the html.
```
 <link rel="stylesheet" type="text/css" href='static/okta-sign-in.min.css'>
 <link rel="stylesheet" type="text/css" href='static/okta-theme.css'>
 <link rel="stylesheet" type="text/css" href='static/okta-custom.css'>
```

**Comment by crazyman1979** [comment]
Ive found about 5 issues with 2.5 that are supposed to be fixed in 2.5, currently un-usable for me

**Comment by crazyman1979** [comment]
@CharlieKuharski when i try this i get

```
zone.js:634 Uncaught TypeError: NativePromise.resolve is not a function
    at Object.setNativePromise (zone.js:634)
    at desc.set (zone.js:1028)
    at t.exports (okta-sign-in.min.js:13)
    at l (okta-sign-in.min.js:13)
    at Object.eval (okta-sign-in.min.js:14)
    at e (okta-sign-in.min.js:13)
    at Object.eval (okta-sign-in.min.js:13)
    at e (okta-sign-in.min.js:13)
    at Object.eval (okta-sign-in.min.js:13)
    at Object.eval (okta-sign-in.min.js:13)
```

**Comment by santhoshbalakrishnan** [comment]
Hi @crazyman1979 @CharlieKuharski, Did you try importing directly from `'@okta/okta-signin-widget'` as opposed to `@okta/okta-signin-widget/dist/js/okta-sign-in.min.js`.

Also, it would be really helpful to get more details about how to reproduce what you are facing. Would it be possible for you to give us a barebones repository with your setup that has the issue?

**Comment by CharlieKuharski** [comment]
@santhoshbalakrishnan - yes, I tried the `'@okta/okta-signin-widget'`. And yes, maybe this weekend I can put up a base VueJS Okta-Widget project.

**Comment by santhoshbalakrishnan** [comment]
@CharlieKuharski That would help us a lot. Thank you! Also, this month we are looking into Vue JS. You can keep an eye on #344

**Comment by crazyman1979** [comment]
@santhoshbalakrishnan  Ive tried every approach, each time a different error comes up.
Sorry it wasn't a very helpful message i will try and do this for you tomorrow.

**Comment by lboyette-okta** [comment]
@crazyman1979 I'm not able to repro any of these issues using a fresh project created by `@angular/cli` following [this guide](https://developer.okta.com/code/angular/okta_angular_sign-in_widget) or created by `create-react-app` following [this guide](https://developer.okta.com/code/react/okta_react_sign-in_widget).

The issues seem to be resolved in 2.5.0 with fresh installs, so there could be a dependency mgmt problem. Try deleting your `node_modules` and/or your `package-lock.json` then reinstall.

@CharlieKuharski VueJS 🎆

**Comment by CharlieKuharski** [comment]
@ibabiy-okta @santhoshbalakrishnan  - Do you still need the VueJS/Okta template?

**Comment by santhoshbalakrishnan** [comment]
@CharlieKuharski Yes, please. Would help us iron out issues in VueJS.  CC: @lboyette-okta

**Comment by johnantoni** [comment]
thanks @CharlieKuharski that solved the issue for me

`const OktaSignIn = require('@okta/okta-signin-widget/dist/js/okta-sign-in.min.js');`

agree, hopefully this get's resolved in the 2.6.0 release

**Comment by agustincelentano** [comment]
It happens using the sign in widget for Angular :( 
"@okta/okta-signin-widget": "^2.6.0"

**Comment by oklas** [comment]
Using `/dist/js/okta-sign-in-no-jquery.js` is very bad idea. It include almost a Megabyte overhead to bundle which will be loaded each time. Include jquery itself from any CDN is better because is a chance that it already in browser cache and downloading may be omited.

**Comment by oklas** [comment]
Using jquery in react app is bad idea. Using /dist/js/okta-sign-in-no-jquery.js is very bad idea. It include almost a Megabyte overhead to bundle which will be loaded each time. Include jquery itself from any CDN is better because is a chance that it already in browser cache and downloading may be omited.

**Comment by oklas** [comment]
Using jquery in react app is dubious idea. Using /dist/js/okta-sign-in-no-jquery.js is very bad idea. It include almost a Megabyte overhead to bundle which will be loaded each time. Include jquery itself from any CDN is better because is a chance that it already in browser cache and downloading may be omited.
