### ISSUE TITLE
Wrong swedish translation 

### ISSUE THREAD

**Issue by PeterQwarnstrom** [okta/okta-signin-widget#2156]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Swedish translation of `primaryauth.username.placeholder` and `primaryauth.username.tooltip` is wrong. 

### Expected behavior

`primaryauth.username.placeholder` and `primaryauth.username.tooltip` should be translated to `Anv\u00E4ndarnamn`

### Your environment

  - Okta Sign-In Widget Version: 5
  - Browser: 
  - OS: 
  - Language: Swedish

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref: OKTA-420781

**Comment by denysoblohin-okta** [comment]
Fixed in 5.12.0
