### ISSUE TITLE
Error loading registration form

### ISSUE THREAD

**Issue by m4rcoperuano** [okta/okta-signin-widget#2188]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Hey guys. First, love the service. Here's my problem. I'm trying to enable self-serve registration via the Okta Signin Widget for your service Okta Identity Engine. I went ahead and:

1. Enabled self serve registration via the Admin panel
2. Verified that it works by first integrating the Okta Redirect Authentication workflow (instead of using the widget).
3. Integrated the widget into my web app.
4. The login functionality works just fine.
5. I enabled the `features.registration` flag.
6. I see the link to register now (see image below)
7.  ![2021-09-06 at 10 17 PM](https://user-images.githubusercontent.com/3129510/132274111-63405a2f-1c59-477b-90c8-4a610746e086.png)
8. I then notice that nothing loads...
9. ![2021-09-06 at 10 18 PM](https://user-images.githubusercontent.com/3129510/132274146-9d41d08e-48e1-462d-8a90-e72d1d2d356f.png)
10. Looking at the network log, I received a 501 response, with this error message:

```
{
    "errorCode": "E0000060",
    "errorSummary": "Unsupported operation.",
    "errorLink": "E0000060",
    "errorId": "oaeuBLa7bpCQfyRzJ8EEd4_2g",
    "errorCauses": []
}
```

### Expected behavior

The registration page should have loaded.

### What went wrong?

Here it is again:

```json
{
    "errorCode": "E0000060",
    "errorSummary": "Unsupported operation.",
    "errorLink": "E0000060",
    "errorId": "oaeuBLa7bpCQfyRzJ8EEd4_2g",
    "errorCauses": []
}
```

### Steps to reproduce

1. If you go into this JSFiddle: https://jsfiddle.net/m2gyLq4v/ and use this javascript code:
```javascript
var orgUrl = "https://oie-5280103.oktapreview.com";

// config
var config = {
    baseUrl: orgUrl,
    features: {
	    registration: true
    }
};

// render widget
var oktaSignIn = new OktaSignIn(config);
oktaSignIn.renderEl({ el: '#okta-login-container' },
    function(res) {
        // success fn
        res.session.setCookieAndRedirect(orgUrl);
    },
    function(error) {
        // failure fn
        console.log(error.message, error);
    }
);
```

2. Then click on Sign Up, your sign up form does not load.

### Your environment

  - Okta Sign-In Widget Version: 5.10.1
  - Browser: Safari (Version 14.1.2 (16611.3.10.1.6)
  - OS: Mac Big Sur (11.5.2)
  - Language: Javascript

**Comment by oleksandrpravosudko-okta** [comment]
Hi @m4rcoperuano - thanks for your interest in OIE!

As far as I am aware, specifying `registration: true` is not necessary for widget in OIE-enabled orgs.

To make widget work in OIE mode you need to pass `useInteractionCodeFlow: true` configuration parameter and also bootstrap widget with the values returned from `/introspect` call (example can be found in our [sample app](https://github.com/okta/okta-auth-js/blob/master/samples/generated/express-embedded-sign-in-widget/web-server/routes/login.js#L51)).

**Comment by vijetmahabaleshwar-okta** [comment]
Hi @m4rcoperuano , @oleksandrpravosudko-okta is right. You don't need to specify the `registration: true` flag for Okta Identity Engine orgs. This configuration is now driver by server side policy settings. 

Registration is now handled by a feature called "Profile Enrollment". Read this document to know how to use it - https://help.okta.com/oie/en-us/Content/Topics/identity-engine/policies/create-profile-enrollment-policy-sr.htm

**Comment by m4rcoperuano** [comment]
Hey guys, thanks for the direction. I went ahead and incorporated the "useInteractionCodeFlow". I've also enabled the Profile Enrollment as @vijetmahabaleshwar-okta said. I also learned a LOT about PKCE since I could no longer use the implicit authentication flow I had set up before. So, here's where I'm at. My sign in widget loads just fine and the registration form loads as well.

![2021-09-08 at 9 12 AM](https://user-images.githubusercontent.com/3129510/132515823-130c5a2c-bc6c-44e4-88de-0808192884c3.png)

```javascript
        let config = {};
        config.baseUrl = "{{ config('okta-auth-provider.base_uri') }}";
        config.clientId = "{{ config('okta-auth-provider.client_id') }}";
        config.redirectUri = "{{ config('okta-auth-provider.oauth_callback_uri') }}";
        config.authParams = {
            issuer: "{{ config('okta-auth-provider.issuer') }}",
            responseType: 'code',
            scopes: [ 'openid', 'profile' ]
        };
        config.el = '#sign-in-widget';
        config.useInteractionCodeFlow = true;
        config.state = "start";
        config.interactionHandle = (data) => {
            console.log(data);
        }
        config.codeChallenge = '{{ Session::get("code-challenge") }}';
        config.codeChallengeMethod = 'S256';

        (new OktaSignIn(config)).showSignInAndRedirect()
            .catch(err => {
                console.log('Error happen in showSignInAndRedirect: ', err);
            });;
```

#### Generating the code challenge

The way I generate the code challenge is by 
1. Creating a plain random string, this is my code verifier. 
2. I then create the code challenge by hashing my code verifier using SHA256. 
3. I then base64 URL encode the result of # 2. That becomes my code challenge.
4. I store in a session variable my code verifier (the string from # 1).

```php
    public function showLoginForm()
    {
        $codeVerifier = Str::random(86);
        $codeChallenge = $this->base64url_encode(hash('sha256', $codeVerifier));
        Session::put("code-verifier", $codeVerifier);
        Session::put("code-challenge", $codeChallenge);

        return view('auth.login');
    }
```

#### Receiving the interaction_code callback

I then receive my interaction code once I log in:

```php
        $headers = [
            'Accept'         => 'application/json',
            'Content-Type'   => 'application/x-www-form-urlencoded',
        ];

        $query = http_build_query([
            'grant_type'       => 'interaction_code',
            'interaction_code' => $interactionCode,
            'code_verifier'    => Session::pull('code-verifier'),
            'client_id'        => $this->clientId,
            'client_secret'    => $this->clientSecret
        ]);

        $url      = $this->issuer . '/v1/token?' . $query;
        $response = Http::withHeaders($headers)->post($url);
```

I was expecting this to work, but I consistently get the error message:
`{"error":"invalid_grant","error_description":"PKCE verification failed."}`

I've been at this for a good number of hours, trying to:
- wrap my code verifier into the base64 URL encoder first
- verifying that the sign in widget is loaded using my code challenge
- changed how I base64 URL encode

I'm kind of at a loss now. Hope you guys can help shed some light.
Thanks

**Comment by m4rcoperuano** [comment]
Update! 🎉 
I figured it out. It turns out that, in PHP, when you use the `hash()` function, you'll receive a string as the result. This string that gets base64 encoded to become the "Code Challenge", is not what _should_ get base64 encoded. Rather, the hash() should return a binary result, that is **then** base64 encoded. So all I had to do was:

```php
   public function showLoginForm()
    {
        $codeVerifier = Str::random(80);
        $codeChallenge = $this->base64url_encode(hash('sha256', $codeVerifier, true)); 
        //// change the hash() function to accept "true" as it's third parameter >_>
        Session::put("code-verifier", $codeVerifier);
        Session::put("code-challenge", $codeChallenge);

        return view('auth.login');
    }
```

I appreciate the help regardless. Thanks!
