### ISSUE TITLE
Invalid CSS. Can't build Angular app

### ISSUE THREAD

**Issue by gultyaev** [okta/okta-signin-widget#2189]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I have an Angular 12 app with latest Ionic.
When I have in my `global.scss` file line `"~@okta/okta-signin-widget/dist/css/okta-sign-in.min.css"` the production build fails with error

> ✖ Index html generation failed.
> undefined:2:49: missing '}'

During some tests I came across `*display` property in the `min.css` which seems to be invalid and breaking during the optimization phase.

### Expected behavior

Should not contain invalid properties so that builders/minifiers can work.

### Steps to reproduce

Setup an Angular 12 app using Ionic CLI. Then import Okta widget styles into the global `.scss` file using `@import "~@okta/okta-signin-widget/dist/css/okta-sign-in.min.css";`

### Your environment

  - Okta Sign-In Widget Version: ^5.10.1
  - OS: MacOS
  - Language: EN

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reporting this @gultyaev.

It looks like this is already fixed in https://github.com/okta/okta-signin-widget/pull/2179 but is not released yet.
The release is likely to happen this or next week.

**Comment by gultyaev** [comment]
Thanks for the response. 

Is it planned to have SASS styles available for extension?

For example I'd like to import it into my gobal styles and change the variables instead of importing minified CSS and then overriding the styles.

Currently it's impossible because:
1. It uses non relative import paths so my builder cannot resolve them
2. It doesn't define SASS variables as default so they could easily be replaced

**Comment by aarongranick-okta** [comment]
@gultyaev If you install the widget via NPM, the SASS source files are in the `dist/sass` folder.  You may be able to do something like `import @okta/okta-signin-widget/dist/sass/okta-sign-in.scss`

**Comment by gultyaev** [comment]
Has this fix been included in 5.11.0?

**Comment by oleksandrpravosudko-okta** [comment]
No, it is slated for the next release (~Oct 1st) - apologies for providing incorrect timeframe.

**Comment by gultyaev** [comment]
Is this included in 5.12.0?

**Comment by oleksandrpravosudko-okta** [comment]
Yes - https://github.com/okta/okta-signin-widget/commit/238bc9657f32e4d96f699211d9f935d79eafa912 is a part of `5.12` branch (release notes updated).
