### ISSUE TITLE
PIV login does not redirect back to application and redirects to `.../app/UserHome`

### ISSUE THREAD

**Issue by anthonysessa** [okta/okta-signin-widget#2198]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Describe your issue or request here (if necessary).

We are using PIV card IDP with the `piv` configuration options.  We are able to successfully sign in using the PIV Card, but it always is redirecting to the `/app/UserHome`

### Expected behavior

Should redirect back to web application (http://localhost:3000/login/callback)

### Steps to reproduce

```typescript
const widgetRef = useRef();

useEffect(() => {
  if (!widgetRef.current) {
    return false;
  }
  console.log(config.oidc.redirectUri);
  const { issuer, clientId, scopes } = config.oidc;
  const widget = new OktaSignIn({
    baseUrl: issuer.split('/oauth2')[0],
    redirectUri: config.oidc.redirectUri,
    clientId,
    logo: '/react.svg',
    i18n: {
      en: {
        'primaryauth.title': 'Sign in to React & Company',
      },
    },
    authParams: {
      issuer,
      scopes,
      display: 'page',
      pkce: false,
    // responseType: 'id_token',
    },
    features: {
      idpDiscovery: true,
    },
    idpDiscovery: {
      requestContext: window.location.href,
    },
    piv: {
      certAuthUrl: 'https://dev-72405853.mtls.okta.com/api/internal/v1/authn/cert',
      text: 'Authenticate with a Smart Card',
      className: 'custom-style',
      isCustomDomain: false,
    },
    useInteractionCodeFlow: false, // Set to true, if your org is OIE enabled
  });
  widget.renderEl(
    { el: widgetRef.current },
    (res) => {
      // NEVER REACHES HERE
      // oktaAuth.handleLoginRedirect(res.tokens);
      if (res.status === 'IDP_DISCOVERY') {
        res.idpDiscovery.redirectToIdp();
      }
    },
    (err) => {
      throw err;
    },
  ).then((res) => {
    if (res.status === 'SUCCESS') {
    // user is authenticated
      console.log('user is authenticated', res.user);
    }
  });
```

### Your environment

  - Okta Sign-In Widget Version: `^5.8.4`
  - Browser: `Chrome`
  - OS: `Windows 10`
  - Language: `EN`

**Comment by aarongranick-okta** [comment]
@anthonysessa Thank you for the report. We will investigate and follow up here on GitHub. Internal ref: OKTA-427596

**Comment by denysoblohin-okta** [comment]
Try to set
```js
relayState: `http://localhost:3000/login/callback`,
```
in options passed to `OktaSignIn ` constructor

**Comment by deekoder** [comment]
@anthonysessa does it work for you when you see the relayState param as @denysoblohin-okta  has suggested?

**Comment by denysoblohin-okta** [comment]
We recommend upgrading to Okta Identity Engine to fix this problem.
You need to enable interaction code flow in your authorization server and pass `useInteractionCodeFlow: true` in the widget config.

If you want to request to gain access to the Okta Identity Engine, please reach out to your account manager. If you do not have an account manager, please reach out to oie@okta.com for more information.

More info:
https://developer.okta.com/docs/guides/migrate-to-oie/
https://developer.okta.com/docs/guides/oie-intro/#embedded-authentication-sample-apps
