### ISSUE TITLE
config.colors.brand no longer working

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#2211]
### I'm submitting a
  -  bug report

### Background info

We have a sign-in page customized using Customizations > Sign-in page code editor. Our customized code is minimal and is limited to changing some properties on `OktaUtil.getSignInWidgetConfig()`.

Specifically, we are changing `config.colors.brand`. Setting `brand` affected the SIW as expected until ~last week.

We have tested this on both the latest (5.latest) version, as well as an earlier version (2.latest). 

### Expected behavior

The submit button color should change.

### What went wrong?

The submit button color does not change. There are no console errors.

It looks like a CSS `!important` is overriding these customizations on the button.

### Steps to reproduce

```js
    <script type="text/javascript">
        var config = OktaUtil.getSignInWidgetConfig();

	config.features.rememberMe = false;
	config.features.showPasswordToggleOnSignInPage = true;
	config.colors = {
          brand: '#ff0000'
        };

        // Render the Okta Sign-In Widget
        var oktaSignIn = new OktaSignIn(config);
        oktaSignIn.renderEl({ el: '#okta-login-container' },
            OktaUtil.completeLogin,
            function(error) {
                // Logs errors that occur when configuring the widget.
                // Remove or replace this with your own custom error handler.
                console.log(error.message, error);
            }
        );
    </script>
```

### Your environment

  - Okta Sign-In Widget Version: 5.latest
  - Browser: Chrome
  - OS: Mac and Windows
  - Language: English

**Comment by deekoder** [comment]
Thanks, @nbarbettini will look into it.

**Comment by vijetmahabaleshwar-okta** [comment]
Hi @nbarbettini,

I wasn't able to reproduce the issue in my org. Can you confirm if this config and the resulting change in sign-in widget look good? 

![image](https://user-images.githubusercontent.com/27521424/135794344-72061536-d1d9-415d-b69e-b8250fd0b089.png)

![image](https://user-images.githubusercontent.com/27521424/135794365-52f84533-3102-4f16-b101-d1d3f6ea21fa.png)

**Comment by nbarbettini** [comment]
Thanks for looking into it @vijetmahabaleshwar-okta!
This seemed to resolve itself and I haven't noticed it recur.
