### ISSUE TITLE
handleLoginRedirect refresh the page

### ISSUE THREAD

**Issue by zehavibarak** [okta/okta-signin-widget#2227]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

We are using the sign in from Angular.

### Expected behavior

After sign in completes, we want to persist the token and use it from cache for subsequent http requets. 

### What went wrong?

The handleLoginRedirect() refreshes the page, while *no refresh is needed*.

```typescript
    signIn.showSignInToGetTokens({
      el: '#sign-in-widget',
      scopes: DEFAULT_SCOPES
    }).then(async tokens => {
      signIn.remove();

      await this._okta.handleLoginRedirect(tokens); // <--
      ...
    }).catch(err => ...);

```

Service should expose a method for persist, without refreshing the page.

### Your environment

  - Okta Sign-In Widget Version:
  - Browser: Chrome latest
  - OS: Win
  - Language: En

**Comment by shuowu** [comment]
@zehavibarak As you mentioned, the `handleLoginRedirect` method should not refresh the page, but I cannot reproduce your issue in our sample app.

Can you try our sample apps to see if the issue can be reproduced there? 

Angular: https://github.com/okta/samples-js-angular/custom-login
React: https://github.com/okta/samples-js-react/custom-login
Vue: https://github.com/okta/samples-js-vue/custom-login

**Comment by zehavibarak** [comment]
Apparently, the https://github.com/okta/samples-js-angular/custom-login is unavilable

**Comment by shuowu** [comment]
@zehavibarak Links fixed.

**Comment by zehavibarak** [comment]
Module ***@***.***/okta-angular"' has no exported member 'OktaAuthService'.

**Comment by shuowu** [comment]
Try [this branch](https://github.com/okta/samples-js-angular/pull/130) if you want to use the latest @okta/okta-angular version (v4). 

Otherwise, `npm install & npm start` should work for the current mainstream branch.

**Comment by zehavibarak** [comment]
It would be nice to get a solution for this.

**Comment by zehavibarak** [comment]
I did       this._oktaAuth.tokenManager.setTokens(tokens) after widget return, and omitted the handleLoginRedirect();
