### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by zehavibarak** [okta/okta-signin-widget#2294]
### I'm submitting a
  - [ X] bug report
  - [ ] feature request

### Background info

Upgrade to Angular 13

### What went wrong?

Chrome error "ERROR TypeError: (_okta_okta_signin_widget__WEBPACK_IMPORTED_MODULE_1___namespace_cache || (intermediate value)(intermediate value)) is not a constructor"

### Steps to reproduce

```
import * as OktaSignIn from '@okta/okta-signin-widget';

const signIn = new OktaSignIn({...}) // <- error in line
```

This may be a webpack issue, caused by widget source syntax.

### Your environment

  - Okta Sign-In Widget Version: 5.13.0
  - Browser: Chrome
  - OS: Windows
  - Language: Angular

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @zehavibarak.

This issue does not seem to be present in the barebones Angular 13 + SIW app - would you be able to share a code/configuration (with sensitive details removed) which triggers it?

**Comment by shuowu** [comment]
This might be a typescript issue due to okta-signin-widget is not currently bundled with types. Curious if ignore the type check, like `// @ts-ignore`, helps?

**Comment by zehavibarak** [comment]
I resolved this by adding (window as any).OktaSignIn(...)
