### ISSUE TITLE
showSignInToGetTokens Promise without any Response

### ISSUE THREAD

**Issue by jeremieLyvoc** [okta/okta-signin-widget#2296]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

My issue is exactly the same as  : https://github.com/okta/okta-signin-widget/issues/1765

I'm building a react app that implement the Okta widget. It is deployed as a static website inside a AWS S3 bucket and Cloudfront.

### Expected behavior

After giving username + password and clicking the sign-in button, the onSuccess or onError should be received. Then store token inside tokenManager and log in user.

### What went wrong?

The loading icon keeps spinning, no error are generated. 
The application never goes into onSuccess or onError, but I can the the tokens delivered by Okta in the network tab of the Chrome dev tools.

In the function `showSignInToGetTokens` of the imported file : [https://github.com/okta/okta-signin-widget/blob/master/src/widget/OktaSignIn.js](url) 

```
      const promise = this.renderEl(renderOptions).then(res => {
        return res.tokens;
      });
```

This seems to never get the tokens.

### Steps to reproduce

App URL : https://customer-portal-dev.arteliagroup.com
Test account : github@okta.com 
Test password : SRT5rz!S!B-f2&jq

### Your environment

  - Okta Sign-In Widget Version: latest
  - Browser: Chrome
  - Language: React / JS

**Comment by MikeMondragon-okta** [comment]
@jeremieLyvoc I'm sorry to hear about this bug but I've filed a bug in our internal system to get the client SDKs team to take a look. I'll note the same on #1765 

Okta Internal Reference: [OKTA-445189](https://oktainc.atlassian.net/browse/OKTA-445189)

**Comment by monde** [comment]
@jeremieLyvoc I'm sorry to hear about this bug but I've filed a bug in our internal system to get the client SDKs team to take a look. I'll note the same on #1765 

Okta Internal Reference: [OKTA-445189](https://oktainc.atlassian.net/browse/OKTA-445189)

**Comment by JacobTLeBlanc** [comment]
I am also having this exact issue, any updates on this by any chance?

**Comment by aarongranick-okta** [comment]
@jeremieLyvoc  I believe this issue has been fixed and is no longer a problem when using the latest version of okta-signin-widget. If you are still experiencing this issue, please open a new Github issue.
