### ISSUE TITLE
Older version of okta-auth-js referenced in latest sign-in-widget

### ISSUE THREAD

**Issue by mguay22** [okta/okta-signin-widget#2308]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

In latest version (5.14.0) of sign-in-widget, the okta-auth-js version referred in "devDependecies" section refers to "4.8.0" and due to that, we are not able to use the huge set of new APIs added to okta-auth-js library during development. Was there a certain reason for this? Is there a workaround?

### Expected behavior

Should have been using latest auth-js version.

### What went wrong?

Please provide log or error messages if applicable.

### Steps to reproduce

1. Create a new project, `yarn init`
2. Run `yarn add @okta/okta-signin-widget`
3. Open `node_modules/@okta/okta-signin-widget/package.json`
4. See `devDependency` `@okta/okta-auth-js` set to `4.8.0`

### Your environment

Okta Sign-In Widget Version: 5.14.0
Browser: Chrome, Edge
OS: Windows 10
Language: JavaScript/Angular9

**Comment by aarongranick-okta** [comment]
The widget has been updated to use the latest version of okta-auth-js. When using a separately installed version of okta-auth-js we recommend that it be the same version as that used by okta-signin-widget, since they will share transaction storage.

@mguay22 Thank you for the issue
