### ISSUE TITLE
RefreshToken in okta signin widget 

### ISSUE THREAD

**Issue by sambeet21** [okta/okta-signin-widget#2330]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Hello okta team I am trying to get the refresh token in the response when  user sign in successfully I am sending offline_access in scopes while initialising the signin widget. But in response I am not getting the refresh token. I also tried out the okta APIs in postman and there I am getting the refresh token but while using the signin widget I am not able to  

this.widget = new OktaSignIn({
      logo: "new.png",
      baseUrl: `${process.env.REACT_APP_OKTA_BASE_URL}`,
      features: {
        rememberMe: true,
        router: true,
      },
      authParams: {
        responseType: ["id_token", "token"]
        scopes: ['openid', 'email', 'offline_access']
      },
})

### Expected behavior

Should return the refresh token as well along with idToken and accessToken 

### What went wrong?

There is no error but I am not receiving the refresh token 

### Steps to reproduce

1. create one okta developer account -> get the client id and issue url 
2. Use that in signin widget for login
3. added in scope offline_access to receive refreshToken 
4. actual result refresh token not received while I check the developer console Application tab of browser the okta-token-storage not have refresh token. but I receive idToken and accessToken only 

### Your environment

  - Okta Sign-In Widget Version: 4.5.2
  - Browser: Chrome
  - OS: MAC
  - Language: EN

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Have you tried adding `refresh_token` to `responseType`?

**Comment by sambeet21** [comment]
Hi @denysoblohin-okta yes it was enabled I checked

**Comment by sambeet21** [comment]
Hi @denysoblohin-okta is there any update on the issue I am sending offline_access in scope but not receiving the refreshToken

**Comment by denysoblohin-okta** [comment]
Can't reproduce your issue.
Can you provide more info that can be helpful, like XHR dumps (with masking sensual and not secure data)?

**Comment by sambeet21** [comment]
Okay will provide you the steps that I followed in details.
1. Created an application (single page application) in okta dashboard for auth integration to my web app which is in react.
2. Enabled all the grant types along with refresh token as you shared previously in yhe screenshot. 
3. I use that client id and issuer url in my okta sign in widget@4.5.2
4. While initializing the okta signin widget in authParam setting I am sending openid and offline_access so as to receive a refresh token 
5. Now iam using the username and password to sign in
6. Sign in was successful 
7. The only problem is i am not geeting the refresh token if I check that in localstorage.. it has only idToken and access Token

**Comment by denysoblohin-okta** [comment]
Have you tried to update the widget version?

**Comment by sambeet21** [comment]
Yes. I tried the sample app which will appear once I set up the okta application. In that I tried out sending the offline access there I receiving the refreshToken.  One thing just want to check the token renew is automatic (meaning is the accessToken get renew after it expires automatically if i configure the widget with scopes openId and scopes)?

**Comment by denysoblohin-okta** [comment]
What widget version have you tried besides 4.5.2, have you tried latest one (5.14.1)?

**Comment by denysoblohin-okta** [comment]
By default `autoRenew` is true. 
You need to start service for autorenew:
`oktaSignIn.authClient.start()`

**Comment by denysoblohin-okta** [comment]
Widget version 5.0.0 upgrades okta-auth-js to v4 and have support of refresh token.
