### ISSUE TITLE
Widget using IDP Discovery gets into a bad state once a user enters incorrect credentials.

### ISSUE THREAD

**Issue by sflanker** [okta/okta-signin-widget#2337]
This bug is related to https://github.com/okta/okta-signin-widget/issues/1180

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

I'm using the widget with `showSignInToGetTokens()` and the following settings:

```javascript
      {
        baseUrl: ...,
        clientId: ...,
        redirectUri: ...,
        features: {
          idpDiscovery: true
        },
        authParams: {
          issuer: ...,
          pkce: true,
          responseMode: 'query',
          responseType: ['code'],
          state: ...,
          postLogoutRedirectUri: ...
        },
        signOutLink: ...
      }
```

This is a serious user experience issue that my SSO users hit on a regular basis. When an SSO user enters the wrong email address (for example there is an IDP mapping for *@host.com, but the user enters their.name@hoTS.com) they are taken to a screen with a read only username field and a password field (an no back button 😔 see https://github.com/okta/okta-signin-widget/issues/1180). If they then enter a password and submit, the login obviously fails, but the form then get's into the state where the user **can** edit the username field in order to re-attempt their login. My users regularly try to correct their initial mistake at this point by entering the correct email (e.i. their.name@host.com). But at this point they are attempting to log in using the Okta Identity Provider, and their account cannot log in this way (not to mention mistakenly sending their password to an institution that they ostensibly should not be sending their password to).

### Expected behavior

When IDP discovery is enabled and  a user fails to log in due to a bad email address and password either:

1) The email address field should remain readonly, and the users should have to click a back button to get back to the screen where they can change it.
2) If the user change the email address field the password field should disappear and IDP discovery should be re-run before they are able to enter a password again.

### What went wrong?

Users are able to (nay, encouraged to) enter an email address and password in a way that bypasses IDP discovery and sends the password the the wrong provider. The only way for the user to get back to a good state is to **refresh the entire page**.

### Steps to reproduce

1. Configure the okta widget to enable IDP Discovery and use `showSignInToGetTokens()` to display the widget.
2. Enter a non-sso email address into the login widget and click Next.
3. Enter any password and click Sign In.
4. Change the email address field to be an SSO enabled email address (i.e. routed to an external IDP) and enter the correct password. Click the Sign In button.

<img width="429" alt="Screen Shot 2021-12-23 at 12 04 42" src="https://user-images.githubusercontent.com/940246/147295377-483cd772-a4bd-4d3b-967b-066cdcf93d0c.png">
<img width="418" alt="Screen Shot 2021-12-23 at 12 05 36" src="https://user-images.githubusercontent.com/940246/147295388-4ccab244-4d3a-4459-ad81-25f514def1d5.png">
<img width="412" alt="Screen Shot 2021-12-23 at 12 05 49" src="https://user-images.githubusercontent.com/940246/147295394-576fa462-dde1-4a4c-9d63-3337ce3a0b8d.png">
<img width="412" alt="Screen Shot 2021-12-23 at 12 06 16" src="https://user-images.githubusercontent.com/940246/147295407-1efa4135-7ae5-43d3-9c20-486767b3fa34.png">

### Your environment

  - Okta Sign-In Widget Version: 5.14.1
  - Browser: Chromium

**Comment by denysoblohin-okta** [comment]
Issue has been fixed with https://github.com/okta/okta-signin-widget/pull/2839 (version 6.8.1)
