### ISSUE TITLE
Issue with node-fetch version

### ISSUE THREAD

**Issue by MirzetKameric** [okta/okta-signin-widget#2358]
### I'm submitting a
  - [ *] bug report
  - [ ] feature request

### Background info

Tested 62 dependencies for known issues, found 1 issue, 1 vulnerable path.

Issues with no direct upgrade or patch:
  ✗ Information Exposure [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFETCH-2342118] in node-fetch@2.6.1
    introduced by @okta/okta-signin-widget@5.12.0 > cross-fetch@3.1.4 > node-fetch@2.6.1
  This issue was fixed in versions: 2.6.7, 3.1.1

### Expected behavior

There should be no vulnerabilities

### What went wrong?

There is a vulnerability.

### Your environment

  - Okta Sign-In Widget Version: 5.16.1 still isnt fixed

**Comment by MirzetKameric** [comment]
I see that cross-fetch has upgraded node-fetch once already and they have PR to upgrade again to not have this issue. I guess here we just need to upgrade cross-fetch

**Comment by shuowu** [comment]
@cdierkens and @MirzetKameric The issue has been addressed in https://github.com/okta/okta-signin-widget/commit/91831f20b4d30bfca043cb97c1c282cc723d2f57 and released in version 6.0.0.
