### ISSUE TITLE
RelayState arg for /register endpoint stopped working

### ISSUE THREAD

**Issue by jrodrigop** [okta/okta-signin-widget#2399]
https://github.com/okta/okta-signin-widget/blob/0769bcfc372940b0ad54881f12c686f74abcd394/src/RegistrationController.js#L179

this has to do with Okta self-service registration feature, for some time we were using RelayState redirect argument in endpoint: .../register which this url is formed at: https://github.com/okta/okta-signin-widget/blob/master/src/RegistrationController.js#L167 And argument used in: https://github.com/okta/okta-signin-widget/blob/master/src/RegistrationController.js#L179 

Currently we send the URL where we want our users to be redirected, our use case is that we allow registration pages for different apps(e.g. myorg.okta.com/app1), then we use this argument to redirect to the proper app once user click activation link in email we did this by sending the app url in RelayState argument. Now this argument seems to be ignored since we get redirected to base url (myorg.okta.com) We decided to use this approach since Password reset has this documented as a side note at https://developer.okta.com/docs/reference/api/authn/#request-parameters-for-forgot-password 

References: 
See https://devforum.okta.com/t/redirect-to-application-after-activation/1538/7?u=cat

**Comment by denysoblohin-okta** [comment]
To be clear, do you use self-hosted sign-in widget v1 (you don't use `useInteractionCodeFlow` option)?
What Okta API call is performed in widget during self-service registration?

**Comment by jrodrigop** [comment]
Right V1 widget, the generated url is:
https://<OKTA_ORG_URL>/api/v1/registration/XXXXXXX/register
However just tried to reproduce this issue and found that is back to normal... no code changes in our side, maybe okta changes something in the backend
