### ISSUE TITLE
Using a social login (Google) briefly shows a popup window in 6.0.1

### ISSUE THREAD

**Issue by jcwchriswalker** [okta/okta-signin-widget#2404]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info
In migrating from siginin widget 4.3.2 to 6.0.1, signing in with  Google provider will show an **empty** popup window with title 'signing in...' for a few seconds and then disappears after the sign-in completes. This behavior did not happen with 4.3.2. When the user clicked the 'sign in with google' in 4.3.2, no blank popup window appeared during signin. 
Note that this popup window does not appear when using an Okta userid/password, only with the 'sign in with Google' button.

### Expected behavior
The user should not see an empty popup when using the sign-in with google option

### What went wrong?
The popup window that initially shows 'about: blank' then titled: 'signing in....' with an okta-dev url appears for a few seconds.

### Steps to reproduce

`import OktaSignIn from '@okta/okta-signin-widget';`
```
this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
            clientId: "xxxx",
            baseUrl: 'https://dev-xxxxxxx.okta.com',
            logo: this.Settings.ApplicationPath + '/css/images/my logo.png',
            redirectUri: this.redirectUrl,
            authParams: {
                issuer: "https://dev-xxxxxx.okta.com/oauth2/default",
                scopes: ['openid', 'email', 'profile']
            },
            idps: [
                { type: 'google', id: 'xxxxxxxx' }
            ],
            features: {
                registration: true
            }
        });
```
```
async login() {
        const accessToken = await this.signIn.authClient.tokenManager.get('accessToken');
        if (!accessToken || this.signIn.authClient.tokenManager.hasExpired(accessToken)) {
            this.signIn.showSignInToGetTokens()
                .then((tokens) => {
                    this.signIn.authClient.tokenManager.setTokens(tokens);
                    this.signIn.remove();
                    this.currentUserName = tokens.idToken.claims.name;
                    this.organizationString = tokens.idToken.claims.organization;
                    $(this).trigger('signedin', tokens.idToken);
                })
                .catch(function (error) {
                    debugger;
                });
        } else {
            const idToken = await this.signIn.authClient.tokenManager.get('idToken')
            this.organizationString = idToken.claims.organization;
            this.currentUserName = idToken.claims.name;
            $(this).trigger('signedin', idToken);
        }
```
### Your environment

  - Okta Sign-In Widget Version: 6.0.1
  - Browser: Chrome 98
  - OS: Windows 10
  - Language: Typescript/javascript- target ES2017

**Comment by denysoblohin-okta** [comment]
By default `authParams.display` is set to `popup` (see "authParams.display" description in [readme](https://github.com/okta/okta-signin-widget#openid-connect))
Looks like you want to use `display: 'page'` to use redirect instead of popup

**Comment by jcwchriswalker** [comment]
I set the display to 'page' with the same result. Here is what my authParams now looks like:
 ```
 authParams: {
                issuer: "https://dev-xxxxxxxx.okta.com/oauth2/default",
                scopes: ['openid', 'email', 'profile'],
                display: 'page'
            },
```
I also went back to V5 versions (as well as 6.0.0) of the signin wiget with the same results which tells me that I am missing something in the configuration. For what its worth, I even set the display value to be 'xxxpage' with the same result and no error message.

**Comment by aarongranick-okta** [comment]
@jcwchriswalker The problem may be with using `showSignInToGetTokens`. This method prevents all redirection so that it can return tokens directly to your app. To allow redirect (to Google IDP) your app needs to handle the login callback (redirectUri).  Try calling `showSignIn` instead. This method will allow redirection.

**Comment by jcwchriswalker** [comment]
@aarongranick-okta , I switched out `showSignInToGetTokens` with `showSignIn` with the same results. I even set `authParams.pkce:true` in case it really didn't default to true per the documentation. Once again using the Okta userid/password works in both cases while the google sign in does not.

**Comment by jcwchriswalker** [comment]
@aarongranick-okta - OK this gets rid of the popup and now puts the codes in my URL as the document says. This now happens for both the Okta signin and Google signin. Does the widget have a way to process url?  It seems that while I dont have the popup for google, I have to now handle both logins (Okta and Google) now. Is there a sample where it shows a social login process using PKCE? Thanks!

**Comment by jcwchriswalker** [comment]
After trying several different configurations, this works for both the social login and the Okta login:
```
this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
            clientId: "xxxxxxxxx",
            baseUrl: 'https://dev-xxxxxxx.okta.com',
            redirectUri: this.redirectUrl,
            redirect: 'always',
            authParams: {
                pkce: true,
                issuer: "https://dev-xxxxxx.okta.com/oauth2/default",
                scopes: ['openid', 'email', 'profile'],
            },
            idps: [
                { type: 'google', id: '0oaq8bv5gkGq79sv14x6' }
            ],
            features: {
                registration: true
            }
        });
```

 ```
async login() {
        const sessionExists = await this.signIn.authClient.session.exists();
        if (sessionExists) {
            if (this.signIn.authClient.isLoginRedirect()) {
                const response = await this.signIn.authClient.storeTokensFromRedirect();
            }
            const idToken = await this.signIn.authClient.tokenManager.get('idToken');
            this.organization = idToken.claims.organization;
            this.currentUserName = idToken.claims.name;
            $(this).trigger('signedin');
        }
        else {
            // show the signin widget
            this.signIn.showSignIn();
        };
    }

```
