### ISSUE TITLE
sign-in-widget import error in angular 13

### ISSUE THREAD

**Issue by kpredde** [okta/okta-signin-widget#2421]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Angular 13 library showing error for import

### Expected behavior

Import for OktaSignIn from '@okta/okta-signin-widget' should not throw error

### What went wrong?

`Could not find a declaration file for module '@okta/okta-signin-widget'. '../auth-lib/node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.entry.js' implicitly has an 'any' type.`
`Try npm i --save-dev @types/okta__okta-signin-widget if it exists or add a new declaration (.d.ts) file containing declare module '@okta/okta-signin-widget';`

### Steps to reproduce

- Create an Angular 13 library
- import okta-signin-widget into a service.ts which throws the error

```
import { Injectable } from '@angular/core';
import * as OktaSignIn from '@okta/okta-signin-widget';  // <- error in line

@Injectable({
  providedIn: 'root',
})
export class Okta {
  widget;

  constructor() {
    this.widget = new OktaSignIn({
      baseUrl: 'https://{yourOktaDomain}',
      clientId: '{clientId}',
      redirectUri: 'http://localhost:4200',
    });
  }

  getWidget() {
    return this.widget;
  }
}
```

### Your environment

  - Okta Sign-In Widget Version: 6.1.0
  - Browser: N/A
  - OS: Windows
  - Language: Angular 13

**Comment by jaredperreault-okta** [comment]
`okta-signin-widget` is not written in TypeScript and does not have types. You'll have to add a `// @ts-ignore` statement above the import line.

See angular sample: https://github.com/okta/samples-js-angular/blob/master/custom-login/src/app/login/login.component.ts#L16

**Comment by jaredperreault-okta** [comment]
Closing issue, feel free to reopen
