### ISSUE TITLE
Module not found: Error: Cannot resolve module '@okta/qtip2'

### ISSUE THREAD

**Issue by GitShaffi** [okta/okta-signin-widget#246]
Getting the above error with the latest version 1.12.0. Please resolve this issue.

**Comment by jmelberg-okta** [comment]
@GitShaffi: We are publishing a new release with the fix #245. In the meantime, the bug-fix has been merged into `master`, so you can rebuild it directly with:
```sh
$ npm run build:release
```

**Comment by jmelberg-okta** [comment]
Version 1.13.0 is now live with this fix. [@okta/okta-signin-widget](https://www.npmjs.com/package/@okta/okta-signin-widget)
