### ISSUE TITLE
App variables do not populate in emails when "Forgot Password" is initiated from an OIE and self-hosted sign-in widget

### ISSUE THREAD

**Issue by mgpartssource** [okta/okta-signin-widget#2465]
### Describe the bug

With an OIE and self-hosted setup, app variables are not populating in email templates. But on the Okta hosted widget it works fine. 

Testing with the "Forgot Password" template the "app" VTL variables listed [here](https://developer.okta.com/docs/guides/custom-email/main/#use-vtl-variables) do not populate in the delivered email when the "Forgot Password" flow is initiated from the self-hosted signin-widget.

The variables are populated in the email when the "Forgot Password" flow is initiated from the Okta-hosted sign-on page.

We are setup with an OIE instance and are using the latest versions of the sign-in widget (6.2.0), okta-react (6.4.3) and okta-auth-js (6.3.1).

### What is expected to happen?

When the "Forgot Password" flow is initiated from a self-hosted sign-in widget the ${app.id}, ${app.name} and ${app.label} variables are replaced with their appropriate values in the delivered email.

### What is the actual behavior?

When the "Forgot Password" flow is initiated from a self-hosted sign-in widget the ${app.id}, ${app.name} and ${app.label} variables are not replaced with their appropriate values in the delivered email.

### Reproduction Steps

From a self-hosted sign-in widget configured for OIDC against an application configured in Okta:

1. Click "Need help signing in?"
2. Click "Forgot Password"
3. Enter the email for a user with access to the configured application
4. Click "Reset Via Email"
5. Observe the ${app.id}, ${app.name} are not replaced with their appropriate values in the delivered email.

![forgot password template](https://user-images.githubusercontent.com/29633927/163175136-678f8a99-b17b-4e61-83bc-b5630cc9681e.jpg)

![forgot password](https://user-images.githubusercontent.com/29633927/163175161-06cfe3c0-9028-4535-af9e-6476323596b0.jpg)

![instance](https://user-images.githubusercontent.com/29633927/163175221-83cd5712-f7ff-48b1-87a8-75deae3e9aea.jpg)

The variables are populated when the "Forgot Password" email is initated from the [Okta hosted sign-in page](https://dev-partssource.okta.com/oauth2/v1/authorize?client_id=okta.2b1959c8-bcc0-56eb-a589-cfcfb7422f26&code_challenge=3X_3ubt6ukJlHndP5JCo01tvwbsalF6gGnO6ppbo7sQ&code_challenge_method=S256&nonce=6VgM5gopkOZZBGjFbp67P1hteydboowxDacwJZAH9jWD8UEejeuK4Uk5I4fb9Asz&redirect_uri=https%3A%2F%2Fdev-partssource.okta.com%2Fenduser%2Fcallback&response_type=code&state=lGsrj3aMANkKBnfRI3Ah1tlY5WySOgwVZvOKoFgbQJX8oXGHnqZ9Iw8Dxi7sSCH5&scope=openid%20profile%20email%20okta.users.read.self%20okta.users.manage.self%20okta.internal.enduser.read%20okta.internal.enduser.manage)

![okta hosted](https://user-images.githubusercontent.com/29633927/163175727-4f867597-3d8e-4b34-a46a-721e3b8b137b.jpg)

### SDK Versions

sign-in widget (6.2.0)
okta-react (6.4.3)
okta-auth-js (6.3.1).

### Execution Environment

https://dev-partssource.okta.com/ and a hosted sign-in widget on an internal test server

**Comment by jaredperreault-okta** [comment]
@mgpartssource Thank you for the detailed report! Unfortunately I don't believe this is an issue with the Widget itself, rather an issue with the Okta service (which the Widget uses under the hood). You can reach out to [Okta Support](https://support.okta.com/help/s/?language=en_US). They should able to assist you with this matter

**Comment by rasudha** [comment]
We are seeing the same issue as well. Did this get resolved? @mgpartssource

**Comment by mgpartssource** [comment]
@rasudha Yes, the issue was resolved after contacting Okta Support.

**Comment by rasudha** [comment]
Thanks @mgpartssource - Would you mind letting me know what the resolution was or how was it implemented later?
