### ISSUE TITLE
Upgrade from 6.2.1 to 6.3.x causes typescript error in OktaSignIn() creation.

### ISSUE THREAD

**Issue by jcwchriswalker** [okta/okta-signin-widget#2510]
### Describe the bug

After moving from SignIn widget 6.2.1 to 6.3.0, Typescript throws this error:
```
ERROR in C:\auth.ts(30,17)
      TS2322: Type '{ pkce: true; issuer: string; scopes: string[]; tokenManager: { autoRenew: true; }; }' is not assignable to type 'AuthParams'.
  Object literal may only specify known properties, and 'pkce' does not exist in type 'AuthParams'

```
The object setup:
```
this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
            clientId: "xxxxxx",
            baseUrl: 'https://dev-xxxxxxx.okta.com',
            logo: this.TYFSettings.ApplicationPath + '/css/images/tyf logo.png',
            redirectUri: this.redirectUrl,
            redirect: 'always',
            authParams: {
                pkce: true,
                issuer: "https://dev-xxxxxx.okta.com/oauth2/default",
                scopes: ['openid', 'email', 'profile'],
                tokenManager: {
                    autoRenew: true
                }
            },
            idps: [
                { type: 'google', id: 'xxxxxxxxxx' }
            ],
            features: {
                registration: true
            }
        });

```

### What is expected to happen?

No typescript error 

### What is the actual behavior?

Typescript flags the error described in the description section

### Reproduction Steps

See description for the OktaSignin creation used

### SDK Versions

@okta/okta-signin-widget: "6.3.0"

### Execution Environment

Using Typescript 4.6.3

**Comment by jcwchriswalker** [comment]
@oleksandrpravosudko-okta 
OK- I removed **pkce** and typescript then flagged the **issuer** property which is the next one on my definition. Note the error in my initial post where it says AuthParams and not authParams. (upper case A).

**Comment by oleksandrpravosudko-okta** [comment]
It looks like `okta-auth-js` typings are not available as it is currently a dev dependency - this will likely be fixed in the next patch release. To work around it for now, please try installing `okta-auth-js`.

**Comment by jcwchriswalker** [comment]
I installed okta-auth-js and received another error:
 ```
TS2345: Argument of type '{ el: string; clientId: string; baseUrl: string; logo: string; redirectUri: string; redirect: string; authParams: { pkce: true; issuer: string; scopes: string[]; tokenManager: { autoRenew: true; }; }; idps: { ...; }[]; features: { ...; }; }' is not assignable to parameter of type 'WidgetOptions'.
  Object literal may only specify known properties, and 'redirect' does not exist in type 'WidgetOptions'.
```

I will go back to signin widget 6.2.1 and wait for the next 6.3 patch release to test. Thanks for your quick responses and help.

**Comment by denysoblohin-okta** [comment]
Looks like [redirect](https://github.com/okta/okta-signin-widget/blob/9abc9f2279947ceec1b07de84116bfdbbb5a8904/src/models/Settings.js#L41) option is missing in TS defnition https://github.com/okta/okta-signin-widget/blob/master/src/types/options.ts

**Comment by jcwchriswalker** [comment]
@aarongranick-okta I upgraded to version 6.3.5 and it now compiles after I removed the `redirect` option and used the `showSigninAndRedirect()` per your recommendation.
Thanks
