### ISSUE TITLE
Cannot get session (me) using custom domain url

### ISSUE THREAD

**Issue by jcwchriswalker** [okta/okta-signin-widget#2521]
### Describe the bug

Using okta-signin-widget 6.2.1, we need to address the blocked 3rd party cookie described in this
[FAQ](https://support.okta.com/help/s/article/FAQ-How-Blocking-Third-Party-Cookies-Can-Potentially-Impact-Your-Okta-Environment?language=en_US).
We set the custom domain name to be login._mycompanyname_.com and registered it. We confirmed the DNS registration by pointing the browser to this new url and see the Okta login screen as expected.

The FAQ then instructs one to change the signin widget configuration to use the custom domain name which we did here:
```
this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
            clientId: "xxxx",
            baseUrl: 'https://login.comanyname.com',
            logo: this.Settings.ApplicationPath + '/css/images/tyf logo.png',
            redirectUri: this.redirectUrl,
            redirect: 'always',
            authParams: {
                pkce:true,
                issuer: "https://login.companyname.com/oauth2/default",
                scopes: ['openid', 'email', 'profile'],
                tokenManager: {
                    autoRenew: true
                }
            },
            idps: [
                { type: 'google', id: 'xxx' }
            ],
            features: {
                registration: true
            }
        });
```

Previously the baseURL and issuer properties used our dev test account dev-xxxx.okta.com.

When testing the login with the new domain, the session GET request:
https://login._companyname_.com/api/v1/sessions/me  returns a 404 resource not found. Switching back to the dev-xxxxx.okta.com will return the session information.  
I feel as if I am missing an additional step in the Okta console to get this working but have not seen any documentation saying as such.

### What is expected to happen?

To see the session data when doing  GET on https://login._companyname_.com/api/v1/sessions/me.

### What is the actual behavior?

 GET returns an http 404

### Reproduction Steps

See initial description

### SDK Versions

okta-signin-widget 6.2.1

### Execution Environment

Chrome Windows/Mac/IOS Safari Mac/IOS

**Comment by aarongranick-okta** [comment]
@jcwchriswalker Let's verify a few details.

- login.companyname.com - this is the URL of your Okta-hosted custom domain. If you navigate here, you should be able to login and see your Okta enduser dashboard page. https://developer.okta.com/docs/guides/custom-url-domain/main/
You should not need to change the widget config on this page.

- app.companyname.com - this is the URL where your app is hosted and using an embedded instance of the Okta SignIn widget. https://github.com/okta/okta-signin-widget/blob/master/docs/classic.md#embedded-self-hosted
This instance should be configured to use `login.companyname.com`. I've simplified your config:

```
this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
            issuer: "https://login.companyname.com/oauth2/default",
            clientId: "xxxx",
            logo: this.Settings.ApplicationPath + '/css/images/tyf logo.png',
            redirectUri: this.redirectUrl,
            scopes: ['openid', 'email', 'profile'],
            idps: [
                { type: 'google', id: 'xxx' }
            ],
            features: {
                registration: true
            }
        });
        
 this.signin.showSigninAndRedirect()
```

**Comment by jcwchriswalker** [comment]
Aaron, another update which might help. After using the simplified config you supplied, I could not login with my google account on any browser, not just the browsers that block the 3rd party cookies. Only when I re-added the authParams {} was I able to login using my google ID. I did this config based on a previous issue I created: #2404

**Comment by jcwchriswalker** [comment]
@aarongranick-okta 
It redirects to google, I enter my 2Fa then it redirects back to my site. Which is what I want.

**Comment by jcwchriswalker** [comment]
@aarongranick-okta - I have been doing a side by side compare of signing in with my Google ID vs my okta dev id. 
In the Google ID flow, I see  https://login._companyname_.com../authorize? request. Right after that I see the accounts.google.com/.o/oauth2/auth? request with a redirect_uri query string pointing to https://dev-xxxxx.okta.com/oauth2/v1/authorize/callback

I am thinking that redirect_uri querystring parameter in the accounts.google.com request should be using the login._companyname_.com and not the dev-xxxxx.okta.com to keep the browser from stripping off the 3rd party cookie which is the sid (session id?) which in turn causes the /sessions/me to return a 404.

Does that make sense?

**Comment by jcwchriswalker** [comment]
@aarongranick-okta - DO you have any ideas on this problem? Should I close this issue and open it on another repository (like auth-js). Another idea would be for me to give you credentials both okta assigned and gmail to see it for yourself.

**Comment by jcwchriswalker** [comment]
Reopening with a better description of this bug.
