### ISSUE TITLE
Remove fibers dependency

### ISSUE THREAD

**Issue by jrodrigop** [okta/okta-signin-widget#2538]
### Describe the feature request

Updating Widget from 5.7 to 6.3, found that we can not build easy as it was, doing some exploration:

- The author of this project recommends you avoid its use if possible.
- Since this requires node-gyp this adds, for windows users this causes missing dependencies, which make no sense: python and windows build tools

https://github.com/okta/okta-signin-widget/blob/56601bc1ec2f52ed6d89024b2a73bb5c8b53c793/package.json#L129

### New or Affected Resource(s)

Tracked this issue since version 5.12

**Comment by jaredperreault-okta** [comment]
@jrodrigop Thanks for submitting this feature request. I will discuss this with the team

**Comment by FerminAMC** [comment]
+1
A quote from the author of the library -
> NOTE OF OBSOLESCENCE -- The author of this project recommends you avoid its use if possible. The original version of this module targeted nodejs v0.1.x in early 2011 when JavaScript on the server looked a lot different. Since then [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), and [Generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) were standardized and the ecosystem as a whole has moved in that direction.

**Comment by shuowu-okta** [comment]
Fix has been merged
