### ISSUE TITLE
Sign-In Process hangs in an Angular app

### ISSUE THREAD

**Issue by mraible** [okta/okta-signin-widget#268]
Noted in [this blog post](https://developer.okta.com/blog/2017/03/27/angular-okta-sign-in-widget) from March.

When using the Sign-In Widget in an Angular app, you sometimes have to click on the page for the login process to complete. Otherwise, the process seems to hang. Clicking anywhere in the browser window seems to solve this problem. I’m not sure why.

**Comment by santhoshbalakrishnan** [comment]
@mraible Similar to what was mentioned in https://github.com/okta/okta-signin-widget/issues/247, this can be solved my manually triggering the change detector in Angular and letting the view know that the variable has changed. Clicking anywhere on the browser triggered this for you, which is why the view changes immediately.

```JavaScript
import { ..., ChangeDetectorRef } from '@angular/core';
...
constructor(private okta: Okta, private changeDetectorRef: ChangeDetectorRef) {
    this.oktaSignIn = okta.getWidget();
}
...
  showLogin() {
    this.oktaSignIn.renderEl({el: '#okta-login-container'}, (response) => {
      if (response.status === 'SUCCESS') {
        this.user = response.claims.email;
        // Let angular know that model changed.
        this.changeDetectorRef.detectChanges();
      }
    });
  }
```

**Comment by mraible** [comment]
@santhoshbalakrishnan Can you please re-open this issue? I wrote a [new example](https://github.com/oktadeveloper/okta-kotlin-typescript-notes-example) and this behavior still exists. The `this.oktaSignIn.renderEl` is in an `@Injectable` - [okta.service.ts](https://github.com/oktadeveloper/okta-kotlin-typescript-notes-example/blob/master/client/src/app/shared/okta/okta.service.ts), so I'm unable to inject a `ChangeDetectorRef`. I can inject an `ApplicationRef`, but this only triggers observables to fire and doesn't actually change to UI. 

The app is configured with Okta settings for my account. Contact me on HipChat if you'd like me to provide credentials for you to login. Otherwise, you'll need to change settings in `okta.service.ts` and [server/src/main/resources/application.properties](https://github.com/oktadeveloper/okta-kotlin-typescript-notes-example/blob/master/server/src/main/resources/application.properties).

**Comment by lboyette-okta** [comment]
@mraible can we see if this is still the case on `2.5.0`?

**Comment by mraible** [comment]
@lboyette-okta Yes, it still happens.

**Comment by fehrinjt** [comment]
I am also seeing this issue. It happens all the time for me, but is fixed with any mouse movement (not moving the mouse just causes the widget to stay in its loading/waiting spinning state). I am also injecting my okta code via a service so ChangeDetectorRef doesn't work. 
I have also tried putting a timer on my login component to call detectChanges every 100ms, but that doesn't fix it either. 

I have also tried using ApplicationRef.tick() from my service to no avail.

**Comment by jmelberg-okta** [comment]
@fehrinjt & @mraible This appears to be a known issue with Zone.js and RxJS, as the `subscribe` event isn't picked up by Zone.js.

There is an open PR for [rxjs here](https://github.com/ReactiveX/rxjs/pull/2266), and discussions around workaround [here](https://github.com/angular/zone.js/issues/304), [here](https://github.com/angular/angular/issues/7381), and [here](https://github.com/angular/angular/issues/16343).

I was able to successfully get the change detector to register by updating the `subscribe` call to include:

```typescript
YOUR-OBSERVABLE.subscribe(user => {
  this._ngZone.run((isAuth) => {
    // Bind value to UI
    this.user = user;
  });
});
```

The entire controller (using @mraible's example):

```typescript
import { Component, OnInit, NgZone } from '@angular/core';
import { OktaAuthService } from './shared/okta/okta.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'My Notes';
  user;

  constructor(public oktaService: OktaAuthService, private _ngZone: NgZone) {
  }

  ngOnInit() {
    if (this.oktaService.isAuthenticated()) {
      this.user = this.oktaService.idTokenAsUser;
    }

    this.oktaService.user$.subscribe(user => {
      this._ngZone.run((isAuth) => {
        this.user = user;
      });
    });
  }
}

```

**Comment by fehrinjt** [comment]
@jmelberg-okta  Thanks a ton! Wrapping my relevant code inside of an ngZone.run() appears to have fixed the issue! Thanks!

**Comment by santhoshbalakrishnan** [comment]
Closing out this issue as we have a workaround. Once the rxjs issue is resolved, we won’t need to do this workaround as well.

**Comment by eicheled** [comment]
The code in the example doesn't match what's here. I'm new to this and just trying to get a working example running - can someone help me with what a correct, working fix is? I get "ERROR TypeError: Cannot read property 'subscribe' of undefined at AppComponent.ngOnInit (app.component.ts:35)"

**Comment by mraible** [comment]
@eicheled Are you using one of our examples? If so, which one and can you please provide steps to reproduce the problem?

**Comment by eicheled** [comment]
@mraible I am following the example here https://github.com/oktadeveloper/okta-angular-sign-in-widget-example. There is a link to this issue at the bottom of the article here : https://developer.okta.com/blog/2017/03/27/angular-okta-sign-in-widget. I am experiencing exactly the issue mentioned "You may experience an issue where the sign-in process seems to hang. Clicking anywhere in the browser window seems to solve this problem." The solution posted here does not refer to code from the example I am following, and I was wondering how to adapt this solution to that example.

**Comment by santhoshbalakrishnan** [comment]
@eicheled Have you tried the solution posted in the second comment on this thread? That might help you. https://github.com/okta/okta-signin-widget/issues/268#issuecomment-320107944

**Comment by mraible** [comment]
@jmelberg-okta Regarding the sign-in widget example mentioned by @eicheled, how would you recommend I change `AppComponent`?

```ts
import { Component } from '@angular/core';
import { Okta } from './shared/okta/okta.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  user;
  oktaSignIn;

  constructor(private okta: Okta) {
    this.oktaSignIn = okta.getWidget();
  }

  showLogin() {
    this.oktaSignIn.renderEl({el: '#okta-login-container'}, (response) => {
      if (response.status === 'SUCCESS') {
        this.user = response.claims.email;
      }
    });
  }

  ngOnInit() {
    this.oktaSignIn.session.get((response) => {
      if (response.status !== 'INACTIVE') {
        this.user = response.login
      } else {
        this.showLogin();
      }
    });
  }

  logout() {
    this.oktaSignIn.signOut(() => {
      this.showLogin();
      this.user = undefined;
    });
  }
}
```

**Comment by santhoshbalakrishnan** [comment]
@mraible Would the `ChangeDetectorRef` from my second comment not work?

**Comment by mraible** [comment]
@santhoshbalakrishnan No, I've tried that before.

**Comment by fehrinjt** [comment]
@mraible 
The structure in my application is a little different than the example you showed (my validation is done in a service), but I wrapped everything inside the response.status === 'success' in an ngZone.run. Here is an example applied to the code you posted above. I have not validated that this works in your example though so you'll want to give it a shot:

`import { Component, NgZone } from '@angular/core';
import { Okta } from './shared/okta/okta.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  user;
  oktaSignIn;

  constructor(private okta: Okta, private ngZone: NgZone) {
    this.oktaSignIn = okta.getWidget();
  }

  showLogin() {
    this.oktaSignIn.renderEl({el: '#okta-login-container'}, (response) => {
      if (response.status === 'SUCCESS') {
        this.ngZone.run(() => {
          this.user = response.claims.email;
        });
      }
    });
  }

  ngOnInit() {
    this.oktaSignIn.session.get((response) => {
      if (response.status !== 'INACTIVE') {
        this.user = response.login
      } else {
        this.showLogin();
      }
    });
  }

  logout() {
    this.oktaSignIn.signOut(() => {
      this.showLogin();
      this.user = undefined;
    });
  }
}`

**Comment by santhoshbalakrishnan** [comment]
@eicheled Use the below `app.component.ts`. Confirmed that this works with @mraible 

```
import { Component, ChangeDetectorRef } from '@angular/core';
import { Okta } from './shared/okta/okta.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  user;
  oktaSignIn;

  constructor(private okta: Okta, private changeDetectorRef: ChangeDetectorRef) {
    this.oktaSignIn = okta.getWidget();
  }

  showLogin() {
    this.oktaSignIn.renderEl({el: '#okta-login-container'}, (response) => {
      if (response.status === 'SUCCESS') {
        this.user = response.claims.email;
        this.oktaSignIn.remove();
        this.changeDetectorRef.detectChanges();
      }
    });
  }

  ngOnInit() {
    this.oktaSignIn.session.get((response) => {
      if (response.status !== 'INACTIVE') {
        this.user = response.login
        this.changeDetectorRef.detectChanges();
      } else {
        this.showLogin();
      }
    });
  }

  logout() {
    this.oktaSignIn.signOut(() => {
      this.user = undefined;
      this.changeDetectorRef.detectChanges();
      this.showLogin();
    });
  }
}
```
