### ISSUE TITLE
idx.error.user.not.assigned.to.app property cannot be overriden

### ISSUE THREAD

**Issue by margish** [okta/okta-signin-widget#2690]
### Describe the bug

We are trying to replace the default value for "idx.error.user.not.assigned.to.app" with a custom error instead of the default "User is not assigned to the client application." All other properties replacement are working fine inside the i18n.en{} block except for this one.

### What is expected to happen?

Based on the documents, I should be able to see the replacement test in error field.

### What is the actual behavior?

The default error text shows up.

### Reproduction Steps

add I18n.en{} configs and add "idx.error.user.not.assigned.to.app" key with custom error text value.
When your application has the error "User is not assigned to the client application.", the original error text shows up instead of customized error text.

### SDK Versions

okta/okta-auth-js: 6.5.1
okta/okta-react: 6.4.3
okta/okta-signin-widget: 6.3.2

### Execution Environment

Google Chrome 104.0.5112.79, MacOS 12.5
Firefox 103.0.2, MacOS 12.5

**Comment by bernica** [comment]
Were you able to work around it? I'm trying to translate without success.

**Comment by margish** [comment]
No, we are still having this issue. 
Here are the steps to reproduce:
1. Setup a user in okta and remove their assignment from application.
2. Login using the user credentials to confirm you see the error message "User is not assigned to the client application."
3. In the web app, set the property for i18n.en.idx.error.user.not.assigned.to.app to "My custom error message"
`      i18n: {
        en: {
          'idx.error.user.not.assigned.to.app': 'My custom error message',
        },
      }
`
4. Repeat step 2. We are still seeing the message "User is not assigned to the client application." instead of the expected message "My custom error message"

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
I debugged current response for this error and noticed the key name is `idx.error.code.user_not_assigned`.
Please try it instead

**Comment by margish** [comment]
I gave it a try and idx.error.code.user_not_assigned doesn't work as well. Here is an interesting observation: the default values for `idx.error.code.user_not_assigned` is `You are not allowed to access this app. To request access, contact an admin.` and the default value for `idx.error.user.not.assigned.to.app` is `User is not assigned to this application.`

However, the error message that we are seeing and trying to override is `User is not assigned to the client application.` which is different than both the custom label defaults. 
Also I noticed a unit test in https://github.com/okta/okta-signin-widget/blob/master/test/e2e/features/oidc.feature line 10 has the same message that we are seeing.

**Comment by margish** [comment]
Got it. Thank you.

**Comment by denysoblohin-okta** [comment]
@margish 
Can you upgrade to OIE engine? 
Or do you have a requirement to have localized `access_denied` error in classic engine so we can fix it?

**Comment by margish** [comment]
We are planning on upgrading to OIE.
