### ISSUE TITLE
Languages docs missing

### ISSUE THREAD

**Issue by StateBarofArizona** [okta/okta-signin-widget#274]
The links to the languages details and country are broken in the GitHub description.  The links get 404 errors.  I need to know how to change the text for Forgot Password?

**Comment by rchild-okta** [comment]
@samerfanek-okta, looks like the link was broken with [this change](https://github.com/okta/okta-signin-widget/pull/260), so we'll need to fix that.

@StateBarofArizona the login.properties file moved to the packages directory, [here](https://github.com/okta/okta-signin-widget/blob/master/packages/%40okta/i18n/dist/properties/login.properties).

**Comment by hor-kanchan-okta** [comment]
Fixed in #307
