### ISSUE TITLE
Problem loading the widget when using SystemJs

### ISSUE THREAD

**Issue by alonfixler** [okta/okta-signin-widget#280]
Hi,

I'm using SystemJs 0.19.41 as my module loader and I have a problem loading the okta signin widget. I believe that the problem is quite similar to https://github.com/okta/okta-signin-widget/issues/221.
In my browser console (image attached) I can see that it cannot find view.js file which he searches in the fist js folder. I assume that view.js is already part of the bundled okta-sgin-in.entry.js file.

![image](https://user-images.githubusercontent.com/2629128/29265207-ce633a28-80e8-11e7-8b74-84cdcb52fb2e.png)

Is there anyway to solve it?

Best,

Alon

**Comment by lboyette-okta** [comment]
Hi @alonfixler 

There are two ways to fix your problem:

Change your `config.js` to alias `@okta/okta-signin-widget`:

```javascript
System.config({
  // ...
  map: {
    "@okta/okta-signin-widget": "npm:@okta/okta-signin-widget@YOUR_VERSION/dist/js/okta-sign-in.min.js"
  // ...
});
```

Or, change the way you import `@okta/okta-signin-widget`:

```javascript
var OktaSignIn = require("@okta/okta-signin-widget/dist/js/okta-sign-in.min.js");
```
