### ISSUE TITLE
Path for checkbox-sign-in-widget.png should be relative

### ISSUE THREAD

**Issue by alonfixler** [okta/okta-signin-widget#281]
The paths for both checkbox-sign-in-widget.png and checkbox-sign-in-widget@2x.png should be relative (start with "../") like all other sources declared in other css files.

https://github.com/okta/okta-signin-widget/blob/ca319e69bf7f87dd4cc66688c291f495d110d97b/assets/sass/modules/_forms.scss

**Comment by mraible** [comment]
FWIW, there's a pending PR to fix this: https://github.com/okta/okta-signin-widget/pull/248

**Comment by alonfixler** [comment]
@mraible Sorry, I missed that one. Thanks!

**Comment by dylandechant** [comment]
is this really fixed? we are using 2.1.0 and still have this problem. Thanks!

**Comment by santhoshbalakrishnan** [comment]
@dylandechant The fix went in at https://github.com/okta/okta-signin-widget/commit/b5aff3ea1223cb4dfa063434c755a694ccf6de9e which is after rev up to version 2.2.0( https://github.com/okta/okta-signin-widget/commit/cde73ee2268cb938e828a80793ab904756efb368 )

This should be bundled with the next version update. @mauriciocastillosilva-okta @rchild-okta can tell more about when a version update would be available.
