### ISSUE TITLE
Okta, React + embedded SignIn Widget returning 401 for all login attempts

### ISSUE THREAD

**Issue by Montana** [okta/okta-signin-widget#2811]
### Describe the bug

Any users assigned either to the `Everyone` group or the `Individual` assignments do not work, they return a 401 error according to the Okta logs. 

<img width="788" alt="Screen Shot 2022-09-27 at 4 17 45 PM" src="https://user-images.githubusercontent.com/20936398/192654037-debc277f-05df-4864-b371-425f87c31e87.png">

This is my `App.js` file:

```jsx
const history = useHistory();

  const customAuthHandler = () => {
    history.push('/login');
  };

  const restoreOriginalUri = async (_oktaAuth, originalUri) => {
    history.replace(toRelativeUrl(originalUri || '/', window.location.origin));
  };

return (
<Security>
        oktaAuth={oktaAuth}
        onAuthRequired={customAuthHandler}
        restoreOriginalUri={restoreOriginalUri}
      >
<Switch>
          <Route exact path="/" render={() => <Home />} />
          <Route path="/login" render={() => <Login />} />
          <Route path="/login/callback" component={LoginCallback} />
          <SecureRoute path="/users" render={() => <List />} />
.......
</Switch>
</Security>
);
```

### What is expected to happen?

For the authentication to go through, since there's no policy rules set. 

### What is the actual behavior?

401.

### Reproduction Steps

Exactly explained in my opening problem.

### SDK Versions

@okta1.0 

### Execution Environment

Node

**Comment by jaredperreault-okta** [comment]
Can you provide the initialization of your `oktaAuth` instance? (please omit sensitive fields) as well as the versions of the SDK(s) you're using?

**Comment by AnthonyISS** [comment]
I am experiencing the same exact issue. User can log in to okta dashboard directly and sees the app widget there,  but attempting to log in via the widget I get a 401 with a "You are not allowed to access this app. To request access, contact an admin.". Older version of the widget (5.x) works fine. Okta server is running the new identity engine. 

My package versions are:
"@okta/okta-auth-js": "^7.2.0",
"@okta/okta-react": "^6.7.0",
"@okta/okta-signin-widget": "^7.5.1",

**Comment by Gugic** [comment]
Same behavior here, tried on two different trial okta accounts, widget was working yesterday, and then all of a sudded started to behave like that.

**Comment by Gugic** [comment]
rolling back to 6.9 helped

**Comment by AnthonyISS** [comment]
In my case passing this option to the widget helped restore the previous functionality: 
`useClassicEngine: true`
despite the fact that the widget is running against new Okta Identity Engine.

**Comment by jaredperreault-okta** [comment]
@Gugic do you mind pasting your widget config? (please obfuscate sensitive fields)

**Comment by Gugic** [comment]
it's super basic:

```
    const oktaWidget = new OktaSignIn({
      issuer: `${oktaDomain}/oauth2/default`,
      clientId,
      redirectUri: 'https://localhost:1234/login',
    });
```

Widget is being rendered later through oktaWidget.renderEl as it is react and I need to use ref to avoid re-renders and inject it in react more or less properly. Did not change a thing between 7.6 and 6.9 - same config on both FE and BE.

**Comment by AnthonyISS** [comment]
@jaredperreault-okta The issue is that my Okta org is using the new identity engine (not the classic engine) and the widget still needs to be forced into classicEngine mode to work.

**Comment by AnthonyISS** [comment]
@jaredperreault-okta My org was migrated to OIE. I've already reached out to Okta Support regarding this and they were the ones that suggested using classic mode on the widget but they didn't provide an explanation why this is happening.

**Comment by AnthonyISS** [comment]
@jaredperreault-okta We are embedding it ourselves inside React app.

**Comment by jaredperreault-okta** [comment]
@AnthonyISS Since you're embedding the SIW, you'll need to make sure `Interaction Code Flow` is enabled on your:

1. Org (Settings > Account > Embedded widget sign-in support)
2. Application  (Applications > {App} > General Settings)
3. Auth Server (Security > Api > {Server} > Access Policies Tab)
This link should help: https://developer.okta.com/docs/guides/implement-grant-type/interactioncode/main/#verify-that-the-interaction-code-grant-type-is-enabled

**Comment by AnthonyISS** [comment]
@jaredperreault-okta Thank you so much! That last one (#3) was it! Somehow post migration Interactive was disabled in Access Policy. After enabling it widget started authenticating in its proper mode (OIE).

**Comment by Gugic** [comment]
Same here, enabling interaction code on Auth Server helped me as well, it's been enabled in other places.

Weird thing there is that it's been working in my testing about three days ago, I've been getting my okta access tokens, and then all of a sudden stopped.
