### ISSUE TITLE
Can't GET sign in widget from CDN

### ISSUE THREAD

**Issue by mirok99** [okta/okta-signin-widget#2916]
### Describe the bug

Can't import Okta sign in widget from CDN.

### What is expected to happen?

Expected sign in widget to be imported from CDN.
<script src="https://global.oktacdn.com/okta-signin-widget/7.0.1/js/okta-sign-in.classic.min.js" type="text/javascript"></script>

### What is the actual behavior?

Get 404 error.
![image](https://user-images.githubusercontent.com/81921071/201344162-4174d659-a32a-48a3-bfaa-a6ca5addd285.png)

### Reproduction Steps

Attempt to get script from CDN

### SDK Versions

7.0.0

### Execution Environment

Firefox 106.0.5
HTML/JS

**Comment by aarongranick-okta** [comment]
@mirok99 Thanks for bringing this to our attention! The assets for 7.0.1 are now on the CDN.
