### ISSUE TITLE
Sign-In Widget doesn't work with a server-rendered JS framework

### ISSUE THREAD

**Issue by mraible** [okta/okta-signin-widget#295]
I tried to create a [Nuxt.js](https://nuxtjs.org/) application and integrate the Sign-In Widget. Unfortunately, it does not work. It'd be great if this widget could work with frameworks like Nuxt.js and Angular Universal (now part of Angular core).

![Window is not defined](https://user-images.githubusercontent.com/17892/30300163-6eaea4f8-9710-11e7-899f-c5d899640239.png)

**Comment by lboyette-okta** [comment]
One of the many reasons this doesn't work is okta-auth-js depends on window APIs. This will require quite a bit of refactoring.

**Comment by Jason54** [comment]
Hi Iboyette-okta, is there a timeline for refactoring or maybe a temp fix?

**Comment by lboyette-okta** [comment]
There's not, but we'll take your request as a 👍on the feature (you may also want to add a real 👍on this issue)!

Which framework are you using to do server-side rendering?

**Comment by Jason54** [comment]
Hi Iboyette-okta, thank you for your response. I'm using WebPack or as mentioned above Angular Universal.

**Comment by alisonhall** [comment]
This is still a problem, and I can't use it on our React.js SPA with Webpack.

**Comment by mraible** [comment]
@alisonhall I've talked with internal teams about this and there are currently no plans to support server-side rendering in any of our SDKs, including the Sign-In Widget. 

The good news is Okta's API is based on OAuth and OIDC, so you could likely use another library that supports these standards.

**Comment by GonzaloCalandria** [comment]
Hello everyone, do we have any news on this issue?

**Comment by swiftone** [comment]
@GonzaloCalandria - Thanks for the question.  Unfortunately, the current case remains as above: No current plans for server-side rendering, but standards-based OAuth/OIDC is supported.

We are regularly considering customer needs in setting our plans and priorities, so talk with your support reps to discuss your particular plans and needs.

**Comment by robertabramski** [comment]
If anyone is having trouble integrating this with Angular SSR (in my case, app-shell), it can be accomplished by hiding your import of `OktaSignIn` inside a `isPlatformBrowser` conditional by using Node require function in instead of an import. You may need to add `"node"` to your types array in tsconfig or declare require as a var.

```
declare var require: any;
let OktaSignIn = require('@okta/okta-signin-widget');
this.widget = new OktaSignIn({/* config */});
```
