### ISSUE TITLE
RememberMe checkbox is not retaining username/password on cordova-ios app

### ISSUE THREAD

**Issue by Amrit-Bend** [okta/okta-signin-widget#3001]
### Describe the bug

I'm using the okta-signin-widget/5.16.1 component to log into my website. Remember me functionality doesn't work on iOS devices (using Cordova) but works fine on below platform :
-  Chrome/Firefox/Safari, 
-  Cordova App on Android

### What is expected to happen?

When a user selects a "RememberMe" checkbox on a login screen, widget should prefill the username and password data on next login.

### What is the actual behavior?

When a user selects a "RememberMe" checkbox on a login screen, widget doesn't prefill username and password data on next login.

### Reproduction Steps

Login with rememberMe checkbox selected on cordova ios app.

### SDK Versions

[okta-signin-widget@5.16.1]

### Execution Environment

Cordova platform: iOS
iOS version: 15.7.1

**Comment by jaredperreault-okta** [comment]
The 'rememberMe' feature writes a cookie in order to remember the last identifier (username) entered. I'm not familiar with Cordova iOS apps, but it is possible your app does not have permissions to write cookies?

Note: This feature does not remember previously entered passwords, only usernames
