### ISSUE TITLE
Cannot  import '@okta/okta-signin-widget/dist/css/okta-sign-in.min.css'

### ISSUE THREAD

**Issue by jcwchriswalker** [okta/okta-signin-widget#3033]
### Describe the bug

When migrating to signin-widget 7.x,  Compiling with typescript 4.7.4 / Webpack  5.75.0 produces the following error:
`
ERROR in ./typescript/Homepage/HomePage_View.ts 6:0-64
Module not found: Error: Package path ./dist/css/okta-sign-in.min.css is not exported from package C:\TYF\node_modules\@okta\okta-signin-widget (see exports field in C:\TYF\node_modules\@okta\okta-signin-widget\package.json)
`
This error does not occur using signin-widget 6.9.0

### What is expected to happen?

This module should be found and resolved

### What is the actual behavior?

See error in the describe the bug section

### Reproduction Steps

Include this line in a ts file:
`
import '@okta/okta-signin-widget/dist/css/okta-sign-in.min.css';
`

With Okta-signin-widget 6.9.0 No error will be produced. However with Okta-signin-widget 7.x, an error will be  thrown.

### SDK Versions

@okta/okta-signin-widget: 6.9.0,
@okta/okta-signin-widget: 7.0.0
Typescript 4.74
webpack 5.75.0
css-loader 6.71.0

### Execution Environment

Typescript 
Windows OS

**Comment by denysoblohin-okta** [comment]
Please use @okta/okta-signin-widget version 7.1.0+ and use
```js
import '@okta/okta-signin-widget/css/okta-sign-in.min.css';
```
See [Using the npm module](https://github.com/okta/okta-signin-widget#using-the-npm-module) in readme

**Comment by jcwchriswalker** [comment]
Installed @okta/okta-signin-widget version 7.2.1 (Latest as of today), changed import statement per previous post, verified that my tsconfig.json had allowSyntheticDefaultImports : true.

The webpack compile no longer shows the error. Thank you
