### ISSUE TITLE
Typescript Error when compiling using 7.2.0+

### ISSUE THREAD

**Issue by jcwchriswalker** [okta/okta-signin-widget#3074]
### Describe the bug

When upgrading from signin-widget 7.1.3, okta-auth-js 7.1.1  to  signin-widget 7.2.0, okta-auth-js 7.2.0 a typescript error is generated:

 TS2322: Type 'OktaAuth' is not assignable to type 'WidgetOktaAuthInterface'.
  The types of 'token.getWithRedirect' are incompatible between these types.
    Property '_setLocation' is missing in type 'GetWithRedirectFunction' but required in type 'GetWithRedirectAPI'.

I have tried later levels of the signin widget up to 7.3.0 with the same results

 

### What is expected to happen?

No typescript error

### What is the actual behavior?

See error message in the description

### Reproduction Steps

```
import { OktaSignIn } from '@okta/okta-signin-widget';
import { OktaAuth,OktaAuthOptions,AccessToken,IDToken,UserClaims,TokenParams } from '@okta/okta-auth-js';
```
```
    public signIn: OktaSignIn;
    public authClient: OktaAuth;
```

```
this.authClient = new OktaAuth({
            redirectUri: this.redirectUrl,
            clientId: this.ClientId,
            pkce: true,
            issuer: this.Issuer,
            scopes: ['openid', 'email', 'profile']
            
        });
        this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
             clientId: this.ClientId,
            redirectUri: this.redirectUrl,
            useClassicEngine: true,
            authClient: this.authClient,
            idps: [
                { type: 'google', id: this.GoogleIDPToken }
            ],
            features: {
                registration: false,
                rememberMe: true,            }
        });
```

### SDK Versions

**Package.json**

Works
```
   "@okta/okta-signin-widget": "7.1.3",
    "@okta/okta-auth-js":"7.1.1",
```
Does not work
```
    "@okta/okta-signin-widget": "7.2.0",
    "@okta/okta-auth-js":"7.2.0",
```

### Execution Environment

Windows 10,
Typescript 4.7.4

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
`@okta/okta-signin-widget` has dependency from `@okta/okta-auth-js ~7.0.0`

`okta-auth-js 7.2.0` introduced [change](https://github.com/okta/okta-auth-js/commit/2c92f04e2703f5eae10ff84fc4f46bbbcd500777#diff-8ddaf7193f379fe639e68e1ea2b199007a05e243a823be0a08ae616a779f6be6R65) for `getWithRedirect` (`_setLocation ` property has been removed).

Until `okta-signin-widget` is updated to use latest `okta-auth-js`, you can use workaround to force dependency resolutions (eg. [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) in yarn) 

Internal ref: OKTA-575801

**Comment by jcwchriswalker** [comment]
@denysoblohin-okta - Thanks

Compiles with `@okta/okta-signin-widget 7.3.0` and `@okta/okta-auth-js 7.0.1`
