### ISSUE TITLE
Widget returning 401 on MFA request

### ISSUE THREAD

**Issue by wpuricz** [okta/okta-signin-widget#3102]
### Describe the bug

Recently, I am getting an error saying that I am not allowed access to the app. This is using the Okta signin widget, I've used 6.7, 6.9, 7.0, 7.3.1. meanwhile doing redirection works fine. Whenever its gets to the answer api call this is where the failure is. The application is setup for 2FA. Putting in the user, and password, get me through the first screen but it won't verify SMS code (which is correct). The application is setup as a SPA using Interaction Code, and the app is using useInteractionCodeFlow: true. This is using the sample code for this widget (https://github.com/okta/samples-js-react) (custom_login).

In addition to the react sample provided by Okta, my previous sample configured for our company's Okta environment, and our application are also seeing the same error 

### What is expected to happen?

The user should enter the correct 2FA code and they should be redirected to the redirect uri

### What is the actual behavior?

The user enters the correct 2FA code, but an error on the challenge answer is received "You are not allowed to access this app. To request access, contact an admin.". 

### Reproduction Steps

1. Create a SPA app in Okta with the default settings. Add Interaction Flow. By default, the authentication policy should be set to any two factors. Make sure this is the case
2. Pull the react sample repo and use the custom login app.https://github.com/okta/samples-js-react
3. Enter your Okta credentials for:
export ISSUER=
export CLIENT_ID=
export USE_INTERACTION_CODE=
4. Run the project, and attempt logging in. You should see the following error in the screenshot attached.
<img width="1335" alt="Screen Shot 2023-02-24 at 2 52 39 PM copy" src="https://user-images.githubusercontent.com/8170231/221282608-10b7a7e5-172d-4547-a4aa-66c8d56ec9d8.png">
<img width="366" alt="Screen Shot 2023-02-24 at 3 09 18 PM" src="https://user-images.githubusercontent.com/8170231/221282614-31f289e4-c119-449a-9dcd-127ec88abf50.png">

### SDK Versions

Have tried multiple versions 7.3.1, 6.7, 6.9, 7.0

### Execution Environment

Chrome Browser on localhost

**Comment by denysoblohin-okta** [comment]
Could you please try reaching out to support@okta.com ?
It might be a configuration issue with org/app/policies.

**Comment by wpuricz** [comment]
Thanks.

Seems like the sample works now with some modified config on the server. I did need to upgrade to 7+ Okta-signin-widget for it to work.

**Comment by shuowu-okta** [comment]
Glad you have it figured out, let us know if you run into any other problems. Close this issue for now.
