### ISSUE TITLE
Allow disablement of autocomplete on login fields

### ISSUE THREAD

**Issue by literallyjustroy** [okta/okta-signin-widget#3130]
### Describe the feature request

Some Web Security Scanners (like the Qualys - Web Application Scans) point out that the login fields (which are sensitive fields) allow autocompleting. These scanners consider this to be a vulnerability:

```
Sensitive form field has not disabled autocomplete
Control ID: 150112
CWE(s): CWE-200

An HTML form that collects sensitive information does not prevent the browser from prompting the user to save the populated values for later reuse. 
Autocomplete should be turned off for any input that takes sensitive information such as credit card number, CVV2/CVC code, U.S. social security number, etc.
```

Supporting autocomplete is a feature in most cases, however, the ability to disable this feature for security-focused applications would be useful.

Can we get a feature config option to disable autocomplete across the input fields?

```
autocomplete="off"
```

### New or Affected Resource(s)

All sensitive (username/password/etc.) inputs

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this request.
Internal ref: OKTA-587048

**Comment by jaredperreault-okta** [comment]
@literallyjustroy Do you have examples of inputs which were flagged? The few I looked at have the correct `autocomplete` value

Secondly, are you using Classic engine or OIE? And what version of the SIW are you using?

**Comment by literallyjustroy** [comment]
@jaredperreault-okta From my companies login page which uses the OktaSigninWidget:
```html
<input type="text" placeholder="" name="username" id="okta-signin-username" value="" aria-label="" autocomplete="username" aria-required="true" required="" class="" aria-describedby="input-container-error48" aria-invalid="true">
```

This **does** have an autocomplete attribute, however, it is set to "username" (which is correct if you want autocompletion) not "off" (which is correct if you want autocomplete disabled).

**Comment by jaredperreault-okta** [comment]
@literallyjustroy can you go to `https://{your org domain}.okta.com/.well-known/okta-organization` and tell me if `pipeline` = `'idx'`

Do you happen to know if you're embedding the SIW or using the Custom Domain feature?

**Comment by literallyjustroy** [comment]
Pipeline is v1. 

We're embedding the sign-in widget into our own angular page.

**Comment by jaredperreault-okta** [comment]
I will pass your request onto product, in the meantime you should be able to use the `afterRender` event to manipulate the DOM to set the `autocomplete` properties accordingly as a workaround

Docs: https://github.com/okta/okta-signin-widget/blob/master/docs/classic.md#afterrender

**Comment by literallyjustroy** [comment]
This works until you add an IDP Routing Rule, where the password field isn't displayed until you end up a the default routing rule match, then it seems like it isn't running the afterRender event again, but the password field gets inserted into the html at this point.

So this code works with no Routing Rules (default username/password) but doesn't remove the autocomplete after the new password field is injected with Routing Rules:
```typescript
this.widget.on('afterRender', this.removeSensitiveAutocomplete);

private removeSensitiveAutocomplete() {
  const passwordFields = document.querySelectorAll('input[type="password"]');

  passwordFields.forEach(field => {
    field.setAttribute('autocomplete', 'off');
  });
}
```

**Comment by glenfannin-okta** [comment]
@literallyjustroy Following up here as we are looking into this, we just wanted to confirm, do you need this for v1 (a.k.a Classic / authn) or OIE? I noticed [this](https://github.com/okta/okta-signin-widget/issues/3252) post from you that suggests you may be using the OIE Sign-in Widget so we just wanted to verify which version of the widget this request is needed for. 

Thank you!

**Comment by literallyjustroy** [comment]
We started the OIE upgrade process but haven't finished it yet, and it may be put off a few more months. So we are currenly on the Classic Engine.

**Comment by glenfannin-okta** [comment]
@literallyjustroy Got it, so we will start this in Classic and cascade to OIE. Will update once this is completed. Thank you!

**Comment by glenfannin-okta** [comment]
@literallyjustroy 👋 Hello again, one last question, you mentioned [here](https://github.com/okta/okta-signin-widget/issues/3130#issuecomment-1597679333) that the afterRender hook did not work with IDP routing rules in place. Can you share how you set up the IDP rules (you can remove any sensitive information), we just want to test our changes against this scenario to ensure it resolves the request (i.e. did you use [these](https://github.com/okta/okta-signin-widget/blob/master/docs/classic.md#idp-discovery) instructions to set up the IDP discovery in your app). 

Also please let us know if you are using the Sign-in Widget as self hosted or if it is Okta-hosted.  

Thank you!

**Comment by literallyjustroy** [comment]
@glenfannin-okta IDP routing rules mapping to an IDP (Azure AD) matching on domain. We are using a self-hosted sign-in widget and did enable idpDiscovery via the feature (since we're using the Classic Engine).

**Comment by glenfannin-okta** [comment]
@literallyjustroy Awesome thank you so much for confirming! If you would like, you can verify the update from [this](https://github.com/okta/okta-signin-widget/tree/OKTA-587048-disable-autocomplete) branch, you would only need to set `features.disableAutocomplete` to `true`. 

Let me know if you have any questions 🙏
