### ISSUE TITLE
No longer receiving users actual name in token

### ISSUE THREAD

**Issue by kylefoley** [okta/okta-signin-widget#314]
Hello,

This just stopped working for me yesterday, but when a user logs in, they no longer get their actual name from Okta. 

Here's how I'm defining my authParams 
`authParams: {`
        `issuer: 'https://dev-xxxxxx.oktapreview.com/oauth2/xxxxxxxxxxxxx',`
        `responseType: ['id_token', 'token'],`
        `scopes: ['openid', 'email', 'profile']`
      `},`

And when I get my tokens back, `Claims` does not show the users actual name anymore. 

I have tried with multiple users with no luck. 

Any advice? Thanks!

**Comment by hor-kanchan-okta** [comment]
@kylefoley Okta is investigating the issue.

**Comment by hor-kanchan-okta** [comment]
@kylefoley The issue has been identified and the fix is on the way.

**Comment by hor-kanchan-okta** [comment]
@kylefoley The fix is deployed.

**Comment by cmckni3** [comment]
Anyway to get the profile information back with `session.get`?

**Comment by hor-kanchan-okta** [comment]
@cmckni3 The `session.get` doesn't contain the profile information.
There is a different API to get profile for the current user `/api/v1/users/me`.
https://developer.okta.com/docs/api/resources/users#get-current-user
Will that work for you?

**Comment by cmckni3** [comment]
@hor-kanchan-okta Yes, I saw that endpoint but didn't know if the widget supported it.

**Comment by matikups** [comment]
The widget supports it?

I happen to not be able to call directly to the API due to a CORS problem (I checked that the domain it's on Okta. The login works, with only get me the e-mail and the userId.

I need at least the name. If it's possible, also the avatar of the user.

**Comment by cmckni3** [comment]
I switched to okta oidc. https://github.com/okta/okta-oidc-js

**Comment by gregl83** [comment]
@matikups, were you able to solve both the CORS issue as well as fetching a user's data via `v1/users/me`?

I've tried using both the **id_token** and the **access_token** without any success. I keep hitting getting "Invalid token provided".
