### ISSUE TITLE
NotSupportedError: ReadableStream uploading is not supported

### ISSUE THREAD

**Issue by jchabotamica** [okta/okta-signin-widget#3239]
### Describe the bug

Receiving this error on the latest okta-signin-widget npm module:
"NotSupportedError: ReadableStream uploading is not supported"

This occurs on Safari browsers on version 15 or older.

Reverting to version 7.5.2 fixed the issue.

### Reproduction Steps

Install okta-signin-widget 7.6.0
Try to login with Safari browser version 15 or older.

### SDK Versions

@okta/configuration-validation: ^1.1.0 => 1.1.0 
    @okta/okta-auth-js: ^7.3.0 => 7.3.0 
    @okta/okta-react: ^6.7.0 => 6.7.0 
    @okta/okta-signin-widget: 7.6.0 => 7.6.0

**Comment by jaredperreault-okta** [comment]
@jchabotamica did you close this issue because you have a work around or you no longer think this is a bug?
