### ISSUE TITLE
png woff ttf assets not found when initializing widget

### ISSUE THREAD

**Issue by jcwchriswalker** [okta/okta-signin-widget#3256]
### Describe the bug

When creating the widget, the baseUrl property value seems to be ignored, or not used, when creating references to .png, .woff and .ttf files packaged by the signin widget.
The application resides (on my machine) http://localhost/abc using IIS.

When creating the widget:
```
this.authClient = new OktaAuth({
            redirectUri: this.redirectUrl,
            clientId: this.ABCSettings.ClientId,
            pkce: true,
            issuer: this.ABCSettings.Issuer,
            scopes: ['openid', 'email', 'profile'],
            
            
        });
  this.signIn = new OktaSignIn({
            el: '#signinwidgetcontainer',
            logo: this.ABCSettings.ApplicationPath + '/css/images/abc logo.png',
            logoText: 'My App',
            clientId: this.settings.ClientId,
            redirectUri: this.redirectUrl,
            useClassicEngine: true,
            authClient: this.authClient,
            baseUrl: this.ABCSettings.ApplicationPath,
            idps: [
                { type: 'google', id: this.ABCSettings.GoogleIDPToken }
            ],
            features: {
                registration: false,
                rememberMe: true,            }
        });       
```

When executed, 6 files are referenced, such as the Google logo as a png file for the widget. However the references are http://localhost/js/c357e3c0ce3a6ad6d0b8.png but they should be http://localhost/abc/js/c357e3c0ce3a6ad6d0b8.png. While I do not see the baseUrl property documented, I do see it defined in  options.ts file in the repository so I tried that with no success.

### Reproduction Steps

Using IIS, create an application called ABC so that the reference to the base url will be http://localhost/ABC vs. http://localhost.

Add the code found in the description and then note the 404 errors in the developertools section (if using chrome)

### SDK Versions

- asp.net 7
- vanilla js using typescript 5
- @okta/okta-signin-widget: 7.6.1
- @okta/okta-auth-js: 7.0.2
- Browser Chrome

**Comment by jcwchriswalker** [comment]
@jaredperreault-okta . Thank you for the quick reply. I did see that in the documentation earlier. That particular section appears to address only the language files per the documentation and I did try it before. I just tried it again and still received the 404 for those 6 files in question.

**Comment by denysoblohin-okta** [comment]
What are those 6 files?
If you are talking about assets like [this](https://github.com/okta/okta-signin-widget/blob/master/assets/img/icons/login/google_logo.png), they are referenced in CSS, not JS
https://github.com/okta/okta-signin-widget/blob/1692040c391dcf2af2fad5418f945c716058ec36/assets/sass/modules/_btns.scss#L263-L264

**Comment by jcwchriswalker** [comment]
@denysoblohin-okta - those files are the product of webpack's style-loader going against the okta css file. It took me awhile to figure out what was happening based on your 'What are those 6 files' comment. It looks like the webpack style-loader does not do what I wanted it to do resolving those font and png files. I removed the css reference  from my .ts file and manually copied in the needed png and font files in my build step.  It works just fine now. Thanks!
