### ISSUE TITLE
Email magic link failure, functionality broken 

### ISSUE THREAD

**Issue by MurthyAvanithsa** [okta/okta-signin-widget#3263]
### Describe the bug

Email verification link failure , with an error "The resource owner or authorization server denied the request."

### Reproduction Steps

1. Enable email a magic link settings in okta 
2. Login using email and proceed with "Email" as authenticator 
3. Click on send email 
4. Click the link in the EMAIL (you will receive in your inbox)
5. The Widget will show an error "The resource owner or authorization server denied the request."
6. You can use https://github.com/okta/samples-js-react to test this 

### SDK Versions

 okta/okta-auth-js": "^7.3.0
 @okta/okta-react": "^6.7.0
 @okta/okta-signin-widget": "^7.6.1

**Comment by shuowu-okta** [comment]
@MurthyAvanithsa Close this issue due to inactivity, feel free to reopen it if you have any other question.
