### ISSUE TITLE
introspect call blocks the form render

### ISSUE THREAD

**Issue by Joe-Withey** [okta/okta-signin-widget#3289]
### Describe the bug

When using the OktaSignin.showSigninToGetTokens method an "introspect" network request is made, this can take about 500 - 1000ms, the login form does not render until the call has completed. Is this essential? it would be nicer to be able to render the form and have the introspect call happen in the background.

<img width="256" alt="image" src="https://github.com/okta/okta-signin-widget/assets/12202750/1620f993-0149-4725-a694-1441be7a8947">

### Reproduction Steps

```
const widget = new OktaSignIn(config)

widget.showSignInToGetTokens({ el: '#login-form' })
```

### SDK Versions

https://global.oktacdn.com/okta-signin-widget/7.7.2/js/okta-sign-in.oie.min.js

**Comment by jaredperreault-okta** [comment]
It is essential. The widget renders views based on responses from our backend, `/introspect` is used to bootstrap the widget so the widget knows what view to render.
