### ISSUE TITLE
Okta Widget not working when i18n is defined for a different locale than the user browser

### ISSUE THREAD

**Issue by meleksomai** [okta/okta-signin-widget#3292]
### Describe the bug

We are using Okta customization option of the sign-in page (hosted by Okta and configured through the Okta admin dashboard).

We are customizing the english label of an error message. The change breaks Okta Widget. The widget is not visible for users' browser is non-english locale (e.g. spanish, etc).

![image](https://github.com/okta/okta-signin-widget/assets/1846037/31af1d5d-63a4-4d0c-ab73-c82ddf54cc6d)

### Reproduction Steps

- Go to Brands > ORG > Pages > Sign-In page
- Add the Javascript code below to configure the i18n string of a `login.properties` (list of labels available [gituhb.com/okta/Okta-signin-widget repo](https://github.com/okta/okta-signin-widget/blob/master/packages/%40okta/i18n/src/properties/login.properties) )

```html
    <script type="text/javascript">
        var config = OktaUtil.getSignInWidgetConfig();
        // HERE 👇 code
        config.i18n.en["errors.E0000068"] = "Your code does not match our records. Please try again."
        // ... other code
    </script>
```

- Preview the sign-on using a non-english locale for the browser. 

### SDK Versions

We are using version `^5` of the widget version.

**Comment by dchaoinception** [comment]
Opened a formal ticket with Okta, Case 01796232

**Comment by shuowu-okta** [comment]
@meleksomai @dchaoinception Have you tried adding i18n option during widget object initialization by following [doc here](https://github.com/okta/okta-signin-widget#i18n)?

**Comment by meleksomai** [comment]
The Okta Support team provided a response and it resolved the issue. The solution is to check if the `i18n.en` is available on the widget when initializing it. It seems that the widget breaks when initialing `i18n.en` in a different locale browser.

Here is a code snippet to solve the issue

```html
    <script type="text/javascript">
        var config = OktaUtil.getSignInWidgetConfig();
        // HERE 👇 code
        // Check that the locale is available before customizing it.
        if (config.i18n.en) {
                config.i18n.en["errors.E0000068"] = "Your code does not match our records. Please try again."
        }
        // ... other code
    </script>
```
