### ISSUE TITLE
pre-define phone number getting blank

### ISSUE THREAD

**Issue by juztinlazaro** [okta/okta-signin-widget#3298]
### Describe the bug

even I set a value `phone number` still got an error

![image](https://github.com/okta/okta-signin-widget/assets/10995629/2a986a0b-6814-49b3-b3c0-ebe2377a318d)

### Reproduction Steps

set phone number using javascript

```
const phoneInput = document.querySelectorAll(
      'input[name="phoneNumber"]',
    )[0];
    if (phoneInput) {
      phoneInput.disabled = true;
      phoneInput.value = '9155966542';
    }
```

![image](https://github.com/okta/okta-signin-widget/assets/10995629/a5d7fa39-b679-4a68-9997-ac14950d1d41)

![image](https://github.com/okta/okta-signin-widget/assets/10995629/c7e6812e-1e82-4a8d-83bd-efc8775926c7)

### SDK Versions

$ npx envinfo --system --npmPackages '{@okta/*,}' --binaries --browsers

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400T @ 1.30GHz
    Memory: 17.30 GB / 31.67 GB
  Binaries:
    Node: 12.22.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)   
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @okta/okta-auth-js: ^4.9.2 => 4.9.2
    @okta/okta-react: ^4.1.0 => 4.1.0
    @okta/okta-signin-widget: ^5.2.2 => 5.5.4

**Comment by juztinlazaro** [comment]
up

**Comment by shuowu-okta** [comment]
@juztinlazaro Can you share more information about issue? are you using this snippet in custom code editor, or it's for automation testing?

For a quick workaround, can you try `phoneInput.blur()` to see if it can make the form work properly?

**Comment by juztinlazaro** [comment]
Hi @shuowu-okta for the custom code editor, not in automation testing, will try `phoneInput.blur()` after the `phoneInput.Value`

**Comment by juztinlazaro** [comment]
Hi @shuowu-okta still getting a same issue, even i execute blur

![image](https://github.com/okta/okta-signin-widget/assets/10995629/3f432ae4-aeb5-4012-ae78-e686140260af)

**Comment by juztinlazaro** [comment]
@shuowu-okta same issue, how did you get the value of input? `keyup?`??

**Comment by shuowu-okta** [comment]
@juztinlazaro Thanks for all the feedback! we will investigate in this issue.

Internal Ref: OKTA-634180

**Comment by glenfannin-okta** [comment]
@juztinlazaro Hello, we are currently looking into this, but we just want to confirm that you are using the Classic version of the Sign-in Widget correct?

**Comment by glenfannin-okta** [comment]
Closing this as the solution is in the above comment. Please let us know if you need any additional assistance. Thank you!
