### ISSUE TITLE
Cannot install okta-signin-widget@7.8.0.  Dependency siw-platform-scripts is not available

### ISSUE THREAD

**Issue by getanish** [okta/okta-signin-widget#3301]
### Describe the bug

I am trying to install okta-signin-widget. The installation fails as one the dependencies @okta/okta-signin-widget@7.8.0 is not available.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@okta%2fsiw-platform-scripts - Not found
```

### Reproduction Steps

npm install @okta/okta-signin-widget@7.8.0

### SDK Versions

System:
    OS: macOS 12.6.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 61.87 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 6.14.18 
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @okta/okta-auth-js: ^7.3.0 => 7.3.0
    @okta/okta-react: ^6.7.0 => 6.7.0
    @okta/okta-signin-widget: ^7.7.2 => 7.7.2

**Comment by VinayakHegde** [comment]
Same here

**Comment by jaredperreault-okta** [comment]
I can confirm this issue, we are working on a solution. Stay tune for updates

**Comment by shuowu** [comment]
@getanish @VinayakHegde For now you can use `npm install @okta/okta-signin-widget@7.7.2` as a workaround, these two versions are almost identical as [7.8.0](https://github.com/okta/okta-signin-widget/releases/tag/okta-signin-widget-7.8.0) only has internal maintenance changes.

**Comment by HuangStanley050** [comment]
Same issue occured with version ^7.1.2

**Comment by jaredperreault-okta** [comment]
`7.8.1` was released to address this issue.
