### ISSUE TITLE
Bundle size is over 300MB and 32000 files

### ISSUE THREAD

**Issue by pascalspadone** [okta/okta-signin-widget#3323]
### Describe the bug

When `npm install`ing `@okta/okta-signin-widget`, the downloaded tarball is over 50MB, and over 300MB with more than 32000 files when unpacked. This doesn't seem reasonable and slows down our CI tasks.

The issue seems to be that the dev dependencies of the `src/v3` workspace are included in the tarball:

```
$ du -bhs node_modules/@okta/okta-signin-widget/src/v3/node_modules
222M    node_modules/@okta/okta-signin-widget/src/v3/node_modules
```

### Reproduction Steps

```
 npm pack @okta/okta-signin-widget@7.8.0
 npm pack @okta/okta-signin-widget@7.7.2
 ls -lh
```

```
-rw-r--r-- 1 pascal pascal 14M Jul 28 11:20 okta-okta-signin-widget-7.7.2.tgz
-rw-r--r-- 1 pascal pascal 54M Jul 28 11:20 okta-okta-signin-widget-7.8.0.tgz
```

### SDK Versions

```
$ npm ls | grep okta
│ ├── @okta/okta-react@6.7.0
│ ├── @okta/okta-auth-js@7.3.1
│ ├── @okta/okta-auth-js@7.3.1 deduped
│ ├── @okta/okta-react@6.7.0 deduped
│ ├── @okta/okta-signin-widget@7.8.1
```

**Comment by lesterchoi-okta** [comment]
internal ref OKTA-632669

**Comment by shawyu-okta** [comment]
@pascalspadone https://github.com/okta/okta-signin-widget/pull/3325 resolves this and the changes should be in the next minor version (`7.10.0`) release. Thank you for the report and detailed description!
