### ISSUE TITLE
"Do not challenge me on this device again" checkbox does not seem to work when unchecked

### ISSUE THREAD

**Issue by kochste** [okta/okta-signin-widget#3447]
### Describe the bug

When a user is prompted for MFA, we give them the option to not be challenged again on that same device (cookie based).  This check-box is pre-checked, so the user has to make a conscious decision to uncheck the box if they do want to be challenged again (e.g. they are on a public device).

It seems that on both of our preview tenants this functionality is broken.  When the checkbox is unchecked and the user supplies their MFA code to authenticate, they are not challenged again the next time.

This is working fine in our production tenant.

### Reproduction Steps

Sign in in an incognito window - when prompted for MFA (new device prompt), uncheck the box next to "Do not challenge me on this device again".  Sign out and sign in again in the same browser window.  You will not be prompted for MFA again.

### SDK Versions

widget version 7.11.2
Okta Classic
Okta Preview tenant (OP3 Preview Cell (US) - Version 2023.10.1 C)
Google Chrome

**Comment by jaredperreault-okta** [comment]
@kochste Can you file a case with support (https://support.okta.com/help/s/?language=en_US). They are better equipped to handle a situation like this.
