### ISSUE TITLE
Release 2.4.0 to CDN

### ISSUE THREAD

**Issue by cniesen** [okta/okta-signin-widget#347]
Thanks for releasing 2.4.0 to npm.  Unfortunately we can't use the npm release due to issue #311.  Could you please put 2.4.0 on CDN as well. Thanks.

Not found:
* https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.4.0/js/okta-sign-in.min.js
* https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.4.0/css/okta-sign-in.min.css
* https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.4.0/css/okta-theme.css

**Comment by santhoshbalakrishnan** [comment]
@cniesen It should be on CDN by EOD Wednesday(Nov 15, 2017).

**Comment by santhoshbalakrishnan** [comment]
@cniesen It's available now on preview CDN: https://op1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.4.0/js/okta-sign-in.min.js 

Will be released soon on production CDN.
