### ISSUE TITLE
okta-sign-in.entry.js file size exceeds ~1.5mb in overall bundle size

### ISSUE THREAD

**Issue by sutkol** [okta/okta-signin-widget#3553]
### Describe the bug

We have been using okta-widget version "@okta/okta-signin-widget": "^5.8.4", since we keen on web performance the okta javascript file itself is a huge contributor in our repository. All other files in our repo has less than 300kbs including third party javascript files. 

![Screenshot 2024-02-21 at 11 44 05 AM](https://github.com/okta/okta-signin-widget/assets/160702106/fb25a2c4-1669-4336-b6ae-1ad948431af4)

Just curious if we at least can lazy load the okta module without blocking the rendering and execution of other js files. 

### Reproduction Steps

Using page speed insights and referenced the compiled js file which is ~1.6mb

### SDK Versions

5.8.4

**Comment by jaredperreault-okta** [comment]
Without knowing about your application and use case it's hard to provide clear guidance, however there is nothing about the SIW which would prevent from being lazy loaded.

A few other options you could explore:

- Upgrade to the latest version
    - You're 2 major versions behind latest, we have made a decent amount of changes to lower the bundle size
- Migrate to Redirect Model
     -  With redirect model, your users are redirected to an Okta-hosted SIW, so you would no longer need to host it yourself
     - https://developer.okta.com/docs/guides/redirect-authentication/
