### ISSUE TITLE
Don't include x-okta-xsrftoken in authn requests

### ISSUE THREAD

**Issue by rchild-okta** [okta/okta-signin-widget#359]
Sourced from this StackOverflow question:
https://stackoverflow.com/questions/47680763/x-okta-xsrftoken-and-js-widget

> i've noticed that when JS component makes calls to authorise (/api/v1/authn) its got an empty header in the request called 'X-Okta-XsrfToken'.
>
> Should that be set or is it defunct?

**Comment by johngronberg-okta** [comment]
This field is no longer used and can be ignored. We have created an internal ticket to remove this in a future release. Closing for now.
