### ISSUE TITLE
Custom checkbox fields added via the parseSchema API have a duplicate label

### ISSUE THREAD

**Issue by bryanbraun** [okta/okta-signin-widget#3604]
### Describe the bug

When using [the `parseSchema` API](https://github.com/okta/okta-signin-widget/tree/master?tab=readme-ov-file#parseschema) to add a custom checkbox field to the okta-signin-widget registration form, the checkbox is displayed with **two** labels (each saying "example checkbox label"), as shown here:

```js
parseSchema: (schema: any, onSuccess, onFailure) => {
  schema.push({
    name: "example.checkbox",
    type: "checkbox",
    modelType: "boolean",
    label: "example checkbox label",
    sublabel: "example checkbox sublabel",
    "label-top": true,
    required: false
  });
  schema.push({
    name: "example.textfield",
    type: "text",
    label: "example text label",
    sublabel: "example text sublabel",
    "label-top": true,
    required: false,
    placeholder: "example text placeholder"
  });
  onSuccess(schema);
}
```

![Screenshot 2024-04-16 at 5 50 07 PM](https://github.com/okta/okta-signin-widget/assets/1256329/3a456a35-b62d-4c79-8317-1ba9851d94a3)

*Expected behavior: for custom checkbox fields, the label only displays once (or there is some way to configure it to only display once).*

Other notes from the example above:

- For the `type: text` field, the label only displays once, as expected (see "example text label," pictured above).
- For the `type: checkbox` and `type: text` fields, the **sublabel** only displays once as expected, (see "example text sublabel" and "example checkbox sublabel," pictured above).
- The code used for the checkbox field is based on the code in [this okta-signin-widget test](https://github.com/okta/okta-signin-widget/blob/1858480328499bcd10c65fa53801d9bbb792aa18/src/v3/src/transformer/transaction/transform.test.ts#L178-L186).

### Reproduction Steps

1. Set up an example application using the embedded okta-signin-widget.
2. In the WidgetOptions, define a `parseSchema` function that adds a `type: checkbox` field similar to code shown below:
```js
parseSchema: (schema, onSuccess, onFailure) => {
  schema.push({
    name: "example.checkbox",
    type: "checkbox",
    label: "example checkbox label",
    sublabel: "example checkbox sublabel",
    "label-top": true,
    required: false
  });
  onSuccess(schema);
}
```
3. View the registration form and verify that the label "example checkbox label" is displaying twice on the screen (see screenshot above for an example).

### SDK Versions

  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 51.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.6.0 - ~/.nvm/versions/node/v16.14.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Chrome Canary: 125.0.6422.0
    Firefox Nightly: 126.0a1
    Safari: 17.1
  npmPackages:
    @okta/okta-signin-widget: ^7.15.1 => 7.15.1 

### Additional Information

Currently our workaround is to hide one of the labels with CSS. Please advise if you recommend a better solution.

**Comment by glenfannin-okta** [comment]
@bryanbraun 👋 Hello! Thank you for the post! 

When adding a custom checkbox using the registration schema, if you just want one label (assuming the label directly next to the checkbox) you will want to omit the `label` key from the schema object and replace it with `placeholder`, for example: 

```
parseSchema: (schema: any, onSuccess, onFailure) => {
  schema.push({
    name: "example.checkbox",
    type: "checkbox",
    modelType: "boolean",
    placeholder: "example checkbox label",
    "label-top": true,
    required: false
  });
  onSuccess(schema);
}
```

Let us know if this works for you. Thank you!

**Comment by bryanbraun** [comment]
@glenfannin-okta, yes that's working great! I had tried omitting `label`, but didn't think to use `placeholder` to bring in the text I needed.

Thank you!
