### ISSUE TITLE
Unable to save items to user's profile

### ISSUE THREAD

**Issue by Burnett2k** [okta/okta-signin-widget#3620]
### Describe the bug

During account creation, our team needs to save some metadata to the user's profile which we already have access to. For example, `userProfile.locale`. We also have a checkbox to store some preferences and are unsure how to get that to svae to the user's profile.

The documentation for the widget has an example that indicates it is possible to use the `preSubmit` hook to add data being sent to the Okta new user creation api. Specifically this [example](https://github.com/okta/okta-signin-widget?tab=readme-ov-file#presubmit) where it appears the `postData` is modified.

When trying to use this hook to add fields to the postData object it always fails. It appears to fail within the widget before even being sent to Okta. Even firstName and address (which is shown in the [parseSchema example](https://github.com/okta/okta-signin-widget?tab=readme-ov-file#parseschema) do not work using this strategy. Example code below

```
    preSubmit(postData: any, onSuccess: any, onFailure: any) {
      // attempting to update locale on the user profile always fails
      postData.userProfile.locale = "en_US";
      onSuccess(postData);
    }
```

error message:
```
2943.5ff351228993195a.js:1 Error: '[userProfile.locale]' cannot be modified.
    at OktaSignIn.callback (OktaSignIn.js:166:26)
    at triggerEvents (backbone.js:308:53)
    at triggerApi (backbone.js:285:21)
    at eventsApi (backbone.js:101:18)
    at Events.trigger (backbone.js:276:7)
    at OktaSignIn.trigger (OktaSignIn.js:191:44)
    at triggerEvents (backbone.js:311:53)
    at triggerApi (backbone.js:286:24)
    at eventsApi (backbone.js:101:18)
    at Events.trigger (backbone.js:276:7)
    at triggerEvents (backbone.js:311:53)
    at triggerApi (backbone.js:286:24)
    at eventsApi (backbone.js:101:18)
    at Events.trigger (backbone.js:276:7)
    at child.handleAfterError (FormController.js:128:10)
    at triggerEvents (backbone.js:305:53)
    at triggerApi (backbone.js:285:21)
    at eventsApi (backbone.js:101:18)
    at Events.trigger (backbone.js:276:7)
    at child.triggerAfterError (EnrollProfileView.js:98:27)
    at triggerEvents (backbone.js:311:53)
    at triggerApi (backbone.js:285:21)
    at eventsApi (backbone.js:101:18)
    at Events.trigger (backbone.js:276:7)
    at child.showFormErrors (FormController.js:409:11)
    at child.handleSaveForm (FormController.js:329:20)
```

Am I misunderstanding how preSubmit works? We want to set this data during user creation rather than later on using an api, because dependent systems have hooks into account creation that need this data.

Please let me know what is the recommended way to approach this? Is it possibly some kind of okta configuration or permissions issue preventing this?

We've found a workaround that _might_ work where we add locale to the User Profile Policies profile enrollment form. 

<img width="1043" alt="image" src="https://github.com/okta/okta-signin-widget/assets/3632381/e8c03d6c-dc50-49b8-90b0-64a4447425d2">

Unfortunately, this causes the field to show up in account creation, so we would have to then write code to
1) Automatically fill the value and not allow user to edit it.
2) Hide it from the DOM so the user cannot see it.

After starting on this workaround, it feels like the wrong way to go about it, so I'm hoping for some guidance. Thanks in advance for helping me solve this bug.

### Reproduction Steps

1. Load okta-signin-widget on a browser
2. Go to the create account / sign up flow
3. Update the registration object presubmit hook to add some additional data to the user's profile
```
registration: {
  parseSchema: (schema, onSuccess, onFailure) => {
      // handle parseSchema callback
      onSuccess(schema);
  },
  preSubmit: (postData, onSuccess, onFailure) => {
      // handle preSubmit callback
      postData.userProfile.firstName = 'bob'; // this will cause a failure
      onSuccess(postData);
  },
  postSubmit: (response, onSuccess, onFailure) => {
      // handle postsubmit callback
      onSuccess(response);
  }
},
```
4. Try to create an account
5. Notice that the form will fail with an error that '[userProfile.firstName]' cannot be modified.'

### SDK Versions

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 454.13 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.6.7 - ~/.yarn/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1

**Comment by trevoring-okta** [comment]
Hi @Burnett2k , thanks for the report! The behavior you're seeing related to not being able to modify/write the `userProfile.locale` property is expected. Our backend does not allow modifying properties that are not present in the registration form itself, so your "workaround" of adding the Locale property to the form will be the correct solution. 

If you don't want to allow your users to modify this locale after adding it to the form then I would recommend you try implementing either of the code-based solutions you suggested (automatically filling the value or hiding the input field from the DOM).

**Comment by Burnett2k** [comment]
@trevoring-okta Hi Trevor, Thanks for that info that we're on the right track.

What's the recommended approach for hiding this locale field so it's treated like a hidden input? Is there a 'hidden' attribute I can use in the schema? Or, do I need to do some kind of querySelector to find and delete / hide those input elements?

I'm a little confused on the [example](https://github.com/okta/okta-signin-widget?tab=readme-ov-file#parseschema) where you can add to the schema new fields in the parseSchema field. Wouldn't that always fail unless you also added that field into the profile enrollment form? And if that is the case, wouldn't the field already exist and you wouldn't want to push it to the schema? Can you verify if all fields we want to save need to be added to profile enrollment form?

If you have any documentation which references this configuration that would be really helpful. Thanks for any additional info you can provide.

**Comment by trevoring-okta** [comment]
@Burnett2k There unfortunately isn't a hidden attribute in the schema itself, so if you want to go the route of hiding the element I'd recommend you add something like `document.querySelector('[data-se="o-form-fieldset-userProfile.locale"]');` to select the locale input and then add the CSS of your choice to hide it (e.g. `display: 'none'`). I recommend the `data-se` attribute as your selector because that's a more stable and specific selector than a `class`.

Another option could be to set the `disabled` attribute for the locale property in the schema so users cannot edit it.

```
    parseSchema: (schema, onSuccess) => {
      // Find the locale field from schema array
      let locale = schema.find(field => field.name === 'userProfile.locale');
      if (locale) {
        // loca
        locale.value = "en_US";
        locale.disabled = true;
      }
      onSuccess(schema);
    }
```

In terms of the `parseSchema` example from documentation, I just confirmed with my team that your logic is correct. Any fields added via `parseSchema` that is eventually submitted w/ form submission must already be added to the profile enrollment form, which means that it should already come with the schema. This example should really be updated to illustrate a use case for modifying something about an existing field (e.g. setting it to `disabled` as I show above) and our best guess is that there was a point in time where backend enforcement that a field must already exist in the form in order to be modified did not exist but `parseSchema` did.

**Comment by Burnett2k** [comment]
@trevoring-okta Thanks for this information! I was able to use parseSchema to set the value and disable it like you proposed and it seems to work well.

I opted to use css to select and hide the locale element using `data-se`.
```
[data-se='o-form-fieldset-userProfile.locale'] {
      display: none;
    }
```

I'm happy to close out this issue, but I would be even happier if you guys could update the documentation to reflect the findings we discussed. Essentially, you can only use parseSchema to modify existing field forms OR add ones that cannot actually be saved to the user's profile.

Thanks again for the quick responses!

**Comment by trevoring-okta** [comment]
@Burnett2k Glad that solution worked for you! I'll create a ticket on our side to get the documentation updated, thanks
