### ISSUE TITLE
Disable auto scroll behaviour on default password form

### ISSUE THREAD

**Issue by anvar** [okta/okta-signin-widget#365]
Hi,

Would it be possible to make `scrollOnError` configurable for the `PrimaryAuthForm`?

Thanks,

Anvar

**Comment by dcalise** [comment]
Any update on this? I can see the option `scrollOnError` defined in the library, but have not been able to disable it.

**Comment by robertjd** [comment]
Thanks everyone, could you drop us a note about the use case or user story that you're trying to implement?  That will help is investigate, thanks!

**Comment by santhoshbalakrishnan** [comment]
Hi @anvar @dcalise ,  just checking in, any updates from your end?

**Comment by ElBafo** [comment]
Hello, we would also like to disable the scrollOnError, is there a way?

**Comment by nbarbettini** [comment]
@ElBafo There isn't currently a way to disable scrollOnError. I'm curious - what's the situation you have where you want to disable it?

**Comment by ElBafo** [comment]
Hey @nbarbettini ! What happens is that when there is an error in the form:

- the form scrolls up to the top of the browser window (not the body of the website)
- since the menu is on a position:fixed state the top of the login form is hidden by the menu.

Hope that helps

**Comment by dcalise** [comment]
After speaking with a rep from the okta team, it seems that the scrollOnError option has not been exposed yet and cant be used without editing the actual library.

**Comment by aarongranick-okta** [comment]
@dcalise It has been some time since this issue was filed and there have been many releases to the widget since then. Has this issue been resolved?

**Comment by swiftone** [comment]
Closing this issue as stale - if anyone has a case where they need to disable normal scroll behavior, feel free to reopen with details.

**Comment by johnsonvkd-hub** [comment]
I am facing the same issue, after entering invalid credentials in the okta login widget form, form scrolling to the top navigation which is not a good user experience.Is there any way to prevent the scroll top behavior?
