### ISSUE TITLE
Safari/iOs : on Safari (Mac OSX + iOS), i am disconnected when I reload the page

### ISSUE THREAD

**Issue by Cezarion** [okta/okta-signin-widget#366]
Hello,
I am in the context of a single page application in Angular 5.
Versions tested: 2.4.0 and 2.5.0

When I connect from Safari (11.0.2) if I reload the page the connection is not kept.
On other browsers (Firefox, Chrome, ...) it works without problems.

The only difference is that the first request of type `Request Method: OPTIONS` on the url` / api / v1 / sessions / me` does not seem to be sent.

there is probably a link with this issue: https://github.com/okta/okta-auth-js/issues/71

**Comment by lboyette-okta** [comment]
@Cezarion I just commented on that issue, but the gist is that the silent login flow won't work on Safari, but silent refresh will. To have the best cross-platform support, we recommend the redirect flow for sign-in.

**Comment by Cezarion** [comment]
Ok, thank's a lot for your quickly response.

**Comment by foiseworth** [comment]
@lboyette-okta could you possibly link to some documentation for the redirect flow? I'm not 100% certain on what you mean. Many thanks

**Comment by foiseworth** [comment]
Also, does this effectively mean this widget / okta-auth-js is not appropriate for anyone who want to support safari?

**Comment by foiseworth** [comment]
Actually I believe I got it working by using `res.session.setCookieAndRedirect` after successfully logging in. I just had to stop passing the clientId to the OktaSignIn in order to disable the oauth2 flow.
