### ISSUE TITLE
Handle ill formatted options to prevent widget from hanging

### ISSUE THREAD

**Issue by bdemers** [okta/okta-signin-widget#376]
This was caused by user error (me), but it was pretty hard to figure out what the problem was.

I had a space in front of my baseUrl option:
```json
baseUrl: ' https://dev-123456.oktapreview.com'
```
With this setting the widget rendered, and I was able to submit a user/pass.  If I typed my password wrong, the widget responded correctly. When a valid user/password was entered the widget would just hang.  No errors in the console, and I was able to see valid responses from the server (along with an access token in the response).

The widget should either fail fast if an ill formatted baseUrl (or other option) is detected or attempt to sanitize the string (i.e. a trim), possibly both.

**Comment by santhoshbalakrishnan** [comment]
Hi @bdemers 

I just tried this out with a fresh clone of okta-signin-widget. The sign in did work for me though, but it redirected me to a URL with the preceding space - something like `https://<something>.oktapreview.com/login/%20https://<something>.oktapreview.com/app/UserHome` and that led to a 404. It did not hang though. 

It would be helpful if you can tell us:

1. Did you try it off a fresh clone? 
2. Which browser/OS did you try this on?

**Comment by bdemers** [comment]
I tired 2.1.0 and 2.4.0.  
I was able to reproduce in Chrome and Safari (i didn't try FF). Using this example: https://github.com/okta/samples-java-spring-mvc/blob/master/front-end/src/main/resources/static/index.html#L53-L62

**Comment by nbarbettini** [comment]
+1 for some basic validation of the widget configuration. Automatically checking stuff like malformed URLs, not using `https`, including `-admin.oktapreview` in the URL, etc. and throwing an error would be good DX for the widget.

**Comment by jmelberg-okta** [comment]
Downstream we merged in a change that will check for `*-admin` in the URL on instantiation. Once a new okta-auth-js version is published, we can update the widget to pick up this change.

**Comment by jmelberg-okta** [comment]
Closing this out for now, as it will get picked up with a new release of AuthJS + the Widget.
