### ISSUE TITLE
Help link (/help/login) returns a 404

### ISSUE THREAD

**Issue by kenthufluxx** [okta/okta-signin-widget#387]
There's a Help link in the widget, and when the user clicks on it, they get redirected to an Okta page that doesn't exist. (I'm using widget version 2.5.0.)

Steps to reproduce:

1. Load Okta widget
2. Click on “Need help signing in?”
3. Click on “Help”
4. Pops up tab with URL https://dev-xxxxxx-admin.oktapreview.com/help/login which redirects to https://dev-xxxxxx-admin.oktapreview.com/error/404?fromURI=%2Fhelp%2Flogin

I know it's possible to customize this URL, but Okta should either fix that default /help/login URL, or just not show a Help link if there no URL was provided on widget initialization.

**Comment by jmelberg-okta** [comment]
Hi @kenthufluxx!

Looks like you're including the `-admin` in your base URL. If you remove it, you should see the `/help/login` page.

Can you try that and report back?

**Comment by kenthufluxx** [comment]
That worked! Thanks!
