### ISSUE TITLE
Registration link not working

### ISSUE THREAD

**Issue by jayanthv86** [okta/okta-signin-widget#391]
Hi,

We were testing out the Registration as a service feature. We even have the router:true flag turned on.

However, when we try to click on Sign up, I can see the form JSON coming in, but it doesn't render the widget.

Our feeling is this has to do with the js framework we are using (Angular). Is there a path or URI that we need to whitelist?

**Comment by manueltanzi-okta** [comment]
Hi @jayanthv86, couple of questions:
- Which version of the widget are you using?
- Did you try with both router flag on and off?

**Comment by jayanthv86** [comment]
@manueltanzi-okta This is not a problem after upgrading to okta sign in widget version 2.6.0. Thanks a lot for your help!
