### ISSUE TITLE
Widget initialized with OIDC does not set session in ie11

### ISSUE THREAD

**Issue by jyotsnaraghunathan-okta** [okta/okta-signin-widget#396]
[oidc_widget.zip](https://github.com/okta/okta-signin-widget/files/1716609/oidc_widget.zip)

- Widget is initialized using OIDC. 
- On success callback, the session id is not being set in the browser in ie11.  So when I redirect to the okta tenant home page,  it does not log the user in automatically. It redirects back to the widget page. 
  function (res) {
			oktaSignIn.tokenManager.add('my_token', res);
						window.location.href = baseUrl;    //Does not work in ie11 !! Works in other browsers
                        }

**Comment by nbarbettini** [comment]
I successfully reproduced this in IE11. Redirecting to the Okta dashboard doesn't work. It's acting as if there is no session established for the user, although the widget was able to sign in.

Notably this **does** work in Edge. So it appears to be an IE11-only problem.

**Comment by nbarbettini** [comment]
I created a repo with a easy-to-test reproduction of this issue: https://github.com/nbarbettini/okta-signin-widget-ie11

1. Replace `{yourOktaDomain}` and `{yourClientId}`
2. Run `npm start` and browse to http://localhost:8080
3. Try signing in with Chrome or Edge: you'll be redirected to the signed-in Okta dashboard
4. Try signing in with IE11: you'll be redirected and prompted to sign in again

**Comment by nbarbettini** [comment]
After investigation with the engineers, there is a little more to the story. The above repro **does** work on IE11 if you use `setCookieAndRedirect`, which is the correct method to use if you are signing into the Okta dashboard.

**Comment by nbarbettini** [comment]
Closing this issue. As stated above, `setCookieAndRedirect` is the correct method to use, and it works in IE11.

**Comment by nbarbettini** [comment]
Ping @jyotsnaraghunathan-okta - can you close this if your issue has been resolved? Thanks!

**Comment by jyotsnaraghunathan-okta** [comment]
case solved.
