### ISSUE TITLE
Getting a future JWT on Samsung Galaxy Note 4

### ISSUE THREAD

**Issue by loqtor** [okta/okta-signin-widget#399]
Hi guys,

When the user attempts to login on Chrome on a Samsung Galaxy Note 4 (Android 6.0.1) I get the error in the screenshot.

The steps to reproduce are:

1 - Attempt to login with a valid user password.

**Expected**: User should be able to login and continue to the site.
**Actual**: Getting what's in the screenshot.

Let me know if you need more information.

Cheers!

![screen shot 2018-02-21 at 10 27 02 am](https://user-images.githubusercontent.com/5937874/36451774-0fa57fd8-16f7-11e8-8f61-491e5cf7f421.png)

**Comment by lboyette-okta** [comment]
This can happen if the time on the device is more than 5 minutes off from the actual time (usually determined by ntp servers). This usually only happens if a user changes the time manually.

**Comment by loqtor** [comment]
Hey,

Thanks for your response. You are absolutely right.

We just checked on the Settings and the time had been manually set.

We can have this one closed now. 

Cheers!

**Comment by mautrok** [comment]
Is it possible to extends the amount of time? Suppose that some companies has server problems and noone is there to repair it,  this "5 minutes" depend on some variables or is a fixed unit of time?

**Comment by jaredperreault-okta** [comment]
@mautrok can you open a new issue with your question/concern? This issue is over 5 years old
