### ISSUE TITLE
unable to login in salesforce using okta sso

### ISSUE THREAD

**Issue by NishaLodhi** [okta/okta-signin-widget#402]
Hi, 
I am new in okta. I followed beo link to sso setup in okta with salesforce
http://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-in-Salesforce.html
 but unbale to login. 
I am getting following error
            We can't log you in. Check for an invalid assertion in the SAML Assertion Validator (available in 
              Single Sign-On Settings) or check the login history for failed logins. 

![oktaapplist](https://user-images.githubusercontent.com/24477134/36974402-923c8a64-209c-11e8-9ad7-e753e276236f.PNG)

![sso error](https://user-images.githubusercontent.com/24477134/36974194-c965611a-209b-11e8-9881-5b19a996c7c4.PNG)

![sfdcsaml](https://user-images.githubusercontent.com/24477134/36974309-37ff852e-209c-11e8-9429-f5cb336ca868.PNG)

**Comment by omgitstom** [comment]
Reach out to us for support.  This isn't the normal channel for these types of questions.

https://support.okta.com/help/open_case

**Comment by jmelberg-okta** [comment]
Closing as this issue doesn't relate to this repository.
