### ISSUE TITLE
JavaScript bloat

### ISSUE THREAD

**Issue by nicholassaunders** [okta/okta-signin-widget#403]
Please review the contents of my node_modules/@okta/okta-signin-widget/dist/js directory and notice the file sizes:

```
-rw-r--r--  1 nsaunders  2067502022   902K Jan 19 13:09 okta-sign-in-no-jquery.js
-rw-r--r--  1 nsaunders  2067502022   5.7M Jan 19 13:09 okta-sign-in-no-jquery.js.map
-rw-r--r--  1 nsaunders  2067502022   1.6M Jan 19 13:09 okta-sign-in.entry.js
-rw-r--r--  1 nsaunders  2067502022   2.3M Jan 19 13:09 okta-sign-in.entry.js.map
-rw-r--r--  1 nsaunders  2067502022   998K Jan 19 13:09 okta-sign-in.min.js
-rw-r--r--  1 nsaunders  2067502022   6.5M Jan 19 13:09 okta-sign-in.min.js.map
```

Considering that my main application bundle weighs in at <100K, even the minified version of the Sign-in Widget is unacceptably large at ~1MB. I'm sorry to say, but even reducing the size by half would _really_ be pushing it, especially on, say, a mobile device!

Is there anything you guys can do about this?

**Comment by rchild-okta** [comment]
I definitely agree - it's something we need to look into. Unfortunately, there aren't any quick wins, but there are some approaches we've been considering:
- Cleaning up our third-party dependencies - there are a couple obvious ones like qtip2 (way too big for what we're using it for) and Q (which we can replace with a lighter polyfill).
- We depend on an internal framework - I haven't run this recently, but we're probably including some code we don't need to. This one's straightforward, but the savings will be minimal.
- The holy grail: lazy-load our modules. We're currently loading one big bundle that has everything included, but most sign-in flows only go through a couple of the views. Ideally, we'd only ship a lightweight bootloader upfront, and load views when they're called out in the /authn response (and even better, cache these via something like service workers).

**Comment by rdegges** [comment]
@nbarbettini any chance we can look into this in the near future?

**Comment by therealnicksaunders** [comment]
Any news on this? I really appreciate the responses from @rchild-okta and @rdegges who seem like they would like to act; but obviously I'm disappointed at the lack of any other activity, and I'm not sure I can recommend the Sign-in Widget for a customer-facing application until this issue is addressed.

**Comment by gardner** [comment]
This is still an issue in 2.x?

**Comment by nbarbettini** [comment]
Thanks for your patience, everyone. I agree, the bundle size is too damn high!

Starting with release [2.14.0](https://github.com/okta/okta-signin-widget/releases/tag/okta-signin-widget-2.14.0) we have been working to reduce the size of the minified output. You should see some incremental improvement already:

```
# As of 2.15.0
-rw-r--r-- 1 Nate 197121 2239369 Jan 16 09:47 okta-sign-in.js
-rw-r--r-- 1 Nate 197121 3330331 Jan 16 09:47 okta-sign-in.js.map
-rw-r--r-- 1 Nate 197121  846209 Jan 16 09:47 okta-sign-in.min.js
-rw-r--r-- 1 Nate 197121 5761404 Jan 16 09:47 okta-sign-in.min.js.map
```

I know this is still large, but we'll keep working at it. I'm going to close this issue as it's an on-going project, not something that has a definitive stopping point. Please continue giving us your feedback though!

**Comment by gardner** [comment]
Hi Nate,
  I am keen to help out whichever way that I can. Generally, on other projects, I have seen people leave unresolved issues open to track progress and, more importantly, to be able to close duplicates while refer to the oldest open issue.

I understand every team has their own way of working and processes that they follow. 

Cheers,
  Gardner

**Comment by nicholassaunders** [comment]
Hey @gardner, are you using any Okta-specific features? I’ve been thinking about spinning up a similar project that does nothing except OIDC with single-factor authentication as the default. I would probably try to get my employer to sponsor it, but admittedly I’m not sure how much luck I will have since execs already believe Okta has an asset that solves this problem well.

**Comment by robertabramski** [comment]
+1 for this. I'm using 5.13.0 and the bundle size of this widget is about the size of the rest of the application.

**Comment by gardner** [comment]
I wrote this: https://github.com/gardner/react-oauth2-pkce

**Comment by torressam333** [comment]
I am using ` "@okta/okta-signin-widget": "^6.6.1",` in my project and the bundle size is HUGE. 
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/33882985/188718628-cb22522d-86f0-462d-8e75-636869a935ed.png">


Is there anyway to make this smaller?

**Comment by jchabotamica** [comment]
Any update on the progress of this?  We are on the latest, and considering replacing it with our own custom form in order to resolve this issue.

**Comment by jchabotamica** [comment]
It also isn't just the js, it's the css as well.  This causes a large "unused css" violation Chrome Web Vitals.

**Comment by mickfo** [comment]
It seems that this issue has still not been addressed by Okta unless I'm mistaken. Our js and css bundle size (since implementing the okta-sign-in-widget) has increased by more than 4mbs. This is causing unacceptable load times and is violating Chrome Web Vitals, dramatically impacting this clients search engine placement. The web app is using okta-sign-in widget 4.8.0. I've updated to 7.12.1 which resulted in the file sizes becoming even larger. I've not had success when attempting to lazy load the module. 

@nbarbettini and @rchild-okta (above) acknowledged this problem in 2018. Has there been any progress on this? Any information or feedback would be very much appreciated.

**Comment by gardner** [comment]
It appears they have been using the same [build strategy](https://github.com/okta/okta-signin-widget/blob/b670350e0341132a358d95ed045e62176b738274/webpack.release.config.js#L4) for the last 5 years. 

> generates a minified built version of the widget that includes everything necessary to run (including all vendor libraries)

This strategy prevents build time optimizations that could deduplicate code and reduce the overall bundle size.

**Comment by mickfo** [comment]
Thanks @gardner. It's pretty odd that Okta hasn't come up with a lighter weight version of this. It seems they are aware of the issue.
