### ISSUE TITLE
API Error messages for E0000014: Update of credentials failed.

### ISSUE THREAD

**Issue by loqtor** [okta/okta-signin-widget#412]
Hi guys,

Sorry if this does not belong here, but I hope you can help me.

We need to customize the error messages related to `errorCode: "E0000014"`. 

I have two questions regarding this:
1 - Is it possible to update these messages from the Admin UI?
2 - If not, there are three different type of errors that use this same code:

```
{"errorCode":"E0000014","errorSummary":"Update of credentials failed","errorLink":"E0000014","errorId":"oae-Q0hctCUSD2cz64VSA69BQ","errorCauses":[{"errorSummary":"Old Password is not correct"}]}

{"errorCode":"E0000014","errorSummary":"Update of credentials failed","errorLink":"E0000014","errorId":"oaeoX7Ft9CwSC6MGnASHaMlsQ","errorCauses":[{"errorSummary":"Password cannot be your current password"}]}

{"errorCode":"E0000014","errorSummary":"Update of credentials failed","errorLink":"E0000014","errorId":"oae0kvP8RTSQ-y90cXWaGWq_g","errorCauses":[{"errorSummary":"Password requirements were not met. Password requirements: at least 8 characters, a lowercase letter, an uppercase letter, a number."}]}
```

How likely are the messages in `errorSummary` to change? 

Because if these cannot be updated from the UI, the only other way we have would be to check on the `errorSummary` attribute and show a custom message for each case. 

Needless to say, this does not sound like the best approach, but if this is not available to be edited from the UI, then there's no other way we could achieve this.

I hope this is clear.

Thanks.

Cheers!

**Comment by jmelberg-okta** [comment]
Hey @loqtor! The best opportunity to get questions like this answered is on the [Okta Developer Forums](https://devforum.okta.com).

However - if you're wanting to modify the error messages on your own login page that hosts the widget, there is information on how to set that up [here](https://github.com/okta/okta-signin-widget#language-and-text).

Thanks!
