### ISSUE TITLE
Poor error message when invalid email address entered in Forgot Password

### ISSUE THREAD

**Issue by tc555** [okta/okta-signin-widget#418]
During the 'forgot password' flow, when a user enters an invalid email address, such as user@xxxxx, the error message ,"The field must not contain HTML tags".  Of course, no HTML tags were entered.

This message would be appropriate if the user entered something like "<script>alert('hi')</script>".

Please change this error message to something along the lines of "Format error with email or username."

**Comment by jmelberg-okta** [comment]
This is a known feature gap that we're going to be fixing in the near future.

I've created a new issue (#549) to track all ongoing work related to providing the ability capture these type of events, so I'm going to close this issue for now.

Please leave a 👍 on that issue.
