### ISSUE TITLE
Cannot run tests on MacOS

### ISSUE THREAD

**Issue by mschaeffner** [okta/okta-signin-widget#427]
When running `npm test` it got stuck (doesn't do anything/doesn't finish) after the following line of console output:
```
...
Testing jasmine specs via PhantomJS
```

Updating `grunt-contrib-jasmine` to version 1.1.0 will solve the problem. For more information see https://github.com/okta/okta-auth-js/issues/108

**Comment by jmelberg-okta** [comment]
Resolved with #428
