### ISSUE TITLE
okta-sign-in-no-jquery.js depends on jquery?

### ISSUE THREAD

**Issue by ilia-luk** [okta/okta-signin-widget#453]
When I use `const OktaSignIn = require('@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery.js');`
and check the dependency tree i get jQuery in my bundle.
![Webpack Bundle Analyzer](http://res.cloudinary.com/domusnetwork/image/upload/v1526462844/Screen_Shot_2018-05-16_at_12.18.37.png)

any thoughts?

**Comment by oklas** [comment]
Using jquery in react app is dubious idea. Using /dist/js/okta-sign-in-no-jquery.js is very bad idea. It include almost a Megabyte overhead to bundle which will be loaded each time. Include jquery itself from any CDN is better because is a chance that it already in browser cache and downloading may be omited.

Is any chance about to avoid to use jquery in modern applications?

**Comment by aarongranick-okta** [comment]
@oklas The Signin Widget has a dependency on jQuery. The `no-jquery` bundle is provided in case you would like to require jQuery separately yourself. To avoid bundling it with webpack you could define jquery as an "external" in your webpack config, and then include jQuery from a CDN. We also offer [CDN distributions](https://github.com/okta/okta-signin-widget#using-the-okta-cdn) of the signin widget itself, this can be used to avoid bundling the signin widget in your app. In most cases, the CDN distribution will work well for you. It is only necessary to bundle the NPM module if you want to do certain types of customization, such as building with custom language files.

**Comment by aarongranick-okta** [comment]
The widget is a large Javascript application, which currently requires jQuery. We generally recommend using the CDN distribution of the widget as it avoids adding this extra weight to your application bundle and it is also easier to manage the versioning of the widget separately from your application build. If you are embedding the widget, we strongly encourage upgrading to the latest version regularly, as we are always making fixes, updating translations, and adding features which may be needed in your organization's sign-on policy. 

Closing this issue. If you are experiencing a problem with the latest version, please create a new issue. Thanks!
