### ISSUE TITLE
Show/hide custom loading before and after a login failed

### ISSUE THREAD

**Issue by stormit-vn** [okta/okta-signin-widget#465]
I want to show a custom loading when user trying to authenticating and hide loading when any error return from Okta such as **Sigin in failed!**. Is there any way to handle this kind of function? Are there any event that i can listen? I tried on the success and error callbacks but both functions seems not get trigged.

Here is my widget config

```
this.signIn = new OktaSignIn({
            /**
             * Note: when using the Sign-In Widget for an ODIC flow, it still
             * needs to be configured with the base URL for your Okta Org. Here
             * we derive it from the given issuer for convenience.
             */
            baseUrl: APP_CONFIG.OKTA_BASE_URL,
            clientId: APP_CONFIG.OKTA_CLIENT_ID,
            redirectUri: APP_CONFIG.OKTA_REDIRECT_URL,
            i18n: {
                en: {
                    'primaryauth.title': 'Sign in to My App'
                }
            },
            authParams: {
                responseType: ['id_token', 'token'],
                issuer: `${APP_CONFIG.OKTA_BASE_URL}/oauth2/default`,
                display: 'page',
                scopes: APP_CONFIG.OKTA_CLAIMS.split(' ')
            }
        });
```

And here is the function to render widget on the sigin page
```
this.signIn.renderEl(
            { el: '#sign-in-widget' },
            (res) => {
                console.log(res); 
            },
            (err) => {
                throw err;
            }
        );
```

**Comment by janb87** [comment]
You could use the "pageRendered" event and then add some listeners to the dom elements.

I've attached a "submit" event listener to show my custom loader.
For knowing when an error occurs you can attach a MutationObserver to the error container (.o-form-error-container). Whenever this changed and gets a "o-form-has-errors" class you can hide it and you also know an error happened.

But this is more a workaround. It would be better to have this as real events on the widget in the api.

**Comment by jmelberg-okta** [comment]
This is a known feature gap that we're going to be fixing in the near future.

I've created a new issue (#549) to track all ongoing work related to providing the ability capture these type of events, so I'm going to close this issue for now.

Please leave a 👍 on that issue.
