### ISSUE TITLE
Sign-in widget issue

### ISSUE THREAD

**Issue by kwaynick** [okta/okta-signin-widget#476]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

Describe your issue or request here (if necessary).
Dev team is trying to clear out the password field on failed logins, so that if a user puts in an invalid password and walks away from their machine, the password field is empty, instead of having it retain their incorrect password.

According to the documentation for the Okta Sign in widget:

There are three kinds of errors that aren’t handled by the Widget, and so can be handled by custom code:
ConfigError
UnsupportedBrowserError
OAuthError

Based on this documentation, as well as our own testing, the error method that we can define as part of the call to renderEl will NOT be called on an invalid username/password, but rather only in the cases outlined above. If it were called on invalid username/password, then we would use jquery to empty the password field.

Given this limitation in the API, is there anything Okta can recommend to hook into the callback for a failed login to clear out the password?
### Expected behavior

What should have happened? 

### What went wrong?

Please provide log or error messages if applicable.

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

### Your environment

  - Okta Sign-In Widget Version:
  - Browser:
  - OS:
  - Language:

**Comment by jmelberg-okta** [comment]
This is a known feature gap that we're going to be fixing in the near future.

I've created a new issue (#549) to track all ongoing work related to providing the ability capture these type of events, so I'm going to close this issue for now.

Please leave a 👍 on that issue.
