### ISSUE TITLE
Bug Report: currentLanguage not cleaned up on remove()

### ISSUE THREAD

**Issue by joelfranusic-okta** [okta/okta-signin-widget#477]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

When calling `remove()` on the Okta Sign-In Widget, the `currentLanguage` section of the configuration is not cleaned up. 

A fix for this issue is in this PR: https://github.com/okta/okta-signin-widget/pull/446

This means that you can not change language strings between a `remove()` on a widget and a `renderEl()`

### Expected behavior

I should be able to change strings between `remove()` and `renderEl()`, then see the new strings after the `renderEl()`

**Comment by santhoshbalakrishnan** [comment]
Solved with https://github.com/okta/okta-signin-widget/pull/501. Would be available with the next release.
