### ISSUE TITLE
Feature Request: Derive all colors from a set palette

### ISSUE THREAD

**Issue by joelfranusic-okta** [okta/okta-signin-widget#482]
### I'm submitting a
  - [ ] bug report
  - [X] feature request

### User Story

As an IT admin or developer, I'd like to be able to specify a palette of colors that the widget will use everywhere, for example my company has a palette of 4 colors that I would like to see reflected in the widget.

**Comment by nbarbettini** [comment]
In https://github.com/okta/okta-signin-widget/pull/606 we are adding an optional `config.colors` section that will do exactly this, starting with a "brand" (primary) color that will affect the main buttons in the Widget.

**Comment by nbarbettini** [comment]
Closing this; will be released in https://github.com/okta/okta-signin-widget/milestone/1
