### ISSUE TITLE
Proposal: Convenience methods for signing in

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#487]
### Background
The Sign-in Widget can be used for many use cases, but the two most common are:
* Starting an Okta session (most likely followed by redirecting to the Okta dashboard)
* Signing a user into your own application

To accomplish these two tasks, you shouldn't need to understand the full Widget configuration model. I propose adding two convenience methods that will make these tasks much easier.

### showSignInToGetTokens

Define the options interface

```ts
interface SignInToAuthorizationServerOptions {
  authorizationServerId?: string;
  clientId: string;
  redirectUri?: string;
  getIdToken?: boolean;
  getAccessToken?: boolean;
  scope?: string | string[];
}
```

and `OktaSignIn.showSignInToGetTokens(options: SignInToAuthorizationServerOptions)` that performs the following "translation":

```js
let config = {
  clientId = options.clientId,
  redirectUri = options.redirectUri || "{current origin}",
  authParams: {
    issuer: options.authorizationServerId,
    responseType: buildResponseTypeArray(options.getIdToken || true, options.getAccessToken || false),
    responseMode: 'fragment'
    display: 'page',
    scopes: options.scope
  }
};

OktaSignIn.renderEl(config, DefaultSuccessHandler, DefaultErrorHandler);
```

#### Example

With this new convenience method, the [sign in to your application example](https://developer.okta.com/code/javascript/okta_sign-in_widget#sign-in-to-your-application) from the Widget Guide becomes much shorter:

```js
var widget = new OktaSignIn({
  baseUrl: 'https://{yourOktaDomain}',
  el: '#widget-container'
});

if (!signIn.token.hasTokensInUrl()) {
  widget.showSignInToGetTokens({
    clientId: '${clientId}'
    getAccessToken: true
  });

} else {
  signIn.token.parseTokensFromUrl(...);
}
```

### showSignInToStartOktaSession

Define the options interface

```ts
interface LoginToOktaOptions {
  redirectUri?: string;
}
```

and `OktaSignIn.showSignInToStartOktaSession(options: SignInToOktaOptions)` that performs the following "translation":

```js
let redirectingSuccessHandler = (res) => {
  if (!options.redirectUri) return;

  if (res.status === 'SUCCESS') {
    res.session.setCookieAndRedirect(options.redirectUri);
  }

OktaSignIn.renderEl(config, redirectingSuccessHandler, DefaultErrorHandler);
```

#### Example

With this new convenience method, the [sign into Okta with the default dashboard](https://developer.okta.com/code/javascript/okta_sign-in_widget#sign-in-to-okta-with-the-default-dashboard) example from the Widget Guide becomes shorter:

```js
var widget = new OktaSignIn({
  baseUrl: 'https://{yourOktaDomain}',
  el: '#widget-container'
});

widget.showSignInToStartOktaSession({
  redirectUri: 'https://{yourOktaDomain}/app/UserHome'
});
```

**Comment by jmelberg-okta** [comment]
Resolved with #503 and published into [`2.11.0`](https://github.com/okta/okta-signin-widget/releases/tag/okta-signin-widget-2.11.0)
