### ISSUE TITLE
Transactional information about the target from the underlying client

### ISSUE THREAD

**Issue by omgitstom** [okta/okta-signin-widget#490]
### I'm submitting a
  - [ ] bug report
  - [X] feature request

### Background info

Expose the auth-js client or the transactional information so I can get information about the state of the widget.

When the widget is loaded in Okta Hosted, or from a token (state, activation, otherwise) it would be great to be able to get the information out of the transaction:

`transaction.target.clientId`

For example this is how you do it with auth-js:

```
var authJs = new OktaAuth({url: orgUrl});
authJs.tx.resume({stateToken: '00oQMxcSBiopj6YLMTCVlhR'})
  .then(function(transaction) {
    console.log('current client:', transaction.target.clientId, transaction);
  }).fail(function(error){
    console.log('err', error)
  });
```

**Comment by RakeshCargill** [comment]
Tagging on for updates as we are also in need of this fix.

**Comment by nbarbettini** [comment]
**Use case 1**: when the Widget is initialized with an existing transaction, provide a way to get the transaction information.

The Widget can be initialized with a state token, like this:

```
let widget = new OktaSignIn({
  baseUrl: '...',
  stateToken: 'mYsTaTeToKeN'
});

widget.renderEl...
```

Or a recovery token like:

```
let widget = new OktaSignIn({
  baseUrl: '...',
  stateToken: 'rEcOvErYtOkEn'
});

widget.renderEl...
```

The recovery token is then exchanged for a state token.

In both cases, the Widget sends the state token to the Authentication API and gets transaction information back:

```json
{
   "stateToken":"00SpYMosv-p_5e11N2cnhL5ho6_oD0z8j7mnTAtkta",
   "expiresAt":"2018-09-13T02:48:50.000Z",
   "status":"RECOVERY",
   "recoveryType":"PASSWORD",
   "_embedded":{
      "user":{
         "id":"00ublkexampleRZLWl0h7",
         "passwordChanged":"2017-08-24T17:11:49.000Z",
         "profile":{
            "login":"user@example.com",
            "firstName":"Nate",
            "lastName":"Barbettini",
            "locale":"en",
            "timeZone":"America/Los_Angeles"
         },
         "recovery_question":{
            "question":"What is a good question?"
         }
      }
   },
   //...
}
```

A developer using the Widget may also want to use this transaction information. We should make it easy to retrieve this information once the Widget has it.

**Comment by nbarbettini** [comment]
**Use case 2**: when the Widget is in the middle of a transaction, provide a way to get the transaction information.

In a similar way to above, if a user is challenged for MFA in the Widget (or in any other situation where the Widget is used beyond primary authentication), a state token and therefore a transaction exists.

A developer using the Widget may want to use transaction information. We should make it easy to retrieve the latest transaction information via a method in the Widget.
