### ISSUE TITLE
Rendering problem on 2.10.0

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#515]
I want to make sure this [comment](https://github.com/okta/okta-signin-widget/issues/278#issuecomment-405936568) on #278 isn't lost.

> This is still happening on version 2.10.0. I can't use 2.5.0 due to the $.cookie is not a function error.
I tried the approach mentioned above, which is importing the widget (okta-sign-in-no-jquery)... I can leave it like this by now, but it would be great it you could look into this problem.

@quirogamauricio are you still running into this issue? If so, can you provide some more detail? Thanks!

**Comment by quirogamauricio** [comment]
@nbarbettini yes, i'm still running into the issue.
Ours is an Angular application. We have an `AuthService` class which is an Angular service that we use to manage user sessions.
In that class, if I import the widget like this
`import * as OktaSignIn from '@okta/okta-signin-widget'`

Then this is how it looks like (I replaced the logo)
![image](https://user-images.githubusercontent.com/8674040/43849492-f39d15fa-9b0b-11e8-9406-baecd96f7968.png)

But, if I import it like this
`import * as OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery'`, then it's rendered correctly.

```
npm ls @okta/okta-signin-widget

project@0.0.0 /route/to/project
└── @okta/okta-signin-widget@2.10.0
```

Let me know if you need additional data.

**Comment by nbarbettini** [comment]
Thanks, that's helpful. When it displays blank like that, are there any JS console errors?

**Comment by quirogamauricio** [comment]
No problem.
There are not errors nor warnings.
```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.2
Node: 8.11.3
OS: linux x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.8.3
```

**Comment by nbarbettini** [comment]
Do you have an example that you can share that reproduces the issue? (If you can't share your code, I understand)

**Comment by alexbonhomme** [comment]
I got the same problem that @quirogamauricio. No error in the console as well

If I use `import * as OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery'` it work properly.

**Comment by bretjb** [comment]
I'm seeing the same problem with the widget 2.13.0 on EmberJS.

I've got an Ember repo set up that shows the bug: https://github.com/bretjb/okta-test

You can see the widget setup I'm using here: https://github.com/bretjb/okta-test/blob/master/app/components/login-form.js

I'm not seeing anything render, but divs are being created on the page. Here's what's rendered into the DOM:
```
<div id="okta-container">
  <div data-se="auth-container" id="okta-sign-in" class="auth-container main-container no-beacon">
    <div class="okta-sign-in-header auth-header">
      <div data-type="beacon-container" class="beacon-container"></div>
    </div>
    <div class="auth-content">
      <div class="auth-content-inner"></div>
    </div>
  </div>
</div>
```

**Comment by hillj1895** [comment]
Same issue here. No console errors, just doesn't render. Replacing `import * as OktaSignIn from '@okta/okta-signin-widget'` with `import * as OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery'` fixes the issue.

**Comment by swiftone** [comment]
Thanks @hillj1895 for your helpful comment.  If anyone has this issue and that workaround does not not help, please comment as much. jQuery will be removed as a dependency in a later version so hopefully any disruption is temporary.

**Comment by jk-accetta** [comment]
Thanks @hillj1895, that fixed it for us, too!

**Comment by jk-accetta** [comment]
Using that workaround breaks when I build for production -- does Okta have any fix planned for this?

**Comment by swiftone** [comment]
@jk-accetta a new version of the signin-widget will be releasing in the near future that reduces the jquery dependency. We will update this issue when that occurs.

**Comment by mmazon** [comment]
Just for information purpose, I am using okta-signin-widget v2.20.1 and I still have to use the no jquery workaround to make it render the widget. 
But it breaks when I build to production with the `"buildOptimizer": true` and setting it to false got the job done.

**Comment by haishengwu-okta** [comment]
@mmazon would you like to try `3.0.*` to see if it fixes your problem?

**Comment by sparachi** [comment]
I'm working with 3.2.0 version and had to struggle for a day to figure out why the widget was not rendering. There was just one horizontal line and no console errors. When I moved the 
this.widgetObject.renderEl() to ngAfterViewInit instead of ngOninit did the trick and it started to load.

**Comment by swiftone** [comment]
@sparachi - Thanks for the clarity.  It's likely you are correct - if the widget rendering and your own angular rendering are in a race, the wrong side might win.  

Our sample is using ngOnInit (https://github.com/okta/samples-js-angular/blob/master/custom-login/src/app/login/login.component.ts#L50) and works (in our testing), but there could be some environmental difference.  Which version of angular are you using?

**Comment by swiftone** [comment]
Closing for lack of response - if someone is reading this and having a similar issue, please open a new issue and reference this one in the report (and provide environmental details).
