### ISSUE TITLE
Cookie missing when using custom button to link to SAML2 IDP

### ISSUE THREAD

**Issue by ryanbowensms** [okta/okta-signin-widget#525]
### I'm submitting a
  - [ ] bug report/question

###### Packages used:
  @okta/okta-angular: "1.0.1",
  @okta/okta-signin-widget: "2.5.0",

Apologies if this is not a bug but incorrect use of the widget.

We are trying to use the sign in widget to allow authentication to our Angular SPA via external SAML 2.0 IDP (G Suite). All the documentation seems to point in the direction of using a custom button and setting the click handler to link to a custom authorise URL.

`https:// <your_okta_url> /oauth2/v1/authorize?idp= <IDP_ID> &client_id= <Client_ID>&response_type=id_token&response_mode=fragment&scope=openid&redirect_uri=<redirect_url>`

This seems to work - it logs in to Okta via G Suite and then redirects back to the Application.
However, when redirecting back to the `OktaCallbackComponent` it calls `handleAuthentication()` which expects that there is a `okta-oath-redirect-params` cookie set when it calls `ParseFromUrl()`. The cookie is not set so the flow fails with 'Unable to parse Tokens from URL'

We can set the cookie and get the whole flow to work if we call `getWithRedirect()`:

```javascript
customButtons: [
        {
          title: 'Login with Google (SAML IDP)',
          className: 'btn-customAuth',
          click: function() {

            /* documented custom button approach -- flow fails as no cookie set */
            // window.location.href = https:// <your_okta_url> /oauth2/v1/authorize?idp= <IDP_ID> &client_id= <Client_ID>&response_type=id_token&response_mode=fragment&scope=openid&redirect_uri=<redirect_url>

            /* not documented but seems to work */
            oktaAuth.token.getWithRedirect({
              scopes: [
                'openid',
                'email',
                'profile'
              ],
              responseType: ['id_token', 'token'],
              response_mode: 'fragment',
              token_type: 'Bearer',
              state: 'randomstring',
              nonce: 'randomstring',
              idp: '<IDP_ID>'
            });
          }
        }]
```
*Q*. Is this approach correct, We can't find any documentation for this use case to confirm if we can implement this in production?

Also we will eventually look to use the IDP discovery (Early access feature).
From looking at the documentation around this it seems like we may run into the same issue with the cookie not being set if we use `res.idpDiscovery.redirectToIdp()`.

### Expected behavior

Some clearer documentation for this scenario

### Your environment

  - Okta Sign-In Widget Version: 2.5.0
  - Browser: Chrome
  - OS: macOS High Sierra 10.13.3
  - Language: JS

**Comment by jmelberg-okta** [comment]
Hi @ryanbowensms!

Thanks raising this question.

First, it appears you are using Okta's [OpenID Connect API](https://developer.okta.com/docs/api/resources/oidc) for authentication, as opposed to SAML. If you're looking for SAML support - you'll need to move away from the `@okta/angular` library, as it only supports OAuth 2.0 and OpenID Connect flows.

Second, the Widget handles the request implementation for you - so you shouldn't need to override it with the `getWithRedirect` method. See [this forum post](https://devforum.okta.com/t/okta-sign-in-widget-with-google-social-login/1252) for an example.

If that forum post does not resolve your issue, please feel free to respond in the forum thread.

Thanks!
