### ISSUE TITLE
Invalid 'Access-Control-Allow-Origin' header value

### ISSUE THREAD

**Issue by stormit-vn** [okta/okta-signin-widget#541]
### I'm submitting a
  - [x ] bug report
  - [ ] feature request

### Background info

I am usinng this widget to sign in to Okta. We use the same Okta account for both development and testing environment. The development environment is running at http://localhost:3000 and testing is running at https://example.com.

The sigin feature is working properly in my local environment, but when we try to login to our test environment we are getting below error

`
implicit/callback:1 Failed to load https://oktadomain.oktapreview.com/oauth2/default/v1/keys: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin. Origin 'https://example.com' is therefore not allowed access.
polyfills.74f394a5c1…5769e125.chunk.js:1 Uncaught Error: Uncaught (in promise): AuthApiError
Error
    at Object.YhKr (main.8683cd6….chunk.js:1)`

If we clean all cache, then we will able to login to http://example.com, but after that we will not able to login to our http://localhost:3000

### Expected behavior

We should able to signin to both environment

### What went wrong?

See above description. Note, it will be no issue when we use Okta Sign-In widget 2.11.0 and Okta angular 1.0.1.

### Steps to reproduce

See above description

### Your environment

  - Okta Sign-In Widget Version: 2.13.0
  - @okta/okta-angular: 1.0.3
  - Browser: Chrome latest version
  - OS: Mac OS
  - Language: JavaScript

**Comment by stormit-vn** [comment]
For more details, I worked with @okta/okta-angular: 1.0.1

**Comment by jmelberg-okta** [comment]
Hi @stormit-vn -

Thanks for the report! We're working with our API team to investigate this further. We'll keep this issue updated as information becomes available.

Thanks!

**Comment by fabiangarga** [comment]
Same issue is happening with okta-angular v1.04.
I guess this is related to the Okta API response, and not the plugins that handle the integration, and more specific with the cache of the response.

If we inspect the response headers that the API from Okta is returning it doesn't includes the 'vary' response header that indicate the browsers the responses can differ based on the value of the origin  that generated the request.

Any updates on this fix?

**Comment by Wilson-Hung-DrumG** [comment]
Same issue here

**Comment by awumsuri** [comment]
Same issue.

**Comment by roski** [comment]
same

**Comment by ajheunis** [comment]
Seemingly same issue, but with @okta/okta-react: 1.1.1.

**Comment by haishengwu-okta** [comment]
Did you enable CORS for both url?

**Comment by Wilson-Hung-DrumG** [comment]
There is a another similar question, where the poster pinned @okta/okta-react to 1.0.1 (we had it as ^1.0.3).  This fixed our issue, i.e., setting @okta/okta-react: 1.0.1

**Comment by bartimaeus** [comment]
@stormit-vn what version of `okta-auth-js` are you using? I ran into a similar issue and discovered that I had to lock my `okta-auth-js` to `1.17.0` to work with `okta-signin-widget`. The later versions of `okta-react` and `okta-angular` use the newer `okta-auth-js:^2.0.0` which does not work with `okta-signin-widget` yet.

```
"@okta/okta-auth-js": "^1.17.0",
"@okta/okta-react": "^1.0.2",
"@okta/okta-signin-widget": "^2.13.0",
```

**Comment by jmelberg-okta** [comment]
Hi all -

Our API team is working on addressing this issue this month. We're tracking the status of the work internally, so I'll update this issue as status updates become available.

**Comment by paulux84** [comment]
Hi all, any update on this bug?

**Comment by jmelberg-okta** [comment]
@paulux84 & others,

Our API teams are **actively** working on this issue. Once the work is completed, I'll be informed when this fix hits production.

Thanks for your patience!

**Comment by jmelberg-okta** [comment]
Hi all,

Wanted to quickly chime in with an update.

Our API teams have merged a fix for this issue, and have rolled it out to preview organizations (`*.oktapreview.com`) this week. Next week, it'll be available for all Okta orgs.

Thanks for your patience - and please keep us updated if issues persist.

**Comment by dotnetcoder01** [comment]
I am in an oktapreview domain and I am still getting this issue.  I have multiple apps in my okta instance each with their own client ID.  I modified the names of the urls for this post.

Access to XMLHttpRequest at 'https://dev-XXXXXX.oktapreview.com/oauth2/default/v1/keys' from origin 'https://project-val.XXXXXX.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://project-dev.XXXXXX.com' that is not equal to the supplied origin.

**Comment by paulux84** [comment]
same for me

**Comment by Saithorat** [comment]
still an issue, any updates ?

**Comment by owenmecham** [comment]
The trust incident is listed as resolved. Since this issue is still open, are you still working on finding a solution?

**Comment by owenmecham** [comment]
Currently, the impact to developers or production users that access both our beta and prod environments is that in order to switch from one site to another, the user has to manually clear their browsing data. This is a big deal for us. Any eta on a fix or a status update would be greatly appreciated.

**Comment by reste85** [comment]
Same issue here. We have 2 SPA and we're using the same authorization server for both. In particular we have 3 authorization servers, one for each environment. When i log into an SPA, i can't login into the second one. I've already opened cases on okta forum, i think this issue is completely related to the api part (seems like the browser is caching the "keys" request with the Allow-Control-Origin header value). 
The only workaround i see is to use separate authorization servers for each SPA and for each environment, so if you have 3 environments and 2 SPA --> 6 authorization servers.

**Comment by AmihaySchwarz** [comment]
@jmelberg-okta ,  according to [this](https://trust.okta.com/#incident/a9C1Y000000GpJuUAK) the matter should have resolved but we still have this issue, I see that others also have this issue. 

Can u please update us?

**Comment by nbarbettini** [comment]
Sorry for the delayed response, and thanks for all your patience.

> Since this issue is still open, are you still working on finding a solution?

Yes, we are close to a fix for this problem ("The 'Access-Control-Allow-Origin' header has a value that is not equal to the supplied origin"). We'll update and close this issue when it is fully resolved.

**Comment by chrisipeters** [comment]
I'm on a preview account, seeing the CORS issue as reported at:
https://devforum.okta.com/t/cors-blocked-access-control-allow-origin/3807

is this the same issue being worked on here?

**Comment by nbarbettini** [comment]
@chrisipeters Yes, looks like the same issue. We are releasing a fix soon.

**Comment by jeremypepper** [comment]
@nbarbettini  Do you have a specific date on when we can expect a fix?
Any idea why opening your chrome debugger and hitting "Disable cache" is a workaround for this issue (at least for devs)?
Is there any workaround we can do until this is fixed for real?

**Comment by jeremypepper** [comment]
Oh i see. It's the /oauth2/v1/keys endpoint that gets cached on disk with the old origin. Unfortunately it's response header has:
Cache-Control: max-age=2178861, must-revalidate

Which comes out to 25 days. So even after this fix is done on your side, there may be a gap of 25 days for this to fully be resolved on all clients right?

**Comment by jeremypepper** [comment]
I added a pull request for a workaround I made that seems to work if anyone wants it:
https://github.com/okta/okta-auth-js/pull/186

**Comment by kylebuckingham** [comment]
Hey @jmelberg-okta  - any update on this? Is there a reason why @jeremypepper 's solution won't work? This is quite frustrating - more details may help us arrive at a solution

**Comment by jeremypepper** [comment]
@kylebuckingham We've been directly using the workaround in our forked repository. You are welcome to use it. You just need to update your package.json to use the checkin with the workaround
```
    "pepperdata/okta-auth-js": "https://github.com/pepperdata/okta-auth-js.git#f334ba71ef1064af8114aa0b9cf5fc0927ef062d",
```
I also had to update my webpack to build the config file in package.json:

```
scripts: {
  "build": "node node_modules/pepperdata/okta-auth-js/writeConfig.js && webpack ...
```
and finally where I used okta auth I replaced the dependency:

```
import OktaAuth from '@okta/okta-auth-js';
```

to:

```
import OktaAuth from "pepperdata/okta-auth-js/lib/index";
```


This bug was said to be fixed "ASAP" as of Dec 11, 2018. We couldn't wait longer so we had to do this workaround.

**Comment by kylebuckingham** [comment]
Thanks for doing this @jeremypepper. We've implemented something similar, but these workarounds and not permanent solutions, and we need a real answer. We spoke with the support team in October/November about it, and it would be great if they would give us details why its still blocked so I don't break my keyboard in rage next time I hit this.

**Comment by owenmecham** [comment]
@jmelberg-okta does release 2.3.0 address this issue in any round about way? I haven't looked through the entire merge yet to see. Any transparency on the status of this issue would be greatly appreciated. Implementing work arounds for this is frustrating and complete throw away work.

**Comment by rk-7** [comment]
We're facing same issue with our SPA app. There are different environments including dev for which we're using the same Okta app. This is very frustrating. We have to clear data (cache, cookies, data) of the previously logged in site/URL and then login to the other environment.

**Comment by owenmecham** [comment]
@rk-7 follow the work around that @jeremypepper put together. We had to make small tweaks but the approach worked for us. We couldn't wait any longer either. We had multiple environments in production for beta users and had to take action.

**Comment by mderoche** [comment]
@nbarbettini Any news on this issue?

**Comment by Saithorat** [comment]
@mderoche There is a workaround by @jeremypepper and it worked for us.
This is so bad that okta isn't taking this issue seriously enough. This issue was a big showstopper for us.
Glad its resolved with the workaround

**Comment by nbarbettini** [comment]
We have a fix for this issue and are rolling it out slowly. Please reach out to support@okta.com to get the CORS Vary feature enabled early if you want to try it before it is rolled out to everyone.

When the rollout is complete, it will "just work" automatically, on all Okta domains.

Really sorry for the lack of apparent progress here. Since this endpoint is used by many clients, we are rolling the fix out slowly to make sure that we fix the right thing (and don't cause any bad side effects). Thanks for your patience, and definitely reach out to support (above) if you need it ASAP.

**Comment by DavidLozzi** [comment]
What's the ETA on the "just works"?

**Comment by ptagl** [comment]
I'm facing the same issue and tried to apply the changes from @jeremypepper pull request but still it's not working.

I am trying to use the sample [Okta Angular webapp](https://github.com/okta/samples-js-angular/tree/master/okta-hosted-login), downloaded it, installed the packages and then changed

`var jwksUri = wellKnown['jwks_uri'];`

to

`var jwksUri = wellKnown['jwks_uri'] + "?now=" + Date.now();`

in file _node_modules/@okta/okta-auth-js/lib/oauthUtil.js_.

Should I do anything else before running ng server? The error I get is:

`Access to XMLHttpRequest at 'https://flexdev.oktapreview.com/oauth2/default/.well-known/openid-configuration' from origin 'http://localhost:60611' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by bfriel** [comment]
Hi @nbarbettini , any update here?

**Comment by Saithorat** [comment]
@bfriel This is fixed at our company, but looks like OKTA is rolling out the fix slowly and you need to reach out to okta support to get this rolled out for your company.

**Comment by owenmecham** [comment]
@Saithorat any side effects from the change that you've noticed or has it been good ever since the fix?

**Comment by nbarbettini** [comment]
@DavidLozzi No public ETA, but we are making progress. It is an Okta fix (not a code/component fix in this library).

We've turned this flag on for many customers who have sent email requests (see my post above) and so far everything looks good. Still making progress on wide rollout. Thanks for your patience.

**Comment by Saithorat** [comment]
@owenmecham No issues on our end, 15000+ users on each site, across 6 different sites.

**Comment by cx41546** [comment]
@nbarbettini Has this Okta fix been completely rolled out?

**Comment by swiftone** [comment]
@cx41546 - No, the change is not yet set for all customers, but you can request it for your org immediately:

`Please reach out to support@okta.com to get the CORS Vary feature enabled early if you want to try it before it is rolled out to everyone.`

**Comment by nbarbettini** [comment]
Follow-up: this is live for everyone. If you see further issues about `Access-Control-Allow-Origin`, please reach out to support@okta.com. Thanks for your patience everyone 🙂

**Comment by zrven** [comment]
We are still having CORS issue. Anyone else in a similar boat? I can't believe it's open since many months.

**Comment by rcollette** [comment]
Out of habit, I had configured the baseUrl property of the widget with our custom authorization server base url.  Same CORS type error message on the call to the /authn api.   The baseUrl property should actually be just protocol and host portion of the URL, nothing else.

**Comment by krinonnn** [comment]
I just went through the tutorial and got the same exact issue. Was this resolved?

**Comment by diabai** [comment]
I'm having the same issue, anyone knows a workaround ?

**Comment by diabai** [comment]
I'm having the same issue.

**Comment by krinonnn** [comment]
> I'm having the same issue.

Hey @diabai - i ended up using Auth0 - pretty straight forward guide with no issues like this one.

**Comment by diabai** [comment]
@krinonnn can you please post a link to the Auth0 example you're referring to ?

**Comment by diabai** [comment]
> > I'm having the same issue.
> 
> Hey @diabai - i ended up using Auth0 - pretty straight forward guide with no issues like this one.

Alright Auth0 to the rescue.

**Comment by Dazztian** [comment]
Hacing this issue

**Comment by Dazztian** [comment]
I'm also experiencing this issue

**Comment by joeythelantern** [comment]
Also having this issue

**Comment by joeythelantern** [comment]
Why is this closed?

**Comment by vahedq** [comment]
Same issue here.

**Comment by diabai** [comment]
I used AuthO instead.

**Comment by joeythelantern** [comment]
I am with OKTA for reasons beyond my control, so I need OKTA to figure out what's going on in this widget.

**Comment by blake-edens** [comment]
"As of Firefox 68, https pages are not permitted to access http://localhost, although this may be changed by Bug 1488740."

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
https://bugzilla.mozilla.org/show_bug.cgi?id=1488740

Dropping these links for anyone using firefox, it appears that localhost requests to an https domain are blocked by the browser itself, not the Okta API.

**Comment by rbivens1** [comment]
I'm getting the same CORS error when I try to use the "Sign Up" link on the widget. The Sign In link works fine. I'm still using localhost:4200.

- Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- "@okta/okta-angular": "^2.1.0"
- "@okta/okta-signin-widget": "^4.2.1"

I get the same CORS error using:
MS Edge Version 83.0.478.64 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/41482956/87795148-a23d0d80-c815-11ea-9f71-16d3738fd31a.png)

![image](https://user-images.githubusercontent.com/41482956/87795335-e4fee580-c815-11ea-9638-3246324a61ad.png)


Is there a need to request something from okta before this works?

**Comment by gautamc1106** [comment]
Still facing this issue, despite adding to the Trusted Origins list. Weirdly I didn't face it instantly but only after reloading once or twice and then it didn't go away. Any help would be appreciated.

**Comment by TaylorNoelJordan** [comment]
Also having the same issue. Any update?

**Comment by lifenautjoe** [comment]
Why is this issue closed? There's tons of people having this issue.

**Comment by rbivens1** [comment]
I decided to switch to Firebase Authentication.

**Comment by glenkitchen** [comment]
Comment above from @blake-edens helped resolve issue for me.

Not 100% sure, but some browers seem to show a CORS error when accessing localhost on http, from https.

For me error occurred on Edge v86.
Used Chrome v86, no issue.  

This may not be an okta issue.

**Comment by sasiperi** [comment]
It appears to be Okta issue. I tried with my SPA (angular), in Chrome, I still get CORS error, even after adding localhost:4200 (which is where my app runs) to "trusted origins". KeyCloak for example works.

**Comment by swiftone** [comment]
@sasiperi - 

> I tried testing using this link : developer.okta.com/docs/guides/enable-cors/testing too, by "tracking blockers turned off"

Can you elaborate somewhat?   You:
- added "https://developer.okta.com" to your organization as a trusted origin, with CORS checked
- logged in to your organization via okta
- in that same browser, put the link to your org in the page above

?

What error did you receive?  What does the network DevTools show for the failing call?

**Comment by sasiperi** [comment]
Here is the error.
![image](https://user-images.githubusercontent.com/20564409/103235816-feea3b80-4910-11eb-88e0-09420256d5ed.png)

![image](https://user-images.githubusercontent.com/20564409/103235964-6bfdd100-4911-11eb-9439-7b120e55f4d2.png)

**Comment by swiftone** [comment]
That is the error from localhost, but what about the test page?  In that case the origin should be developer.okta.com.

Can you confirm you did the 3 steps listed in the previous message and show the network calls there?  We aren't aware of any CORS issues in general, so this suggests there's something in the configuration for your organization that needs a change.

**Comment by sasiperi** [comment]
I am experimenting with the free dev account. 
Screen-shot-1, showing my trusted origins
![image](https://user-images.githubusercontent.com/20564409/103236569-3a860500-4913-11eb-854f-fb9b96e11134.png)

Here is the error (same as the one I get with my SPA)

![image](https://user-images.githubusercontent.com/20564409/103236919-2bec1d80-4914-11eb-889b-e0fde982ce65.png)

**Comment by swiftone** [comment]
the `-admin` part of that url is not in the "real" issuer, that's just used for the admin website you are using.  Try putting just the `https://dev-WHATEVER.okta.com` in the form field.  

Also leave off the trailing `/` - that part shouldn't make a difference, but just in case, make sure.

**Comment by sasiperi** [comment]
-admin is the problem(did not notice, I copied that part). Removing it works (with and without /)

**Comment by joeythelantern** [comment]
For all those who have to use a client side framework (like react) and need the the app showing up as a tile, I have completely bypassed the react okta sdk and used SAML with a small express backend.  I went this route because of issues like this not being solved:

https://github.com/joeythelantern/React-SAML-Auth

There is a video on how I did it in the description of the repo.

Cheers.

**Comment by Kizziah** [comment]
CORS for a real web app is still broke? Working on the OKTA test site is different then localhost or a live app.
