### ISSUE TITLE
How do I change the validation error messages for text fields?

### ISSUE THREAD

**Issue by rodoabad** [okta/okta-signin-widget#546]
Hey guys,

Just a general question. How do I use a custom message when validation fails?

Here's a quick example.

<img width="377" alt="screen shot 2018-09-20 at 2 26 07 pm" src="https://user-images.githubusercontent.com/1240667/45842045-2f2de300-bce1-11e8-9a84-0e66a9f7d054.png">

I would like to change the "Please enter a username".

...

The page I'm trying to change is when a user is entering a new password. I would like to display a validation error like "No special characters allowed, you can only use X, Y, and Z".

Thanks!

**Comment by jmelberg-okta** [comment]
Hi @rodoabad!

You can modify the error fields by directly updating the [`i18n` property](https://github.com/okta/okta-signin-widget#language-and-text).

For example:

```javascript
var options = {
  baseUrl: 'https://{yourOktaDomain}',
  i18n: {
    en: {
      'error.username.required': 'No special characters allowed, you can only use X, Y, and Z'
    }
  }
};
var signIn = new OktaSignIn(options);
```

Any value here should be able to be modified: [`login.properties`](https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/dist/properties/login.properties)
