### ISSUE TITLE
Improve IdP Discovery interface when acting as OIDC client

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#566]
### I'm submitting a
  -  feature request

### Background info

Given this configuration:

```js
var signIn = new OktaSignIn({
  el: "#widget",
  baseUrl: 'https://{yourOktaDomain}',
  idpDiscovery: {
    requestContext: '/a/app/request/context',
  },
  features: {
    idpDiscovery: true
  }
});
 
signIn.renderEl(
  function (res) {
    if (res.status === 'IDP_DISCOVERY') {
      // idpDiscovery.redirectToIdp knows the authentication URL for the selected IdP.
      // This will redirect to that authentication URL, and include someUri as a query param: ?fromURI={someUri}
      res.idpDiscovery.redirectToIdp(someUri);
    }
  }
);
```

The Sign-in Widget will query Okta (IdP Discovery) to determine whether it should redirect to another IdP to sign the user in.

### Feature gap

If the Widget is self-hosted by an application and is acting as a client (i.e., configured with a client ID), and the intent is to get tokens from Okta and return to the application with these tokens, the `redirectToIdP` method is not quite sufficient.

There is no way to tell the Widget and server: redirect to the target IdP to sign the user in, and afterward get tokens and return them to my application.

More background here: https://oktawiki.atlassian.net/wiki/spaces/~nate.barbettini/pages/585238829/IdP+Discovery+self-hosted+Sign-in+Widget+tokens+for+an+OIDC+client

### Solution

Add a method like `res.idpDiscovery.continueAndGetTokens()`

Behavior:

1. Construct an authorize URL following the logic in Auth.js getWithRedirect
2. Drop the expected cookies in the browser, following the logic in Auth.js getWithRedirect
3. Behave like redirectToIdp with the authorize URL from (1)

continueAndGetTokens can be thought of as a special case of redirectToIdp that understands how to construct the correct redirect authorize URI (and sets the correct cookies). We may be able to simply use  Auth.js to do this with the existing getWithRedirect method.

This is very similar to what the Widget does for social login: https://github.com/okta/okta-signin-widget/blob/master/src/util/OAuth2Util.js#L34-L96

**Comment by nbarbettini** [comment]
Holding pending the outcome of this discussion: https://oktawiki.atlassian.net/wiki/spaces/eng/pages/244854014/IDP+Discovery+support+in+the+Sign+in+Widget

**Comment by yowzadave** [comment]
What is the current status of this feature? We're attempting to implement idpDiscovery via Okta, but the above links w/ further explanation are limited to the private Okta wiki.

**Comment by nbarbettini** [comment]
Hey @yowzadave, sorry for the lack of info above. It's something we have investigated, but is not fixed. The Widget does not currently support identifier-first (`features.idpDiscovery`) when you're hosting a sign-in page in your own application. It should work fine with an [Okta-hosted sign-in page](https://developer.okta.com/docs/guides/custom-hosted-signin/overview/).

**Comment by devinnate** [comment]
We worked around this issue by:

1. Making a standard idpDiscovery login widget (okta hosted), which redirects to

2. A ‘bookmark’ in okta, which points to a,

3. OIDC app using okta auth js, which determines it doesn’t have OIDC tokens, which redirects back to itself with tokens. 

This supports:
1. Full idp discovery with identifier first login,
2. Idp initiated inbound sso

This costs:
1. 2 extra redirects at login. 

I can explain more if it helps. It’d be nice if okta described this formally as I don’t think anything we are doing is unsupported or ‘hacky’. It would be nice to eventually remove the 2 extra redirects tho. 

Thanks,

**Comment by swiftone** [comment]
@devinnate, thanks for the well-described work around!

I'll look around to see if we can uncover if this feature is on the Okta timeline in the near future, but in the meantime your solution seems quite logical to me.

**Comment by TCDooM** [comment]
Any updates on this issue?
Is there any documentation on this flow?
Thanks.
Tomer.c@Quali.com

**Comment by swiftone** [comment]
@TCDooM - unfortunately, this issue is not on our current priority list, and outside of the links in the above comments, we don't have additional documentation.  If you have specific questions about IdP Discovery, you may find answers via our forums ( https://devforum.okta.com/ ).

**Comment by Chintagious** [comment]
I was able to figure out a workaround, with only a single redirect; the only downside being that...
- it makes a call to the `webfinger` endpoint twice (which is easy to live with)
- if NOT using JIT for your IdP Auth Settings, the user will be redirected to your Okta sign-in page, instead of the page that initiated the request and hosts the sign-in widget

What I had to do was create an instance of both Okta Auth JS v2.0.1 (only to use for IDP discovery related stuff), and the Okta Sign-in Widget v2.21.0.

Our use case is to have a custom login page with a sign-in widget, discover the IDP of the user, redirect to that IDP and allow the user to log in, then return back to the same page with the token.

Sign-in Widget Config:
```js
let oktaSignInConfig = {

    // ... Rest of your configs

    idpDiscovery: {
        requestContext: window.location.href
    },
    features: {
        idpDiscovery: true
    },
    transformUsername: function(username) {
        let expireInSecondsFromNow = 120;
        let expireIn = new Date();
        expireIn.setTime(expireIn.getTime + (expireInSecondsFromNow * 1000));

        // Need to set this cookie so we can make sure that the username that was typed in will match the token user that gets returned
        // Issue was that if the user was redirected to the IDP, but was logged in as a different user, the IDP would return immediately with the wrong token
        _setCookie("userToLogin", username, expireIn, '/', 'MY_DOMAIN');

        return username;
    }
}
```

Widget logic:
```js
signIn.renderEl(
    {el: '#widget-container'},
    function(res) {
        if (res.status === 'IDP_DISCOVERY') {
            _discoverIdPAndRedirect();
        }
    },
    function(err) {
        // Handle error ...
    }
);

function _discoverIdPAndRedirect() {

    oktaAuthClient.webfinger({
        resource: 'acct:' + _getCookie("userToLogin")
    }).then(function(res) {
        try {
            _cleanUpOktaCookies();
            oktaAuthClient.token.getWithRedirect({
                scopes: [
                    'openid',
                    'email',
                    'profile'
                ],
                idp: res.links[0].properties["okta:idp:id"],
                responseType: ['id_token', 'token']
            });
        } catch(err) {
            // Handle error ...
        }

    }).fail(function(err) {
        // Handle error ...
    });
}

// Needed to remove these cookies in case redirect params were set, but redirect resulted in an error -- want a clean slate to work from
function _cleanUpOktaCookies() {
    (_getCookie("okta-oauth-state")) ? _deleteCookie("okta-oauth-state") : null;
    (_getCookie("okta-oauth-nonce")) ? _deleteCookie("okta-oauth-nonce") : null;
    (_getCookie("okta-oauth-redirect-params")) ? _deleteCookie("okta-oauth-redirect-params") : null;
}
```

Then to handle the token that gets returned on redirect back:
```js
if (signIn.token.hasTokensInUrl()) {        
    signIn.token.parseTokensFromUrl(
        function success(res) {
            _setFormAndSubmit(res[1].accessToken);
        },
        function error(err) {
            // If the Okta Auth SDK throws an exception with parsing from the URL, then manually parse it and log the user in, if possible
            _parseFromHashAndSubmitIfExists();

            // Since parsing failed, must allow user to log back in..
            _renderSignInWidget();
        }
    );
}

function _parseFromHashAndSubmitIfExists() {
    if (!window.location.hash) {
        return;
    }

    let hashArray = window.location.hash.replace("#", "").split("&");
    let hashJson = {};
    for (let i = 0; i < hashArray.length; i++) {
        let splitHash = hashArray.split("=");
        hashJson[splitHash[0]] = splitHash[1];
    }

    let accessToken = hashJson['access_token'];
    if (accessToken) {
        _setFormAndSubmit(accessToken);
    }
}
```

I should note that I had to add this logic on initial page load, prior to instantiating the widget:
```js
    // When using an IdP, the cookie returns partially encoded, which causes okta auth sdk to fail its parsing of the cookie
    if (_getCookie("okta-oauth-redirect-params")) {
        document.cookie = "okta-oauth-redirect-params=" + decodeURI(_getCookie("okta-oauth-redirect-params")).replace(/\%2C/g, ",");
    }
```

devinnate's description wasn't very clear to me, but helped set me on the right direction, so thanks to them!

**Comment by rcollette** [comment]
The problem with the solution that @Chintagious provides here, which otherwise would be incredibly useful to me at the moment, is that the current version of the widget (4.1.3), does not call any of the normal callbacks such as transformUsername, processCreds, or the result handling function.   I have tried breakpointing and console logging in these functions and nothing happens.  So there isn't a standard way of hooking the idpDiscovery functionality currently.
