### ISSUE TITLE
Can't Auth into Okta via Chrome Extension.

### ISSUE THREAD

**Issue by Alexwinding** [okta/okta-signin-widget#568]
### Background info

Hello.
We have an extension app for chrome and we decided to integrate okta AWS authentification (we want to simplify the auth process and make it safe for our customers).

Unfortunately, we receiving a sign-in error.

### Expected behavior

Successful sign in

### What went wrong?

The issue happens in redirecting after success login and we receiving "400 - bad request" from them https://monosnap.com/file/GYflfeTbhWCGhC8meHMuPtwMx6xZQ0

The error was while the redirect on this url {domain}/oauth2/default/v1/authorize? {our ids, e.t.c}
Another thing I noticed, was responding error 404 when OktaSignIn trying to connect to {domain}/api/v1/sessions/me

### Steps to reproduce

400 error page right after "Sign in"

### Your environment

  - Okta Sign-In Widget Version: 2.13.0
  - Browser: chrome 69.0.3497.100
  - OS: OSX Mojave 10.14
  - Language: English

**Comment by nbarbettini** [comment]
Hey @Alexwinding, sorry for the delay. I don't think this is a Sign-in Widget issue, it sounds like a configuration problem somewhere else. Seeing 404 from OktaSignIn is normal if the user doesn't have an existing session.

Can you post your question on https://devforum.okta.com and include some more detail about the failing requests, and how you have Okta/your application set up?
