### ISSUE TITLE
Authentication Factors dropdown stays hidden

### ISSUE THREAD

**Issue by AsimCBS** [okta/okta-signin-widget#574]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

We sign in by providing username and password, then we are asked for the second factor but the dropdown that lets us choose from the authentication factors, stays hidden. 

### Expected behavior

the multiple authentication factors dropdown should me displayed so that user could select from the multiple authentication factors dropdown. in my case i have three configured. SMS Authentication, Google Authenticator and Securety Question. 

### What went wrong?

We sign in by providing username and password, then we are asked for the second factor but the dropdown that lets us choose from the authentication factors, stays hidden. 

### Steps to reproduce

Make sure more than 1 authentication factor is configured for you. 
Sign in using Okta
On the second factor step, the multiple authentication factors dropdown stays hidden.
if you use developer tools of the browser and modify the css style #okta-sign-in .okta-sign-in-header by removing display:none. or change it to block. it displays the dropdown and the factors work as expected.

### Your environment

  - Okta Sign-In Widget Version: 1.7.0 as well as 2.13.0
  - Browser: Chrome, IE
  - OS: Windows
  - Language:

**Comment by nbarbettini** [comment]
Can you show the code you are using to render the Sign-in Widget? If we can reproduce this issue we can take a look. I've successfully used the Widget with multiple factors before and it's working for me, so there must be something else going on.

**Comment by jmelberg-okta** [comment]
Hi @AsimCBS,

Is this happening **after** the user has completed enrollment for **multiple** MFA factors? If a user enrolls in **only one** factor, that would explain why other options are not appearing. We only populate the dropdown with a list of factors the user has opted into.

If this isn't the case, can you please provide us more reproduction steps? Ideally which MFA factors are enabled and selected by a user.

**Comment by AsimCBS** [comment]
sorry for the confusion but it was the custom css that caused the issue. Fixing the custom css addressed it. thanks for the help.
