### ISSUE TITLE
Initialize Widget directly in registration view

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#587]
### I'm submitting a
  -  feature request

### Background info

When I am building a registration page or have a registration button, I need to be able to render the Widget directly in the registration view (skipping the primary auth view).

**Comment by haishengwu-okta** [comment]
hi @nbarbettini , could you share the background why developers like this feature?

**Comment by nbarbettini** [comment]
@haishengwu-okta Controlling which view the Widget starts in is important for folks building their own sign-in pages.

For example, one requirement is: as a developer, I am building separate sign-in and registration pages. On the registration page, I need to show the Widget's registration view. Using `features.router` and the "magic" path `/signin/register` is not always feasible for single-page apps, or when I want more control over the URL.

I've detailed the user stories here: https://oktawiki.atlassian.net/wiki/spaces/PM/pages/590550736/Get+and+set+the+Widget+view

**Comment by dbredvick** [comment]
Hi @nbarbettini and @haishengwu-okta - any chance this will be completed soon? Also curious if you know of any workarounds until this change is implemented. Thanks!

**Comment by dbredvick** [comment]
Bump

**Comment by haishengwu-okta** [comment]
@dbredvick 
> Using `features.router` and the "magic" path `/signin/register`

That's an workaround if sounds plausible to you.

----
1. set `features.router` to true
2. bootstrap widget with `/signin/register` url instead of default `/`

**Comment by afunnydev** [comment]
Any news on this? Using the workaround for now, but this looks like a must for custom sign in/sign up pages! Thanks :)

**Comment by swiftone** [comment]
@afunnydev - No particular update at this time.  If you have any particular business case you want to share with your support contacts, I'm sure they'd appreciate the information and feed it to the appropriate contacts.  

If the workaround isn't working for you, please open a new ticket with the specifics.  As it appears the listed solution works for most folks for the past year, I'm closing this specific issue.

**Comment by ddurham2** [comment]
@nbarbettini,  I too am interested in this.   It seems like an obvious and justifiable request to want to offer both a Sign Up and Sign In page taht instructs the user on just what to do.

I get setting features.router=true, but I'm unsure what is meant by "bootstrap widget with /signin/register url instead of default /"  I'm in Angular and perhaps that's why I'm unsure, but do you have any idea how I would do that?  TIA
