### ISSUE TITLE
Clarify confusing readme notes about Widget version

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-signin-widget#601]
This part of the readme is confusing readers: https://github.com/okta/okta-signin-widget/blame/master/README.md#L963-L967

These notes are old, since we are now at version 2.14. We should be able to remove them to reduce confusion.

**Comment by haishengwu-okta** [comment]
Certainly there are customers using `<2.7`. Are we really sure to remove it?

**Comment by aarongranick-okta** [comment]
Closing this issue as documentation has been revised many times since this issue was created. We are currently on version 3.8.1
