### ISSUE TITLE
Please upgrade Backbone 1.2.1 to 1.3.3

### ISSUE THREAD

**Issue by durgeshahire4** [okta/okta-signin-widget#602]
In our application we are using Backbone 1.3.3 and in Okta its 1.2.1 so we are getting some errors. 
Can you please upgrade backbone in Okta

**Comment by nbarbettini** [comment]
Hey @durgeshahire4, what are the errors that you are getting. Can you post your package.json file?

**Comment by durgeshahire4** [comment]
@nbarbettini Any Updates on this

**Comment by nbarbettini** [comment]
@durgeshahire4 Can you post the errors you are seeing in your application?

**Comment by durgeshahire4** [comment]
@nbarbettini Please find the below Screenshot

![image](https://user-images.githubusercontent.com/11089569/49921100-77206880-fed2-11e8-9c8a-fc8944a259b5.png)


I have 'this.model' and i am trying to do collection of above model.
'new Backbone.Collection(this.model)'

and Result shows something different 
like attribute inside attribute

so if i try to use 'get' method its break

**Comment by durgeshahire4** [comment]
@nbarbettini Any Updates on This.
Actually I found issue in Lib.
the issue in _isModel funtion. 

Is there any option in Which we can use OKTA lib, by accessing our OWN Backbone lib
Please let me know updates

**Comment by haishengwu-okta** [comment]
@durgeshahire4 
what's build system you're using?
if you're using webpack, I think you could add an `alias` to define the location of OKTA backbone.

**Comment by aarongranick-okta** [comment]
Closing this issue. We are currently using Backbone 1.3.3. However, for anyone else experiencing version mismatch in the future, use webpack `resolve.alias` as suggested.
