### ISSUE TITLE
"The Okta Sign-In Widget is running in development mode" message even after setting production

### ISSUE THREAD

**Issue by matthewdfleming** [okta/okta-signin-widget#624]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x ] bug report
  - [ ] feature request

### Background info

I upgraded to version 2.15.0 of the widget. I'm now seeing the "The Okta Sign-In Widget is running in development mode. When you are ready to publish your app, embed the minified version to turn on production mode." message within the console.

I use webpack and have a plugin defined that adds:
```
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(`production`),
...
```

### Expected behavior

My expectation is that the message would not show up. when using the NODE_ENV setting for my production builds. Am I thinking about this wrong?

### What went wrong?

Not sure. The script is compiled into a vendor.js bundle successfully but this message always shows up.

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

### Your environment

  - Okta Sign-In Widget Version: 2.15.0
  - Browser: Safari and Chrome
  - OS: Mac
  - Language: English

Edit: I'm building/running an Angular (6) application.

**Comment by seangwright** [comment]
I'm using the following import statement in my Angular application and I'm seeing the same warning in the console.

```
import OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in.entry';
```

**Comment by haishengwu-okta** [comment]
thanks for reporting!
yes, `@okta/okta-signin-widget/dist/js/okta-sign-in.entry` is the main file consumed when import just like `import OktaSignIn from '@okta/okta-signin-widget'`.

`@okta/okta-signin-widget/dist/js/okta-sign-in.min` could be alternative.

Sorry for confusing and we'll think it through.

**Comment by seangwright** [comment]
Any help on this one?

When I use the `@okta/okta-signin-widget/dist/js/okta-sign-in.min` in my Angular application the widget loads but the form is missing - only the shell of the widget displays.

The integration instructions are unclear as to what the real differences between the bundles are and all the bundles I've tried are still gigantic. This is supposed to be a widget but it's larger than many client side applications.

**Comment by cniesen** [comment]
I'm getting the same message when importing version 2.19.0 via npm.  Even the minimized CDN version 2.18.0 prints out the same message.

The code [here](https://github.com/okta/okta-signin-widget/blob/34ce5beae9808daa54bdcb3c531396fb1545afcc/src/widget/OktaSignIn.js#L205) really doesn't make sense since it always prints the message.

What's the point of this message anyway?  Just to make sure that your code is minimized?

**Comment by seangwright** [comment]
@cniesen I resolved this issue by extracting the Okta SignIn Widget SDK from my Angular prod bundle and lazily loading the production version of the SDK into my app.

I'm using `"@okta/okta-signin-widget": "2.18.0"`

The prod version of the SDK is `node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.min.js`

Here are the typings I used for Typescript

```
declare class OktaSignIn {
  constructor(configuration: OktaSignInConfig);
}

interface OktaSignIn {
  renderEl(configuration: { el: string }): void;
  remove(): void;

  session: {
    get: (callback: (repsonse: any) => void) => void;
  };
}

interface OktaSignInConfigAuthParams {
  issuer: string;
  display: 'page';
  scopes: string[];
  responseType: string[];
}

interface OktaSignInConfigi18n {
  en: {
    'primaryauth.username.placeholder': string;
    'primaryauth.username.tooltip': string;
    'error.username.required': string;
    'error.password.required': string;
  };
}

interface OktaSignInConfig {
  baseUrl: string;
  logo: string;
  clientId?: string;
  redirectUri?: string;
  authParams: OktaSignInConfigAuthParams;
  i18n: OktaSignInConfigi18n;
}
```

I used `"scriptjs": "2.5.9"` to do the lazy loading (promise based) of the separately deployed SDK script into my app.

Using the above version of the SDK ensures that dev-mode message will not be displayed.

**Comment by aarongranick-okta** [comment]
@matthewdfleming @seangwright This should be resolved since this PR was merged: https://github.com/okta/okta-signin-widget/pull/999

If you are still experiencing this issue, please upgrade to the current version of the widget (currently 3.8.1)

**Comment by matthewdfleming** [comment]
I upgraded to 3.8.1 and the message is gone when building for production.

**Comment by fredsvanelli** [comment]
This problem is happening again on `v7.11.1` with React 18 and Webpack 5.

The best solution to remove the warning seemed to be to import the minified version:
```
import OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in.min';
```

But this would break the type definitions, since Typescript would not recognize the types anymore. A workaround for this can be to redirect it to the original file: 

```
declare module '@okta/okta-signin-widget/dist/js/okta-sign-in.min' {
    import OktaSignIn from '@okta/okta-signin-widget';
    export * from '@okta/okta-signin-widget';
    export default OktaSignIn;
}
```
The solution above fixes the Typescript problem.

But now, the other problem is that Webpack 5 doesn't allow importing from `@okta/okta-signin-widget/dist/js/okta-sign-in.min` since it's not explicitly exported as a module from this package:
```
ERROR in ./src/auth/oktaSignInWidget.tsx 26:45-80
Module not found: Error: Package path ./dist/js/okta-sign-in.min.js is not exported from package /node_modules/@okta/okta-signin-widget

```

A possible workaround for this would be to force an alias on `webpack.config.js` and import from the original module:
```
module.exports = {
  // ...
  resolve: {
    alias: {
      '@okta/okta-signin-widget$': '@okta/okta-signin-widget/dist/js/okta-sign-in.min.js'
    }
  }
};
```

bot this solution would make impossible to import the CSS:
```
import '@okta/okta-signin-widget/dist/css/okta-sign-in.min.css';

👆 This wouldn't work anymore due to the alias 
```

So far I wasn't able to remove the development mode warning using React 18 and Webpack 5.

Any suggestions?
