### ISSUE TITLE
Google Idp button icon

### ISSUE THREAD

**Issue by alexpx** [okta/okta-signin-widget#631]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [*] bug report
  - [ ] feature request

### Background info

Right now the Google Idp button icon has the Google plus icon.
Since this API is deprecated and you have already released a fix for that in the Okta OIDC flow, I expect the icon to be changed as well.

### Steps to reproduce

Just add Google as Idp provider and check the button  icon

### Your environment

  - Okta Sign-In Widget Version: 2.15.0

**Comment by haishengwu-okta** [comment]
@alexpx thanks for reporting and we're working on. stay tune.
