### ISSUE TITLE
Update handlebars

### ISSUE THREAD

**Issue by Z3r021** [okta/okta-signin-widget#639]
### Background info

NPM is reporting a vulnerability with handlebars.

### Expected behavior

handlebars updated to >- 4.0.13

### What went wrong?

=== npm audit security report ===
High - Prototype Pollution
Package: handlebars
Patched In: >=4.0.13
Dependency Of: @okta/okta-signin-widget   
Path: @okta/okta-signin-widget > handlebars 
More Info: https://npmjs.com/advisories/755   

### Your environment

  - Okta Sign-In Widget Version: 2.15.0

**Comment by swiftone** [comment]
Thanks for the note, we'll put this update on our list.

**Comment by Z3r021** [comment]
@swiftone, any speculation on target for next release? Trying to determine if we go with a forked version for now or wait, if the release is not too far off. I am new to contributing, so their may be something posted somewhere answer this, I was not able to find it if there was one. :)

**Comment by fuzzthink** [comment]
When will 2.18 be published to npm? Unable to install handlebars fix without version published to npm.

**Comment by swiftone** [comment]
@fuzzthink A teammate is literally tweaking the release notes now, so while it might take some time to trickle through through our CI process, 2.17 (not 2.18) which will have this change should be on npm Very Soon (tm).

**Comment by haishengwu-okta** [comment]
@fuzzthink `2.17` has been published. let us know if any more questions.
https://www.npmjs.com/package/@okta/okta-signin-widget/v/2.17.0
