### ISSUE TITLE
Release 2.18 is not found on oktacdn.com

### ISSUE THREAD

**Issue by pinkhominid** [okta/okta-signin-widget#678]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Release 2.18 is 404 Not Found on oktacdn.com.

### Expected behavior

CDN should respond with the requested file.

### What went wrong?

404 PAGE NOT FOUND We couldn't find the page you were looking for.

### Steps to reproduce

Try the following URL in your browser, https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.18.0/js/okta-sign-in.min.js

### Your environment

  - Okta Sign-In Widget Version: 2.18.0
  - Browser: Chrome, Firefox, Safari
  - OS: MacOS
  - Language: En

**Comment by haishengwu-okta** [comment]
@pinkhominid 
sorry about that but it takes a little while for 2.18 hit okta cdn. Will ping here once it got deploy.

**Comment by pinkhominid** [comment]
@haishengwu-okta, thanks for the quick reply.

What is typical?

I can get it from unpkg (https://unpkg.com/@okta/okta-signin-widget@2.18.0/dist/js/okta-sign-in.min.js), but I'm getting much better response times from oktacdn.

**Comment by haishengwu-okta** [comment]
Typically it's about 2 weeks after released to npmjs until it hits okta cdn.
It's not ideal and we're still working to close this gap (hit npmjs and cdn at same time). Stay tune.

**Comment by pinkhominid** [comment]
Just checked. It's available now :)
