### ISSUE TITLE
The openid scope is incorrectly removed from authentication requests if getIdToken is false

### ISSUE THREAD

**Issue by alencool** [okta/okta-signin-widget#685]
### I'm submitting a
  - [x] bug report

### Background info
Acquiring an access token using the okta sign in widget, without requesting an `id_token` and having the minimal scope `openid` should be possible

In the authorization request, `openid` has been unnecessarily removed from scopes by the util function `addOrRemoveOpenIdScope` from util/OAuth2Util.js if `id_token` is not requested.

This is incorrect behavior as `openid` is the minimum scope required for authentication requests as stated in okta's own documentation.
https://developer.okta.com/docs/api/resources/oidc/#request-parameters
> openid is required for authentication requests. Other scopes may also be included.

And is possible with okta own example application
https://okta-oidc-fun.herokuapp.com

### Expected behavior

`openid` is not spliced out of the authentication request, and the authentication request is successful.

### What went wrong?
`openid` was spliced out of the authentication request and an error response 
```The authorization server resource does not have any configured default scopes, 'scope' must be provided```
was then produced.

### Steps to reproduce
In configuration of `showSignInToGetTokens()`
set getAccessToken: true,
set getIdToken: false,
set scope: 'openid'

Attempt to sign in.

### Your environment

  - Okta Sign-In Widget Version: 2.14.0
  - Browser: Chrome 73.0.3683.103
  - OS: macOS Mojave
  - Language: english

**Comment by aarongranick-okta** [comment]
Internal ref:
