### ISSUE TITLE
Link registration email verification back to the app hosting the widget.

### ISSUE THREAD

**Issue by johneakin** [okta/okta-signin-widget#710]
In the registration email that is sent from a new signup on the Link registration email verification back to the app hosting the widget..
If the user clicks the button in the email to verify their account they are then routed back to the Okta dashboard. Is it not possible to route the user back to the app that was hosting the Link registration email verification back to the app hosting the widget.?

**Comment by swiftone** [comment]
Hi @johneakin!  For questions about using our SDKs and product offerings like this, I recommend checking out our [dev forums](https://devforum.okta.com/).  

This post might have the answers you are looking for: https://devforum.okta.com/t/custom-activation-flow-whats-the-best-practice/1440
