### ISSUE TITLE
Localization does not work

### ISSUE THREAD

**Issue by ttvrdon** [okta/okta-signin-widget#723]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

React app using octa-signin-widget.

### Expected behavior

If one of supported languages (described here: https://github.com/okta/okta-signin-widget#language-and-text) is used, widget should load localized texts.
I'm using 'cs'

### What went wrong?

Failed to load resource: the server responded with a status of 404 ()
https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.20.0/labels/jsonp/login_cs.jsonp?callback=jsonp_login

https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.20.0/labels/jsonp/country_cs.jsonp?callback=jsonp_country

widget is (after receiving 404 errors) displayed in default language

### Steps to reproduce

set language property to 'cs'

### Your environment

  - Okta Sign-In Widget Version: 2.20.0
  - Browser: Chrome (v. 75.0.3770.80)
  - OS: Windows 10 Enterprise
  - Language: OS language - English

**Comment by haishengwu-okta** [comment]
Thanks for reporting but it's probably because we didn't deploy `2.20` yet. Please give another try tomorrow and let us know.

**Comment by dancrevier** [comment]
I'm still seeing this for Japanese. Is there a way to get this fixed or some workaround? https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.20.1/labels/jsonp/login_ja.jsonp?callback=jsonp_login can't be found in my case.

**Comment by haishengwu-okta** [comment]
hi @dancrevier 
please try `2.20.0` instead of `2.20.1`. We still in the process solving the gap between npm release and CDN deployment.

**Comment by smelyakov** [comment]
seems broken again since `3.0.1`

**Comment by swiftone** [comment]
@smelyakov - We're not encountering any such issues with the 3.x versions - Can you provide details as to what you are seeing?

**Comment by smelyakov** [comment]
@swiftone the issue has gone for the latest version. But I guess it still happens for some of the prior versions.
https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/3.X.X/labels/jsonp/country_%LANG%.jsonp?callback=jsonp_country is not available for all of them

**Comment by swiftone** [comment]
@smelyakov - Thanks for the update.  Barring security issues, we don't update previous versions, so I'm closing the issue as the current version is working correctly.

Please create a new issue if you encounter any such failures in a current version.
