### ISSUE TITLE
SignIn Widget renders empty

### ISSUE THREAD

**Issue by tristanheilman** [okta/okta-signin-widget#728]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x ] bug report
  - [ ] feature request

### Background info

Today I ran a npm update and updated @okta/okta-signin-widget to version 2.20.1 and immediately noticed problems. The sign in widget would render on my login page, but would render an empty white block element.

### Expected behavior

What should have happened? 
The widget should have rendered with all elements visible and functional.

### What went wrong?

No log/error messages were produced.

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

Before update: running @okta/okta-signin-widget: "^2.19.0", @okta-react: "^1.2.0"
After update: running @okta/okta-signin-widget: "^2.20.1", @okta-react: "^1.2.0"
Serve the application and proceed to signing in. When the page renders the sign in widget div will be visible (if color is different than background), but the contents within the widget will not be visible. No buttons, text boxes, label, etc. Just a blank div.

Rolling the version back to "^2.19.0" fixes the issue.

### Your environment

  - Okta Sign-In Widget Version: 2.20.1
  - Browser: Chrome
  - OS: Mac
  - Language: Javascript/Reacjs

**Comment by swiftone** [comment]
@tristanheilman - We're unable to reproduce this issue locally
- Do you have a build process involved?
- Are there any messages in the JS Dev console?

**Comment by tristanheilman** [comment]
I believe I updated other dependencies along with the sign-in widget which broke caused the error. I reverted back to the older versions and only updated okta. Problem solved.
