### ISSUE TITLE
Renders empty after jquery 3.4 is installed

### ISSUE THREAD

**Issue by aarongranick-okta** [okta/okta-signin-widget#731]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [ X  ] bug report
  - [ ] feature request

### Background info

Although the SIW is webpacked with all dependencies, it is still affected by local versions of jquery node module installed by the parent application.

### Expected behavior
As a client-side widget, SIW should be bundled with all dependencies (backbone, jquery, etc.) included and should not be affected by other versions of these modules being installed alongside the SIW in node_modules of the application.

### What went wrong?
The SIW will not render any form elements after installing jquery@3.4 in a sample application.

### Steps to reproduce
I used the React sample application. On a clean install everything works as expected. After `npm i jquery@3.4` the SIW no longer renders correctly.
<img width="671" alt="Screen Shot 2019-06-19 at 5 41 32 PM" src="https://user-images.githubusercontent.com/47947204/59810325-86d19d00-92b9-11e9-826e-ca7c74918760.png">

![siw](https://user-images.githubusercontent.com/47947204/59810276-4e31c380-92b9-11e9-9fdd-1c3cb8c5854b.gif)

### Your environment

  - Okta Sign-In Widget Version: 2.21
  - Browser:
  - OS:
  - Language:

**Comment by aarongranick-okta** [comment]
Related: https://github.com/okta/okta-signin-widget/issues/378

**Comment by robertjd** [comment]
@aarongranick-okta do you see the same behavior if you use the `dev-3.0` branch of the widget?

**Comment by haishengwu-okta** [comment]
@aarongranick-okta did you have chance to confirm if it's fixed on `3.x` ?

**Comment by aarongranick-okta** [comment]
I am seeing no issues with the current version of `samples-js-react` which uses SIW v. 3.2
