### ISSUE TITLE
custom authorization server not working in newly exposed authClient

### ISSUE THREAD

**Issue by BassplayerPatrick** [okta/okta-signin-widget#760]
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

I have the okta-signin-widget running in my self-hosted login-page. I have configured a custom authorization server to support login to my applications using the authorization code flow and hiding the okta dashboard from the users.
Here's my code to support the single sign-on experience using the widget:
```javascript
        this.oktaSignIn = this.okta.getWidget(config);
        console.log('##### widget initialized #####');
        this.oktaSignIn.authClient.session.get()
          .then(session => {
          console.log('Response session status = ' + session.status);
            if (session.status === 'ACTIVE') {
              this.oktaSignIn.authClient.token.getWithRedirect({
                sessionToken: session.sessionToken,
                responseType: 'code',
                scopes: ['openid', 'profile', 'email'],
                state: config.state,
                nonce: config.nonce
              });
            } else {
              console.log('##### Inactive session. Render login widget #####');
              this.oktaSignIn.renderEl({el: '#okta-login-container'});
            }
        }).catch(error => {
            console.log('Response error = ' + error);
            console.log('##### Render login widget #####');
            this.oktaSignIn.renderEl({el: '#okta-login-container'});
        });
```
config looks like this:
```javascript
      const config = {
        baseUrl: environment.oktaBaseURL,
        clientId: options.clientId,
        redirectUri: options.redirectUri,
        recoveryToken: options.recoveryToken,
        authParams: {
          display: 'page',
          responseType: options.responseType,
          issuer: environment.issuer,
          scopes: ['openid', 'profile'],
          state: options.state,
          nonce: options.nonce
        }
      };
```
The values in options are extracted from the url query-parameters
- environment.oktaBaseURL = https://< my-org >.oktapreview.com
- environment.issuer = authorizationServerId

### Expected behavior

- When a user browses to an applicatiion, he will be redirected to the login-page because he has no valid access- or id-token yet.
- The user logs in succesfully, and is redirected back to the application with an authorizationcode (from the configured custom authorization server) in the url query parameters
- The application exchanges this code for an access- and/or id-token and the user authentication process is completed
- Then the user navigates to an other application which doesn't know the user is already logged in and gets redirected to the loginpage again
- The loginpage now detects an already active (okta-) session and retrieves a new authorization code from the configured custom authorization server which is sent in the url query parameters during the redirect back to the second application
- The second application exchanges this code for an access- and/or id-token and the user authentication process is completed again

### What went wrong?

When the second application tries to exchange the authorization code for an access and/or id-token, it receives an error message: "The grant was issued for another authorization server."

By exploring the source code i came to the conclusion that the newly exposed authClient object in the widget does not respect the configured issuer (authorizationServerId) but always resolves to the **default** authorization uri.

I managed to fix this issue locally by modifying the okta-signin-widget code in OktaSignIn.js (from line 110) like:
```javascript
    var authClient = new OktaAuth({
      url: options.baseUrl,
      transformErrorXHR: Util.transformErrorXHR,
      headers: {
        'X-Okta-User-Agent-Extended': 'okta-signin-widget-' + config.version
      },
      clientId: options.clientId,
      issuer: options.authParams.issuer,
      authorizeUrl: options.authParams.authorizeUrl,
      redirectUri: options.redirectUri
    });
    _.extend(this, LoginRouter.prototype.Events, getProperties(authClient, LoginRouter, Util, options));
```
by adding issuer and authorizationUrl. I had to add authorizationUrl to the authParams in config. Not sure if issuer really makes a difference, but issuer combined with url (baseUrl)  should be enough to recreate the correct authorizationUrl

### Steps to reproduce

See the steps in Expected behavior. You'll need a custom sign-in page, utilizing the okta-signin-widget, **NOT** hosted by okta and an application (frontend+backend) which implements the authorization code flow exclusively. Instead of creating the second application, you can mimic this by visiting the loginpage via the same url that is used by the application to redirect the user to the loginpage. 

### Your environment

  - Okta Sign-In Widget Version: 3.0.3
  - Browser: any
  - OS: any
  - Language: any

**Comment by matthewdfleming** [comment]
I was able to work around this somewhat with
```
this.oktaSignIn.authClient.session.get()
    .then((res) => {
        if (res.status === 'ACTIVE') {
            // we have a valid Okta session, fetch new access tokens
            this.oktaSignIn.authClient.token.getWithoutPrompt({
                    responseType: ['id_token', 'token'],
                    scopes: ['openid', 'email', 'profile'],
                    sessionToken: res.sessionToken
                },
                {
                    issuer: 'https://customurl/oauth2/default'
                }).then((token) => {
                // all good let's go
                this.oktaSignIn.authClient.tokenManager.add(ID_TOKEN_KEY, token[0]);
                this.oktaSignIn.authClient.tokenManager.add(USER_ACCESS_TOKEN_KEY, token[1]);
                this.loginSuccess();
            }).catch(() => {
                this.removeSignIn();
                this.showLogin();
            });
        } else {
            // no active Okta session, need to login again
            this.showLogin();
        }
    })
    .catch(() => {
        // no active Okta session, need to login again
        this.showLogin();
    })
;
```

The key is the second argument to `getWithoutPrompt`.. I didn't check `getWithRedirect` but it may have a similar kind of signature.

**Comment by BassplayerPatrick** [comment]
@matthewdfleming Thanks! Your work-around indeed works. I resolved my issue by using the same work-around, although I still consider this a bug, because it should use the same issuer as during initializing, just like it's using the same baseUrl.

**Comment by aarongranick-okta** [comment]
@matthewdfleming We have pushed a new Signin widget with an updated okta-auth-js library which implements the desired behavior (all authParams will be passed to okta-auth-js at construction). So there should be no need for the workaround anymore.
