### ISSUE TITLE
Wrong text on Facebook button for ru_RU locale

### ISSUE THREAD

**Issue by GinoPane** [okta/okta-signin-widget#836]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [*] bug report

### Background info

We've added a Facebook log-in button via widget settings for Okta hosted log-in page and it looks like this in the system with Russian locale:

![image](https://user-images.githubusercontent.com/3897579/63103308-c264ac80-bf74-11e9-8f49-e2ee03e2aa04.png)

### Expected behavior

The button text should say something like "Log-in with Facebook" (Войдите с помощью Фэсбука)

### What went wrong?

But, instead, it says "Register with Facebook" ("Регистрация с помощью учетной") and it even does not fit into button dimensions.

### Your environment

  - Okta Sign-In Widget Version: 3.latest
  - Browser: Chrome latest
  - OS: Linux Mint 18.3
  - Language: ru_RU

Can we do something in widget setup to resolve the issue?

**Comment by swiftone** [comment]
Reported to translation team.  Closing this ticket as we don't track that work on GH.  Thanks for the report and detail @GinoPane.
