### ISSUE TITLE
Cannot import okta sign in widget in polymer application

### ISSUE THREAD

**Issue by shanushka** [okta/okta-signin-widget#857]
#560 # I'm submitting a
  - [x] bug report

Issue

**When importing OktaSign In**

``` import OktaSignIn from '@okta/okta-signin-widget';```

It Throws the following error 
```
SyntaxError: The requested module '../../../node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.entry.js' does not provide an export named 'default'
Describe your issue or request here (if necessary).
```

**Again, when I try to open it in this way:**

```import * as OktaSignIn from '@okta/okta-signin-widget';```

It Throws the following error: 
```TypeError: Cannot read property 'noConflict' of undefined```

**Comment by swiftone** [comment]
@shanushka  - Thanks for the report.   The signin-widget doesn't support `import` at this time - try using `require` and see if that works better.
