### ISSUE TITLE
Undefined variable: "$fonts" when trying to use OktaThemeStyle (okta-theme.scss)

### ISSUE THREAD

**Issue by Lewissss** [okta/okta-signin-widget#871]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Describe your issue or request here (if necessary).

When trying to use the OktaThemeStyle within a Nuxt project, we are getting the error: "Undefined variable: "$fonts" (Okta-theme.scss (line 61, column 18)).

This has only started happening since we updated from v2.20.0 to v3.2.1. We are unable to revert to the previous verson due to critical flaws within the JQuery package dependency. 

### Expected behavior

What should have happened? 

We expect to be able to use the OktaTheme and have it correctly render on the page. 

### What went wrong?

Please provide log or error messages if applicable.

undefined
                ^
      Undefined variable: "$fonts".
      in #####\node_modules\@okta\okta-signin-widget\dist\sass\okta-theme.scss (line 61, column 18)

### Steps to reproduce

When using a Nuxt project, import the OktaThemeStyle file (using either require or import) into a client side page. When trying to build, you are presented with the error message above.

### Your environment

  - Okta Sign-In Widget Version: 3.2.1
  - Browser: Chrome
  - OS: Windows
  - Language: English

**Comment by swiftone** [comment]
The theme was removed in 3.x of the widget, see the instructions here: https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md
