### ISSUE TITLE
Signin widget is zoomed and off center in iOS 13.*

### ISSUE THREAD

**Issue by nodediggity** [okta/okta-signin-widget#914]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

Describe your issue or request here (if necessary).

In iOS 13, when using the `signInWithBrowser` method on the iOS lib, the sign in widget is zoomed and off center. 

![screen offset](https://user-images.githubusercontent.com/25435000/66581027-456e4180-eb77-11e9-8fe5-2bc4385692d3.gif)

### Expected behavior

The page should be centered when focusing on the input fields.

### What went wrong?

This is due to iOS Safari's default behaviour of zooming if the font-size is less than 16px

I was able to fix for now using 
```css
#okta-sign-in.auth-container .okta-form-input-field input {
  font-size: 16px;
}
```

### Steps to reproduce

Launch login using Safari in iOS. (see attached gif)

### Your environment

  - Okta Sign-In Widget Version: latest (3)
  - Browser: iOS Safari
  - OS: iOS 13.2
  - Language: English

**Comment by swiftone** [comment]
@nodediggity - Thanks for the report and the detailed cause-and-potential-fix!

**Comment by swiftone** [comment]
Internal reference: OKTA-255326

**Comment by stefan22** [comment]
Adding a zoom normal property, it also fixes the problem in IOS devices

.okta-form-input-field input {
   zoom: normal !important;
}
