### ISSUE TITLE
Quickstart Guide does not work with Sign-In Widget 3.2.0+

### ISSUE THREAD

**Issue by mraible** [okta/okta-signin-widget#947]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

The code from the QuickStart Guide does not work with v3.2.0+.

### Expected behavior

I expect the documentation to work with the latest version. It works with 2.16.0 (for example, in https://developer.okta.com/blog/2018/06/08/add-authentication-to-any-web-page-in-10-minutes).

Here's the code I'm using:

```html
<html>
  <head>
    <script src="https://global.oktacdn.com/okta-signin-widget/3.4.0/js/okta-sign-in.min.js" type="text/javascript"></script>
    <link href="https://global.oktacdn.com/okta-signin-widget/3.4.0/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>
  </head>
  <body>
    <div id="okta-login-container"></div>
    <script type="text/javascript">
      var oktaSignIn = new OktaSignIn({
        baseUrl: "https://dev-133320.okta.com",
        clientId: "0oa1pnqwx0wgyW2n3357",
        authParams: {
          issuer: "https://dev-133320.okta.com/oauth2/default",
          responseType: ['token', 'id_token'],
          display: 'page'
        }
      });
      if (oktaSignIn.token.hasTokensInUrl()) {
        oktaSignIn.token.parseTokensFromUrl(
          function success(tokens) {
            // Save the tokens for later use, e.g. if the page gets refreshed:
            // Add the token to tokenManager to automatically renew the token when needed
            tokens.forEach(token => {
              if (token.idToken) {
    
                signIn.tokenManager.add('idToken', token);
              }
              if (token.accessToken) {
                signIn.tokenManager.add('accessToken', token);
              }
            });
    
            // Say hello to the person who just signed in:
            var idToken = signIn.tokenManager.get('idToken');
            console.log('Hello, ' + idToken.claims.email);
    
            // Remove the tokens from the window location hash
            window.location.hash='';
          },
          function error(err) {
            // handle errors as needed
            console.error(err);
          }
        );
      } else {
        oktaSignIn.session.get(function (res) {
          // Session exists, show logged in state.
          if (res.status === 'ACTIVE') {
            console.log('Welcome back, ' + res.login);
            return;
          }
          // No session, show the login form
          oktaSignIn.renderEl(
            { el: '#okta-login-container' },
            function success(res) {
              // Nothing to do in this case, the widget will automatically redirect
              // the user to Okta for authentication, then back to this page if successful
            },
            function error(err) {
              // handle errors as needed
              console.error(err);
            }
          );
        });
      }
    </script>
  </body>
</html>
```

### What went wrong?

Error is:

```
Uncaught TypeError: Cannot read property 'hasTokensInUrl' of undefined
```

### Steps to reproduce

Create `index.html` with code above. Run in a browser.

### Your environment

  - Okta Sign-In Widget Version: 3.4.0	
  - Browser: Chrome 78
  - OS: macOS
  - Language: English

**Comment by amok** [comment]
neither with 3.4.0

**Comment by mraible** [comment]
I tried this again today and our docs are still out of date. I'm using [this guide](https://developer.okta.com/quickstart-fragments/widget/default-example/#configure-the-sign-in-widget) with version 3.5.0. 

The docs say to use `oktaSignIn.token.hasTokensInUrl()`, but that's no longer a function.  The GitHub repo [shows that you should use `oktaSignIn.hasTokensInUrl()`](https://github.com/okta/okta-signin-widget#hastokensinurl).

**Comment by mraible** [comment]
There's a [section in the README of this project](https://github.com/okta/okta-signin-widget#authclient) that explains the reason for this:

> Before version 3.0, the Sign-in Widget contained `session` and `tokenManager` properties, and methods like `tokenManager.get`. These were just proxies to identical objects and methods in the [AuthJS](https://github.com/okta/okta-auth-js#api-reference) base library. These proxies have been removed in favor of direct access to the authClient object which allows you to call any of these methods. All the methods are documented in the [AuthJS](https://github.com/okta/okta-auth-js#api-reference) base library.

Here's a working version with 3.5.0 and implicit flow:

```html
<html>
<head>
  <title>Okta Sign-In Widget QuickStart</title>
  <script src="https://global.oktacdn.com/okta-signin-widget/3.5.0/js/okta-sign-in.min.js"
          type="text/javascript"></script>
  <link href="https://global.oktacdn.com/okta-signin-widget/3.5.0/css/okta-sign-in.min.css" type="text/css"
        rel="stylesheet"/>
</head>
<body>
<div id="okta-login-container"></div>

<script type="text/javascript">
  var oktaSignIn = new OktaSignIn({
    baseUrl: 'https://dev-133320.okta.com',
    clientId: '0oa2apgdomrOSH74w357',
    authParams: {
      issuer: 'default',
      responseType: ['token', 'id_token'],
      display: 'page'
    }
  });
  if (oktaSignIn.hasTokensInUrl()) {
    oktaSignIn.authClient.token.parseFromUrl().then(function success(tokens) {
        // Save the tokens for later use, e.g. if the page gets refreshed:
        // Add the token to tokenManager to automatically renew the token when needed
        tokens.forEach(token => {
          if (token.idToken) {
            oktaSignIn.authClient.tokenManager.add('idToken', token);
          }
          if (token.accessToken) {
            oktaSignIn.authClient.tokenManager.add('accessToken', token);
          }
        });

        // Say hello to the person who just signed in:
        oktaSignIn.authClient.tokenManager.get('idToken').then(function (idToken) {
          console.log('Hello, ' + idToken.claims.email);
        });

        // Remove the tokens from the window location hash
        window.location.hash = '';
      },
      function error(err) {
        // handle errors as needed
        console.error(err);
      }
    );
  } else {
    oktaSignIn.authClient.session.get().then(function (res) {
      // Session exists, show logged in state.
      if (res.status === 'ACTIVE') {
        console.log('Welcome back, ' + res.login);
        return;
      }
      // No session, show the login form
      oktaSignIn.renderEl(
        {el: '#okta-login-container'},
        function success(res) {
          // Nothing to do in this case, the widget will automatically redirect
          // the user to Okta for authentication, then back to this page if successful
        },
        function error(err) {
          // handle errors as needed
          console.error(err);
        }
      );
    });
  }
</script>
</body>
</html>
```

**Comment by mraible** [comment]
Here's a working version with Authorization Code Flow and PKCE:

```html
<html>
<head>
  <title>Okta Sign-In Widget QuickStart</title>
  <script src="https://global.oktacdn.com/okta-signin-widget/3.5.0/js/okta-sign-in.min.js"
          type="text/javascript"></script>
  <link href="https://global.oktacdn.com/okta-signin-widget/3.5.0/css/okta-sign-in.min.css" type="text/css"
        rel="stylesheet"/>
</head>
<body>
<div id="okta-login-container"></div>

<script type="text/javascript">
  var oktaSignIn = new OktaSignIn({
    baseUrl: 'https://{yourOktaDomain}',
    redirectUri: window.location.origin,
    clientId: '{yourClientId}',
    authParams: {
      pkce: true,
      responseType: ['token', 'id_token']
    }
  });

  oktaSignIn.authClient.session.get().then(function (res) {
    // Session exists, show logged in state.
    if (res.status === 'ACTIVE') {
      console.log('Welcome back, ' + res.login);
      oktaSignIn.authClient.token.getWithoutPrompt({
        scopes: ['openid', 'email', 'profile'],
      }).then((tokens) => {
        tokens.forEach(token => {
          if (token.idToken) {
            oktaSignIn.authClient.tokenManager.add('idToken', token);
          }
          if (token.accessToken) {
            oktaSignIn.authClient.tokenManager.add('accessToken', token);
          }
        });

        // Say hello to the person who just signed in
        oktaSignIn.authClient.tokenManager.get('idToken').then(idToken => {
          console.log(`Hello, ${idToken.claims.name} (${idToken.claims.email})`);
        });
      }).catch(error => console.error(error));
      return;
    }
    // No session, show the login form
    oktaSignIn.renderEl(
      {el: '#okta-login-container'},
      function success(res) {
        // Nothing to do in this case, the widget will automatically redirect
        // the user to Okta for authentication, then back to this page if successful
      },
      function error(err) {
        // handle errors as needed
        console.error(err);
      }
    );
  });

</script>
</body>
</html>
```

**Comment by AbhishekVermaExternlabs** [comment]
I am getting this error please tell me how to fix it.
{(okta 400 Bad Request :-(Your request resulted in an error. The 'redirect_uri' parameter must be a Login redirect URI in the client app settings: https://dev-48230991-admin.okta.com/admin/app/oidc_client/instance/0oa4ersgjpwHoQqmg5d7#tab-general)}
 <script>
    function myempFunction() {
      var eid = document.forms["myEmpForm"]["empId"].value;
      if (eid == 20) {
        var url = 'https://{yourOktaDomain}';
        var cid = '{yourClientId}';
        var iss = 'https://${yourOktaDomain}/oauth2/default';
      } else if (eid == 40) {
         var url = 'https://{yourOktaDomain}';
        var cid = '{yourClientId}';
        var iss = 'https://${yourOktaDomain}/oauth2/default';
      }
      else {
        alert("Invalid Employer ID");
      }
      console.log(url);
      var oktaSignIn = new OktaSignIn({
        baseUrl: url,
        clientId: cid,
        // redirectUri: window.location.href = "http://localhost:5500/login/callback",
        authParams: {
          issuer: iss,
          responseType: ['token', 'id_token'],
          display: 'page'
        }
      });
      
      if (oktaSignIn.token.hasTokensInUrl()) {
        oktaSignIn.token.parseTokensFromUrl(
          // If we get here, the user just logged in.
          function success(res) {
            var accessToken = res[0];
            var idToken = res[1];
            oktaSignIn.tokenManager.add('accessToken', accessToken);
            oktaSignIn.tokenManager.add('idToken', idToken);
            window.location.hash = '';
            document.getElementById("messageBox").innerHTML = "Hello, " + idToken.claims.email + "! You just logged in! :)";
          },
          function error(err) {
            console.error(err);
          }
        );
      } else {
        oktaSignIn.session.get(function (res) {
          // If we get here, the user is already signed in.
          if (res.status === 'ACTIVE') {
            console.log(res);
            document.getElementById("messageBox").innerHTML = "Hello, " + res.login + "! You are *still* logged in! :)";
            return;
          }
          oktaSignIn.renderEl(
            { el: '#okta-login-container' },
            function success(res) { },
            function error(err) {
              console.error(err);
            }
          );
        });
      }
    } //myempFunction end
  </script>

**Comment by mraible** [comment]
It looks like you need to have `http://localhost:5500/login/callback` listed in your app's Sign-In Redirect URIs.

**Comment by JpatelSyngenta** [comment]
Would you happen to have updated code for the Okta super widget with social sign-ins? This is the [link](https://super-widget.oktaprise.com/nav-social) that has the old code but it does not load in for me so I made the change of adding the updated code you provided above and I still cant get the widget to show up.
