### ISSUE TITLE
L10N_ERROR[oktaverify.numberchallenge.instruction]

### ISSUE THREAD

**Issue by jscriptcoder** [okta/okta-signin-widget#969]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I'm having an issue in the NumberChallengeView (see screenshot below)
<img src="https://user-images.githubusercontent.com/613724/69431280-b3418780-0d37-11ea-8aa6-d4b8e3f9ec84.png" width="300" />

Now, I debugged the widget and noticed this line:

https://github.com/okta/okta-signin-widget/blob/b603247b5252d59a8958f9a5701737e9fc5025f6/src/views/mfa-verify/NumberChallengeView.js#L44

Looks like returning `null` is causing this _L10N_ERROR_. If I instead return an empty string, I get the translation key properly replaced, because apparently the templating engine is complaining that the argument is missing:

<img src="https://user-images.githubusercontent.com/613724/69431524-382ca100-0d38-11ea-8c5e-7adebcf4d2a8.png" width="300" />

With a number, which seems to be expecting, the message looks strange since it outputs the number twice. Not sure what's supposed to appear in here:

<img src="https://user-images.githubusercontent.com/613724/69431716-96598400-0d38-11ea-8cb3-661ac73c51b1.png" width="300" />

### Expected behavior

What should have happened? 

Definitely not that ugly message. Above all because the label with the translation key _oktaverify.numberchallenge.instruction_ is there.

### What went wrong?

Looks like there is a bug, or at least it appears to me, by playing around with the value returned by `getTemplateData()`

### Steps to reproduce

Well, send push must be enabled

### Your environment

  - Okta Sign-In Widget Version: 3.4.2
  - Browser: Chrome 78
  - OS: MacOS
  - Language: All languages

**Comment by magizh-okta** [comment]
@jscriptcoder  thanks for filing the issue. I have a few questions and also wanted to give some context on this feature. 

Ideally the UI should look like this.

![Screen Shot 2019-11-22 at 9 22 23 AM](https://user-images.githubusercontent.com/17267130/69446787-069ce100-0d0a-11ea-9cc7-f80e470405a7.png)


 And this only shows up of client (verify apps and backend supports this flow). That said  

1) Are u trying to build/customize the widget and want to check out this feature? 

2) If so are you using any mock data to try this? Can you give more info as to how you got to see this UI ? 

Checkout the test and mockdata for more info https://github.com/okta/okta-signin-widget/pull/884/files#diff-4b2ed50d042dededa6f2af06dc054199R5236

**Comment by jscriptcoder** [comment]
Hi @magizh-okta , thanks for the quick answer, 

Answering your questions:

1. Only customization I'm doing is the re-styling of the widget. I'm hosting the sass files and overriding what's needed, then building the css. I'm not trying to check out this feature. It showed up, apparently, when I upgraded the widget from version 2.13.0 to 3.3.1. But, as you can see this new feature appears along with the "send push" button. Currently, the way I'm solving it is by hiding it:

```css
.number-challenge-view { display: none; }
```

Maybe I'm missing styles? since I'm sticking the the sass files of the previous version... 

Actually when I wrote the previous sentence, I decided to have a quick look at the new sass files and I found this:

https://github.com/okta/okta-signin-widget/blob/master/assets/sass/modules/_mfa-challenge-forms.scss#L72

I can see this is already hidden, and probably it's shown programmatically. No issue then, this is actually my fault for not keeping the sass files up to date.

I guess this issue can be closed. Sorry for the troubles.

Fran

**Comment by restfulhead** [comment]
We're seeing the same issue after upgrading:

![okta-label-issue](https://user-images.githubusercontent.com/558375/74280722-16b1d480-4ceb-11ea-8b9e-9173679c8107.png)

Can this be merged: https://github.com/okta/okta-signin-widget/pull/1010?

**Comment by bretterer** [comment]
@jscriptcoder & @restfulhead - Thank you for confirming this is still an issue, we will pass this along to our team to take a look at the PR.

internal ref: https://oktainc.atlassian.net/browse/OKTA-278094

**Comment by magizh-okta** [comment]
@restfulhead  the backend api response should be returning the number. Can you post a recording of the flow and the api response. 

If you are unable to post the recording can you confirm if you just get this state after primary auth or this show up after showing the old push UI. 

FYI this number challenge view works only when backend flag is on and you should not be seeing this unless the flag is on to combine risk scoring feature with okta verify.

**Comment by magizh-okta** [comment]
Also @restfulhead  I guess you might have not consumed the new sass files and might be missing this change. https://github.com/okta/okta-signin-widget/blob/master/assets/sass/modules/_mfa-challenge-forms.scss#L72

Similar to the https://github.com/okta/okta-signin-widget/issues/969#issuecomment-558069027

Please confirm if it works so we can close the issue.

**Comment by restfulhead** [comment]
Ah, yes, that was it. We weren't pulling the latest styles. I've updated it and no longer see the error. Ticket can be closed, thank you.

**Comment by magizh-okta** [comment]
Great thanks!

**Comment by enchanter5525** [comment]
> Ah, yes, that was it. We weren't pulling the latest styles. I've updated it and no longer see the error. Ticket can be closed, thank you.

wha

> Ah, yes, that was it. We weren't pulling the latest styles. I've updated it and no longer see the error. Ticket can be closed, thank you.

what are those new styles? where can i get those?

**Comment by enchanter5525** [comment]
> Ah, yes, that was it. We weren't pulling the latest styles. I've updated it and no longer see the error. Ticket can be closed, thank you.

what are those new styles and where can i find those exactly?
