### ISSUE TITLE
what event when clicked on login with facebook button?

### ISSUE THREAD

**Issue by novaknole** [okta/okta-signin-widget#975]
### Background info
I am using this plugin. I am not using custom form, but googleIDP and facebookIDP. As the buttons are there, the whole widget gets attached later. So I don't have anything like a button in html.

What I want to do now is when user clicks on login with facebook, I want to have a loader. The thing why I want to have a loader is that sometimes, when I am logged in on facebook and trying to login in on my app later, it takes kind of 3-4 seconds, so That's why I need some way to turn on the loader and when success/error function is called, turn it off. 

How do I do that? how do you do That? I added this question here because if this is not done, I can write it and make a PR then.

Thanks.

### Your environment

  - Okta Sign-In Widget Version: 3.0.0
  - Browser: Chrome
  - OS: Linux
  - Language:

**Comment by aarongranick-okta** [comment]
It should be possible to add a 'click' event handler to the Facebook button after the widget is rendered. See the documentation here: https://github.com/okta/okta-signin-widget#afterrender and please let us know if this helps.
