### ISSUE TITLE
PKCE & code_verifier flow not working

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-signin-widget#979]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info
I'm enabling **PKCE** in order to get the token, but I'm getting a redirection like this:
`my-app://callback#code=aEx5AQDbf-mSmn3xHMhI&state=gycQjIUolkPxgjExV8EneDsnTD8GxxtvjE2WIw9t8RRzzV547hPzPWtFkS6hGiEl`
As you can see this is a deep linking redirection so we don't know the **code_verifier** from the mobile app.

### Expected behavior
Redirect with the token instead of code, because we don't know the `code_verifier` here in order to get the token with a POST request: https://developer.okta.com/docs/guides/implement-auth-code-pkce/exchange-code-token/

### What went wrong?

**PKCE** is not working debugging locally (localhost), `responseType` of the _authorize_ request is still `code`. e.g: `https://.../oauth2/default/v1/authorize?...&response_type=code`

### Steps to reproduce

Current configuration of the widget:
```
this.widget = new OktaSignIn({
  el,
  baseUrl,
  clientId,
  authParams: {
    pkce: true,
    issuer,
    responseType: ['id_token', 'token'],
    display: 'page',
    scopes
  }
});
this.widget.showSignInToGetTokens({
  clientId,
  redirectUri,
  // Return an access token from the authorization server
  getAccessToken: true,
  // Return an ID token from the authorization server
  getIdToken: true
});
```

### Your environment

  - Okta Sign-In Widget Version: 3.4.2
  - Browsers: Chrome, iOS (Safari)
  - OS: macOS Mojave
  - Language: JS

Thanks in advance!

**Comment by aarongranick-okta** [comment]
Hi @jdnichollsc Thanks for the report. We would like to help you solve your issue. A few questions:

What type of application is this? (Web, SPA, native)

Does this login flow involve a native app? (Your example URI contains `my-app://callback` which seems to indicate it does)

In order for PKCE flow to work, the callback must be handled in the same browser and must be on the same domain as the page which initiated login. The reason is that the `code_verifier` is stored in local browser storage prior to the redirect. The value is expected to exist in this same storage location on the callback. The flow should work within a native app as long as login is initiated within the app. If login is initiated on a web page, but the callback is handled in a native app, then we would expect PKCE not to work.

**Comment by jdnichollsc** [comment]
Hi Aaron, yes I'm opening the widget from a Mobile app by using Chrome CustomTabs/SafariViewController, but I'm redirecting to the same Domain too to be able to use PKCE and I don't know how to get the token after redirect, what's the method to get the access token after get the code and state in that redirection?
Thanks for your help! ❤

**Comment by aarongranick-okta** [comment]
The method is `parseFromUrl`, it is part of the `authClient` that is exposed by the signin widget.
I apologize for the state of our documentation on this.

https://github.com/okta/okta-signin-widget#authclient
https://github.com/okta/okta-auth-js#tokenparsefromurloptions
https://developer.okta.com/code/javascript/okta_auth_sdk/

On the callback page, construct an instance of the widget, then call `widget.authClient.token.parseFromUrl()` this returns a promise that will resolve to an array of token objects. These tokens should be saved, something like:
https://github.com/okta/okta-auth-js/blob/master/test/app/src/testApp.js#L268

**Comment by jdnichollsc** [comment]
OMG, thanks! It's working perfect, now I can redirect the user to the mobile app with the token by using another redirection with deep linking 👍 

This is the package I'm using from React Native to open this widget from an external domain :) https://github.com/proyecto26/react-native-inappbrowser

<img width="480" alt="Captura de Pantalla 2019-12-09 a la(s) 7 51 55 p  m" src="https://user-images.githubusercontent.com/2154886/70485700-a655bf80-1abd-11ea-8366-ffc8dbf843a3.png">
