### ISSUE TITLE
Use showSignInToGetTokens with offline_access scope

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-signin-widget#981]
### I'm submitting a
  - [x] bug report

### Background info

It should be possible to use **offline_access** scope for PWA or opening the widget of an external domain from mobile apps (Android/iOS).

### Expected behavior
Get the token with the `offline_access` scope, it works without that scope.

### What went wrong?

I'm getting this error after redirect to the callback route (localhost:3000/callback) and using `widget.authClient.token.parseFromUrl()` to get the token before to redirect to the app by using deep linking:
```
{
  "error": "invalid_scope",
  "error_description": "Browser requests to the token endpoint may not include the offline_access scope."
}
```

### Steps to reproduce
- Using PKCE flow:
```
const scopes = ['openid', 'email', 'profile', 'offline_access']
this.widget = new OktaSignIn({
  el,
  baseUrl,
  clientId,
  authParams: {
    pkce: true,
    issuer,
    responseType: 'code',
    display: 'page',
    scopes
  }
});
this.widget.showSignInToGetTokens({
  clientId,
  redirectUri,
  // Return an access token from the authorization server
  getAccessToken: true,
  // Return an ID token from the authorization server
  getIdToken: true,
  scope: scopes.join(' ')
});
```

- Getting the token after redirect:
`const token = await widget.authClient.token.parseFromUrl();`

### Your environment

  - Okta Sign-In Widget Version: 3.5.0
  - Browser: Chrome
  - OS: macOS Mojave 10.14.6
  - Language: JS

**Comment by swiftone** [comment]
@jdnichollsc - Thanks for the report.  I have a few questions:

Just to make sure we have the full story before speculating:  What is the configuration for your client ID?  A SPA app that has PKCE enabled?

**Comment by jdnichollsc** [comment]
Yes Sir, check our configuration 🙂
![Screenshot_20191216-184040_Chrome](https://user-images.githubusercontent.com/2154886/70952237-9eed6380-2033-11ea-99ad-173c459855ab.jpg)

**Comment by swiftone** [comment]
I did a little digging, and I believe the issue is some confusion over the intent of `offline_access`.   While that sounds right up the alley of a PWA, that scope gives a refresh token, which should NOT be used in a browser-based app (PWAs included).  

As a result, Okta's security flow prevents you from doing that.  I'd recommend discussing your use case with our support team at developers@okta.com to see if they can recommend a better way of achieving your goal.

**Comment by jdnichollsc** [comment]
Thanks Brett for confirming this! 👍
